In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
from os import listdir
import re

import csv
import datetime
import pickle
import os

import calendar
import random as r

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 500)
pd.options.display.float_format = '{:.0f}'.format

In [3]:
DATA_ROOT_PATH="/mnt/data/projects/MD1/data/R1000/reports/"
PROJ_ROOT_PATH="/home/priyesh/projects/MD1"

In [4]:
# Read from Pickle file

filepath = os.path.join(PROJ_ROOT_PATH,'pickle','std_statements_stage4.pkl')
master_std_statements = pd.read_pickle(filepath)

In [5]:
# Read from Pickle file

filepath = os.path.join(PROJ_ROOT_PATH,'pickle','clean_master_data_stage2.pkl')
clean_master_data = pd.read_pickle(filepath)

In [6]:
# Read from Pickle file

filepath = os.path.join(PROJ_ROOT_PATH,'pickle','master_data_stage2.pkl')
master_data = pd.read_pickle(filepath)

In [ ]:
# Read from Pickle file

table_labels = {}

filepath = os.path.join(PROJ_ROOT_PATH,'pickle','mappings_cash_stage3.pkl')
table_labels['cash'] = pd.read_pickle(filepath)
                        
filepath = os.path.join(PROJ_ROOT_PATH,'pickle','mappings_bal_stage3.pkl')
table_labels['balance'] = pd.read_pickle(filepath)
                        
filepath = os.path.join(PROJ_ROOT_PATH,'pickle','mappings_income_stage3.pkl')
table_labels['income'] = pd.read_pickle(filepath)

In [59]:
companyList = list(master_data.keys())
i = r.randint(0,700)
c = companyList[i]
print(c)
master_data[c]['20']['income']

APTV

                                                                                                                                                                                                                                                                                                                                                                                                                                    Consolidated Statements Of Operations - USD ($)  shares in Thousands, $ in Millions  \
                                                                                                                                                                                                                                                                                                                                                                                                                                    Consolidated Statements Of Operations - USD ($)  shares in Thousands, $ in Millions
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Income Statement [Abstract]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Revenues
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Operating expenses:
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Cost of Goods and Services Sold
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Selling, general and administrative
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Amortization
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Restructuring
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Total operating expenses
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Operating income
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Interest expense
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Other expense, net
11                                                                                                                                                                                                                                                                                                                                                                                                                                              Income from continuing operations before income taxes and equity income
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Income tax expense
13                                                                                                                                                                                                                                                                                                                                                                                                                                                               Income from continuing operations before equity income
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Equity income, net of tax
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Income from continuing operations
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Income from discontinued operations, net of tax
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Net income
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Net income attributable to noncontrolling interest
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Net income attributable to Aptiv
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Amounts attributable to Aptiv:
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Income from continuing operations
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Income from discontinued operations
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Net income attributable to Aptiv
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Basic net income per share:
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Income from continuing operations, per basic share
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Income from discontinued operations, per basic share
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Basic net income per share attributable to Aptiv
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Weighted average number of basic shares outstanding
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Diluted net income per share:
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Income from continuing operations, per diluted share
31                                                                                                                                                                                                                                                                                                                                                                                                                                                               Income from discontinued operations, per diluted share
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Diluted net income per share attributable to Aptiv
33                                                                                                                                                                                                                                                                                                                                                                                                                                                                Weighted average number of diluted shares outstanding
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NaN
35  [1] Includes charges recorded in 2019 related to costs associated with employee termination benefits and other exit costs of $104 million for Signal and Power Solutions and $44 million for Advanced Safety and User Experience. [2] Includes charges recorded in 2018 related to costs associated with employee termination benefits and other exit costs of $90 million for Signal and Power Solutions and $19 million for Advanced Safety and User Experience. [3] Includes charges recorded in 2017 related...

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3 Months Ended  \

## Income Sheets

In [28]:
master_data['AOS']['20']['income']

                                                                                                                                                                               CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions  \
                                                                                                                                                                               CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions
0                                                                                                                                                                                                                                Net sales
1                                                                                                                                                                                                                    Cost of products sold
2                                                                                                                                                                                                                             Gross profit
3                                                                                                                                                                                             Selling, general and administrative expenses
4                                                                                                                                                                                                    Restructuring and impairment expenses
5                                                                                                                                                                                                                         Interest expense
6                                                                                                                                                                                                                       Other income - net
7                                                                                                                                                                                               Earnings before provision for income taxes
8                                                                                                                                                                                                               Provision for income taxes
9                                                                                                                                                                                                                             Net Earnings
10                                                                                                                                                                                                  Net Earnings Per Share of Common Stock
11                                                                                                                                                                                          Diluted Net Earnings Per Share of Common Stock
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                                            \
                                                                                                                                                                             CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions.1
0                                                                                                                                                                                                                                      NaN
1                                                                                                                                                                                                                                      NaN
2                                                                                                                                                                                                                                      NaN
3                                                                                                                                                                                                                                      NaN
4                                                                                                                                                                                                                                      NaN
5                                                                                                                                                                                                                                      NaN
6                                                                                                                                                                                                                                      NaN
7                                                                                                                                                                                                                                      NaN
8                                                                                                                                                                                                                                      [1]
9                                                                                                                                                                                                                                      NaN
10                                                                                                                                                                                                                                     NaN
11                                                                                                                                                                                                                                     NaN
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                           12 Months Ended  \
                                                                                                                                                                                                                             Dec. 31, 2019
0                                                                                                                                                                                                                                $ 2,992.7
1                                                                                                                                                                                                                                   1812.0
2                                                                                                                                                                                                                                   1180.7
3                                                                                                                                                                                                                                    715.6
4                                                                                                                                                                                                                                      0.0
5                                                                                                                                                                                                                                     11.0
6                                                                                                                                                                                                                                   (18.0)
7                                                                                                                                                                                                                                    472.1
8                                                                                                                                                                                                                                    102.1
9                                                                                                                                                                                                                                  $ 370.0
10                                                                                                                                                                                                                                  $ 2.24
11                                                                                                                                                                                                                                  $ 2.22
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                                            \
                                                                                                                                                                                                                             Dec. 31, 2018
0                                                                                                                                                                                                                                $ 3,187.9
1                                                                                                                                                                                                                                   1882.4
2                                                                                                                                                                                                                                   1305.5
3                                                                                                                                                                                                                                    753.8
4                                                                                                                                                                                                                                      6.7
5                                                                                                                                                                                                                                      8.4
6                                                                                                                                                                                                                                   (21.2)
7                                                                                                                                                                                                                                    557.8
8                                                                                                                                                                                                                                    113.6
9                                                                                                                                                                                                                                  $ 444.2
10                                                                                                                                                                                                                                  $ 2.60
11                                                                                                                                                                                                                                  $ 2.58
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”


   Dec. 31, 2017
0      $ 2,996.7
1         1764.3
2         1232.4
3          722.8
4            0.0
5           10.1
6         (21.3)
7          520.8
8          224.3
9        $ 296.5
10        $ 1.72
11        $ 1.70
12           NaN
13           NaN

In [32]:
master_data['PEN']['20']['income']

                               Consolidated Statements of Operations - USD ($)  $ in Thousands  \
                               Consolidated Statements of Operations - USD ($)  $ in Thousands
0                                                                  Income Statement [Abstract]
1                                                                                     Revenues
2                                                                              Cost of revenue
3                                                                                 Gross profit
4                                                                          Operating expenses:
5                                                                     Research and development
6                                                            Sales, general and administrative
7                                                 Acquired in-process research and development
8                                                                     Total operating expenses
9                                                                Income (loss) from operations
10                                                                        Interest income, net
11                                                                          Other expense, net
12                  Income before income taxes and equity in losses of unconsolidated investee
13                                                   Provision for (benefit from) income taxes
14                                   Income before equity in losses of unconsolidated investee
15                                                 Equity in losses of unconsolidated investee
16                                                                     Consolidated net income
17                                           Net loss attributable to non-controlling interest
18                                                   Net income attributable to Penumbra, Inc.
19    Net income (loss) attributable to Penumbra, Inc. per share: Basic (in dollars per share)
20  Net income (loss) attributable to Penumbra, Inc. per share: Diluted (in dollars per share)
21                                      Weighted average shares outstanding: Basic (in shares)
22                                    Weighted average shares outstanding: Diluted (in shares)

   12 Months Ended
     Dec. 31, 2019 Dec. 31, 2018 Dec. 31, 2017
0              NaN           NaN           NaN
1        $ 547,405     $ 444,938     $ 333,764
2           175441        152405        116622
3           371964        292533        217142
4              NaN           NaN           NaN
5            51723         36165         31661
6           272733        226385        184316
7                0         30835             0
8           324456        293385        215977
9            47508         (852)          1165
10            2854          2964          2653
11           (227)         (504)       (1,342)
12           50135          1608          2476
13            3131       (4,403)       (3,611)
14           47004          6011          6087
15               0       (3,101)       (1,430)
16           47004          2910          4657
17         (1,454)       (3,691)             0
18        $ 48,458       $ 6,601       $ 4,657
19          $ 1.39        $ 0.19        $ 0.14
20          $ 1.34        $ 0.18        $ 0.13
21        34750706      34138176      32978065
22        36265999      36086821      35319103

In [41]:
master_data['AOS']['20']['income']

                                                                                                                                                                               CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions  \
                                                                                                                                                                               CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions
0                                                                                                                                                                                                                                Net sales
1                                                                                                                                                                                                                    Cost of products sold
2                                                                                                                                                                                                                             Gross profit
3                                                                                                                                                                                             Selling, general and administrative expenses
4                                                                                                                                                                                                    Restructuring and impairment expenses
5                                                                                                                                                                                                                         Interest expense
6                                                                                                                                                                                                                       Other income - net
7                                                                                                                                                                                               Earnings before provision for income taxes
8                                                                                                                                                                                                               Provision for income taxes
9                                                                                                                                                                                                                             Net Earnings
10                                                                                                                                                                                                  Net Earnings Per Share of Common Stock
11                                                                                                                                                                                          Diluted Net Earnings Per Share of Common Stock
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                                            \
                                                                                                                                                                             CONSOLIDATED STATEMENT OF EARNINGS - USD ($)  $ in Millions.1
0                                                                                                                                                                                                                                      NaN
1                                                                                                                                                                                                                                      NaN
2                                                                                                                                                                                                                                      NaN
3                                                                                                                                                                                                                                      NaN
4                                                                                                                                                                                                                                      NaN
5                                                                                                                                                                                                                                      NaN
6                                                                                                                                                                                                                                      NaN
7                                                                                                                                                                                                                                      NaN
8                                                                                                                                                                                                                                      [1]
9                                                                                                                                                                                                                                      NaN
10                                                                                                                                                                                                                                     NaN
11                                                                                                                                                                                                                                     NaN
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                           12 Months Ended  \
                                                                                                                                                                                                                             Dec. 31, 2019
0                                                                                                                                                                                                                                $ 2,992.7
1                                                                                                                                                                                                                                   1812.0
2                                                                                                                                                                                                                                   1180.7
3                                                                                                                                                                                                                                    715.6
4                                                                                                                                                                                                                                      0.0
5                                                                                                                                                                                                                                     11.0
6                                                                                                                                                                                                                                   (18.0)
7                                                                                                                                                                                                                                    472.1
8                                                                                                                                                                                                                                    102.1
9                                                                                                                                                                                                                                  $ 370.0
10                                                                                                                                                                                                                                  $ 2.24
11                                                                                                                                                                                                                                  $ 2.22
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”

                                                                                                                                                                                                                                            \
                                                                                                                                                                                                                             Dec. 31, 2018
0                                                                                                                                                                                                                                $ 3,187.9
1                                                                                                                                                                                                                                   1882.4
2                                                                                                                                                                                                                                   1305.5
3                                                                                                                                                                                                                                    753.8
4                                                                                                                                                                                                                                      6.7
5                                                                                                                                                                                                                                      8.4
6                                                                                                                                                                                                                                   (21.2)
7                                                                                                                                                                                                                                    557.8
8                                                                                                                                                                                                                                    113.6
9                                                                                                                                                                                                                                  $ 444.2
10                                                                                                                                                                                                                                  $ 2.60
11                                                                                                                                                                                                                                  $ 2.58
12                                                                                                                                                                                                                                     NaN
13  [1] In 2017, the Company recorded a one-time charge of $81.8 million associated with U.S. Tax Reform, primarily related to the repatriation of undistributed foreign earnings. For additional information, see Note 15 “Income Taxes.”


   Dec. 31, 2017
0      $ 2,996.7
1         1764.3
2         1232.4
3          722.8
4            0.0
5           10.1
6         (21.3)
7          520.8
8          224.3
9        $ 296.5
10        $ 1.72
11        $ 1.70
12           NaN
13           NaN

In [56]:
master_data['BC']['20']['income']

                                                                                                                                                                                                                                                                                                                                                                                                                                     Consolidated Statements of Operations - USD ($)  shares in Millions, $ in Millions  \
                                                                                                                                                                                                                                                                                                                                                                                                                                     Consolidated Statements of Operations - USD ($)  shares in Millions, $ in Millions
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Income Statement [Abstract]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Net Sales
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Cost of Sales
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Selling, General and Administrative Expense
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Research And Development Expense
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Restructuring, Exit and Impairment Charges
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Operating Earnings
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Equity Earnings
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Pension Settlement Charge
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Other Expense, Net
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Earnings Before Interest and Income Taxes
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Interest Expense
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Interest Income
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Transaction Financing Charges
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Earnings Before Income Taxes
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Income Tax Provision
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Net Earnings from Continuing Operations
17                                                                                                                                                                                                                                                                                                                                                                                                    Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest
18                                                                                                                                                                                                                                                                                                                                                                                                                                                             (Loss) Earnings from Discontinued Operations, Net of Tax
19                                                                                                                                                                                                                                                                                                                                                                                                                                                              Gain on disposal of discontinued operations, net of tax
20                                                                                                                                                                                                                                                                                                                                                                                                                                                         Net (Loss) Earnings from Discontinued Operations, Net of Tax
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Net Earnings (Loss)
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Basic
23                                                                                                                                                                                                                                                                                                                                                                                                                                                           Earnings from Continuing Operations (in Dollars Per Share)
24                                                                                                                                                                                                                                                                                                                                                                                                                                                  Earnings (Loss) from Discontinued Operations (in Dollars Per Share)
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Net Earnings (Loss) (in Dollars per Share)
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Diluted
27                                                                                                                                                                                                                                                                                                                                                                                                                                                           Earnings from Continuing Operations (in Dollars per Share)
28                                                                                                                                                                                                                                                                                                                                                                                                                                                  Earnings (Loss) from Discontinued Operations (in Dollars per Share)
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Net Earnings (Loss) (in Dollars per Share)
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Weighted Average Shares Used for Computation of:
31                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Basic Earnings Per Common Share (in Shares)
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Diluted Earnings Per Common Share (in Shares)
33                                                                                                                                                                                                                                                                                                                                                                                                                                                      Cash Dividends Declared Per Common Share (in Dollars per Share)
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NaN
35  [1] (A) In the second quarter of 2018, the Company announced its intention to wind down Sport Yacht & Yachts (SYY) operations. During the second quarter and the full-year of 2019, SYY had Net sales of $(0.7) million. During the first, second, third and fourth quarters and the full-year of 2018, SYY had Net sales of $15.1 million, $19.9 million, $9.0 million, $5.4 million and $49.4 million, respectively [2] (C) Restructuring, exit, integration and impairment charges are discussed in Note 4 – ...

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        12 Months Ended  \

In [60]:
master_data['APTV']['20']['income']

                                                                                                                                                                                                                                                                                                                                                                                                                                    Consolidated Statements Of Operations - USD ($)  shares in Thousands, $ in Millions  \
                                                                                                                                                                                                                                                                                                                                                                                                                                    Consolidated Statements Of Operations - USD ($)  shares in Thousands, $ in Millions
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Income Statement [Abstract]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Revenues
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Operating expenses:
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Cost of Goods and Services Sold
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Selling, general and administrative
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Amortization
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Restructuring
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Total operating expenses
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Operating income
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Interest expense
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Other expense, net
11                                                                                                                                                                                                                                                                                                                                                                                                                                              Income from continuing operations before income taxes and equity income
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Income tax expense
13                                                                                                                                                                                                                                                                                                                                                                                                                                                               Income from continuing operations before equity income
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Equity income, net of tax
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Income from continuing operations
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Income from discontinued operations, net of tax
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Net income
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Net income attributable to noncontrolling interest
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Net income attributable to Aptiv
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Amounts attributable to Aptiv:
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Income from continuing operations
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Income from discontinued operations
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Net income attributable to Aptiv
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Basic net income per share:
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Income from continuing operations, per basic share
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Income from discontinued operations, per basic share
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Basic net income per share attributable to Aptiv
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Weighted average number of basic shares outstanding
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Diluted net income per share:
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Income from continuing operations, per diluted share
31                                                                                                                                                                                                                                                                                                                                                                                                                                                               Income from discontinued operations, per diluted share
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Diluted net income per share attributable to Aptiv
33                                                                                                                                                                                                                                                                                                                                                                                                                                                                Weighted average number of diluted shares outstanding
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  NaN
35  [1] Includes charges recorded in 2019 related to costs associated with employee termination benefits and other exit costs of $104 million for Signal and Power Solutions and $44 million for Advanced Safety and User Experience. [2] Includes charges recorded in 2018 related to costs associated with employee termination benefits and other exit costs of $90 million for Signal and Power Solutions and $19 million for Advanced Safety and User Experience. [3] Includes charges recorded in 2017 related...

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3 Months Ended  \

## Balance Sheets

In [61]:
master_data['APTV']['20']['balance']

,Consolidated Balance Sheets - USD ($) $ in Millions,"Dec. 31, 2019","Dec. 31, 2018"
0,Current assets:,NaN,NaN
1,Cash and cash equivalents,$ 412,$ 567
2,Restricted cash,16,1
3,"Accounts receivable, net",2569,2487
4,Inventories (Note 3),1286,1277
5,Other current assets (Note 4),504,445
6,"Disposal Group, Including Discontinued Operation, Assets, Current",532,0
7,Total current assets,5319,4777
8,Long-term assets:,NaN,NaN
9,"Property, net (Note 6)",3309,3179
10,"Operating Lease, Right-of-Use Asset",413,0
11,Investments in affiliates,106,99
12,"Intangible assets, net (Note 7)",1186,1380
13,Goodwill (Note 7),2407,2524
14,Other long-term assets (Note 4),719,521
15,Total long-term assets,8140,7703
16,Total assets,13459,12480
17,Current liabilities:,NaN,NaN
18,Short-term debt (Note 11),393,306
19,Accounts payable,2463,2334
20,Accrued liabilities (Note 8),1155,1054
21,"Disposal Group, Including Discontinued Operation, Liabilities, Current",43,0
22,Total current liabilities,4054,3694
23,Long-term liabilities:,NaN,NaN
24,Long-term debt (Note 11),3971,4038
25,Pension benefit obligations,483,445
26,"Operating Lease, Liability, Noncurrent",329,0
27,Other long-term liabilities (Note 8),611,633
28,Total long-term liabilities,5394,5116
29,Total liabilities,9448,8810
30,Commitments and contingencies (Note 13),NaN,NaN
31,Shareholders' equity:,NaN,NaN
32,"Preferred shares, $0.01 par value per share, 50,000,000 shares authorized, none issued and outstanding",0,0
33,"Ordinary shares, $0.01 par value per share, 1,200,000,000 shares authorized, 255,288,240 and 259,991,022 issued and outstanding as of December 31, 2019 and 2018, respectively",3,3
34,Additional paid-in capital,1645,1639
35,Retained earnings,2890,2511
36,Accumulated other comprehensive loss (Note 16),(719),(694)
37,Total Aptiv shareholders' equity,3819,3459
38,Noncontrolling interest,192,211
39,Total shareholders' equity,4011,3670
40,Total liabilities and shareholders' equity,"$ 13,459","$ 12,480"

In [62]:
master_data['BC']['20']['balance']

,Consolidated Balance Sheets - USD ($) $ in Millions,"Dec. 31, 2019","Dec. 31, 2018"
0,Current Assets,NaN,NaN
1,"Cash and Cash Equivalents, at Cost, Which Approximates Fair Value",$ 320.3,$ 294.4
2,Restricted Cash,11.6,9.0
3,Short-Term Investments in Marketable Securities,0.8,0.8
4,Total Cash and Short-Term Investments in Marketable Securities,332.7,304.2
5,"Accounts and Notes Receivable, Less Allowances of $11.3 and $9.2",331.8,351.8
6,Inventories,NaN,NaN
7,Finished Goods,554.3,490.8
8,Work-In-Process,101.3,94.1
9,Raw Materials,168.9,189.1
10,Net Inventories,824.5,774.0
11,Prepaid Expenses and Other,36.8,72.9
12,"Disposal Group, Including Discontinued Operation, Assets, Current",0.0,377.2
13,Current Assets,1525.8,1880.1
14,Property,NaN,NaN
15,Land,17.8,16.5
16,Buildings and Improvements,415.4,359.8
17,Equipment,1090.1,983.0
18,"Total Land, Buildings and Improvements and Equipment",1523.3,1359.3
19,Accumulated Depreciation,(863.8),(791.9)
20,"Net Land, Buildings and Improvements and Equipment",659.5,567.4
21,Unamortized Product Tooling Costs,136.9,127.1
22,Net Property,796.4,694.5
23,Other Assets,NaN,NaN
24,Goodwill,415.0,377.3
25,"Other Intangibles, Net",583.5,585.8
26,Equity Investments,29.5,32.6
27,Deferred Income Tax Asset,118.7,97.8
28,Operating lease assets,83.2,0.0
29,Other long-term assets,12.3,13.1
30,Long-term assets held for sale,0.0,610.3
31,Other Assets,1242.2,1716.9
32,Total Assets,3564.4,4291.5
33,Current Liabilities,NaN,NaN
34,Short-Term Debt and Current Maturities of Long-Term Debt,41.3,41.3
35,Accounts Payable,393.5,458.2
36,Accrued Expenses,509.6,502.1
37,Current Liabilities,944.4,1256.6
38,"Disposal Group, Including Discontinued Operation, Liabilities, Current",0.0,255.0
39,Long-Term Liabilities,NaN,NaN
40,Debt,1068.0,1179.5
41,Non-Current Operating Lease Liabilities,70.1,0.0
42,Postretirement Benefits,73.6,71.6
43,Other,107.4,101.6
44,Long-Term Liabilities Held for Sale,0.0,99.6
45,Long-Term Liabilities,1319.1,1452.3
46,Shareholders' Equity,NaN,NaN
47,"Common Stock; Authorized: 200,000,000 Shares, $0.75 Par Value; Issued: 102,538,000 Shares; Outstanding: 86,757,000 and 87,537,000 Shares",76.9,76.9
48,Additional Paid-In Capital,369.2,371.1
49,Retained Earnings,1931.3,2135.7
50,"Treasury Stock, at Cost: 15,781,000 and 15,001,000 Shares","(1,023.1)",(638.0)
51,"Accumulated Other Comprehensive Loss, Net of Tax:",NaN,NaN
52,Foreign Currency Translation,(37.6),(48.9)
53,Prior Service Credits,(3.0),(6.1)
54,Net Actuarial Losses,(7.3),(306.2)
55,Unrealized Losses on Derivatives,(5.5),(1.9)
56,"Total Accumulated Other Comprehensive Loss, Net of Tax",(53.4),(363.1)
57,Shareholders' Equity,1300.9,1582.6
58,Total Liabilities and Shareholders' Equity,"$ 3,564.4","$ 4,291.5"

In [63]:
master_data['PEN']['20']['balance']

,Consolidated Balance Sheets - USD ($) $ in Thousands,"Dec. 31, 2019","Dec. 31, 2018"
0,Current assets:,NaN,NaN
1,Cash and cash equivalents,"$ 72,779","$ 67,850"
2,Marketable investments,116610,133039
3,"Accounts receivable, net of doubtful accounts of $2,946 and $2,782 at December 31, 2019 and December 31, 2018, respectively",105901,81896
4,Inventories,152992,115741
5,Prepaid expenses and other current assets,14852,12200
6,Total current assets,463134,410726
7,"Property and equipment, net",51812,35407
8,Operating lease right-of-use assets,43717,NaN
9,Finance lease right-of-use assets,39924,NaN
10,"Intangible assets, net",25407,27245
11,Goodwill,7656,7813
12,Deferred taxes,31305,32940
13,Other non-current assets,2946,875
14,Total assets,665901,515006
15,Current liabilities:,NaN,NaN
16,Accounts payable,15111,8176
17,Accrued liabilities,67630,57886
18,Current operating lease liabilities,4142,NaN
19,Current finance lease liabilities,4165,NaN
20,Total current liabilities,91048,66062
21,Deferred rent,0,7586
22,Non-current operating lease liabilities,47242,NaN
23,Non-current finance lease liabilities,26748,NaN
24,Other non-current liabilities,15250,18943
25,Total liabilities,180288,92591
26,Commitments and contingencies (Note 10),NaN,NaN
27,Stockholders’ equity:,NaN,NaN
28,"Preferred stock, $.001 par value per share - 5,000,000 shares authorized, none issued and outstanding at December 31, 2019 and December 31, 2018",0,0
29,"Common stock, $.001 par value per share - 300,000,000 shares authorized, 35,001,581 issued and outstanding at December 31, 2019; 300,000,000 shares authorized, 34,437,339 issued and outstanding at December 31, 2018",35,34
30,Additional paid-in capital,430659,415084
31,Accumulated other comprehensive loss,"(2,324)","(1,942)"
32,Retained earnings,57522,9064
33,"Total Penumbra, Inc. stockholders’ equity",485892,422240
34,Non-controlling interest,(279),175
35,Total stockholders’ equity,485613,422415
36,Total liabilities and stockholders’ equity,"$ 665,901","$ 515,006"

## Cash Statements

In [64]:
master_data['PEN']['20']['cash']

                                                                  Consolidated Statements of Cash Flows - USD ($)  $ in Thousands  \
                                                                  Consolidated Statements of Cash Flows - USD ($)  $ in Thousands
0                                                                                              Statement of Cash Flows [Abstract]
1                                                                                                  Consolidated net income (loss)
2                                     Adjustments to reconcile net income to net cash provided by (used in) operating activities:
3                                                                                                   Depreciation and amortization
4                                                                                                        Stock-based compensation
5                                                                                       Loss on non-marketable equity investments
6                                                                                                 Provision for doubtful accounts
7                                                                                            Inventory write-offs and write-downs
8                                                                                                                  Deferred taxes
9                                                                                    Acquired in-process research and development
10                                                                               Change in fair value of contingent consideration
11                                                                                                                          Other
12                                                                                   Changes in operating assets and liabilities:
13                                                                                                            Accounts receivable
14                                                                                                                    Inventories
15                                                                      Prepaid expenses and other current and non-current assets
16                                                                                                               Accounts payable
17                                                                             Accrued expenses and other non-current liabilities
18                                                                                      Net cash provided by operating activities
19                                                                                          CASH FLOWS FROM INVESTING ACTIVITIES:
20                               Asset acquisition (Note 3 and Note 6) and acquisition of business (Note 5), net of cash acquired
21                                                                                    Contributions to non-marketable investments
22                                                                                      Lease payments made prior to commencement
23                                                                                            Purchases of marketable investments
24                                                                                  Proceeds from sales of marketable investments
25                                                                             Proceeds from maturities of marketable investments
26                                                                    Acquisition of intangible assets from a licensing agreement
27                                                                                            Purchases of property and equipment
28                                                                                                                          Other
29                                                                                          Net cash used in investing activities
30                                                                                          CASH FLOWS FROM FINANCING ACTIVITIES:
31                                 Proceeds from issuance of common stock upon underwritten public offering, net of issuance cost
32                                                                                       Proceeds from exercises of stock options
33                                                             Proceeds from issuance of stock under employee stock purchase plan
34                                                                           Payment of obligations on debt and credit facilities
35                                                        Payment of employee taxes related to vested common and restricted stock
36                                                                                          Payments of finance lease obligations
37                                                                                     Payment of acquisition-related obligations
38                                                               Proceeds from capital contribution from non-controlling interest
39                                                                            Net cash (used in) provided by financing activities
40                                                           Effect of foreign exchange rate changes on cash and cash equivalents
41                                                                                      NET INCREASE IN CASH AND CASH EQUIVALENTS
42                                                                                  CASH AND CASH EQUIVALENTS—Beginning of period
43                                                                                        CASH AND CASH EQUIVALENTS—End of period
44                                                                             SUPPLEMENTAL DISCLOSURES OF CASH FLOW INFORMATION:
45                                                                                                     Cash paid for income taxes
46                                                                                    NONCASH INVESTING AND FINANCING ACTIVITIES:
47                               Common shares issued as consideration in connection with a buyout agreement (Notes 7, 10 and 11)
48                                     Purchase of property and equipment funded through accounts payable and accrued liabilities
49  Asset acquisition (Note 3 and Note 6) and acquisition of business (Note 5) related contingent and working capital liabilities
50                      Indefinite-lived intangible assets related to licensed technology related contingent liabilities (Note 7)

   12 Months Ended
     Dec. 31, 2019 Dec. 31, 2018 Dec. 31, 2017
0              NaN           NaN           NaN
1         $ 47,004       $ 2,910       $ 4,657
2              NaN           NaN           NaN
3             8104          6168          3781
4            21485         18422         17812
5                0          3101          1430
6              656          1563           606
7             4411          1700          1037
8             1820       (6,480)       (4,288)
9                0         30835             0
10            (35)           950           109
11              49         (101)          1036
12             NaN           NaN           NaN
13        (25,029)      (25,762)       (9,118)
14        (41,407)      (22,288)      (18,826)
15         (4,001)          2231          2436
16            6038          1329          1851
17            7557         14230         10168
18           26652         28808         12691
19             NaN           NaN           NaN
20               0      (20,414)       (9,253)
21               0       (1,382)       (5,265)
22         (6,636)           NaN           NaN
23        (77,326)     (108,227)     (189,658)
24            4746         12129         28752
25           90614        127112        112803
26               0             0       (2,500)
27        (22,109)       (9,603)      (12,532)
28         (2,000)             0             0
29        (12,711)         (385)      (77,653)
30             NaN           NaN           NaN
31               0             0        106267
32            4120          5064          5048
33            8984          7231          5809
34               0         (404)       (1,079)
35        (18,535)      (17,725)      (11,686)
36         (2,570)           NaN           NaN
37         (1,758)       (4,481)             0
38             800           500             0
39         (8,959)       (9,815)        104359
40            (53)       (1,395)       (1,996)
41            4929         17213         37401
42           67850         50637         13236
43           72779         67850         50637
44             NaN           NaN           NaN
45             175           156           141
46             NaN           NaN           NaN
47               0          5256             0
48            2903          1037           977
49               0          4000          6067
50             $ 0           $ 0      $ 12,717

In [65]:
master_data['BC']['20']['cash']

                                                                  Consolidated Statements of Cash Flows - USD ($)  $ in Thousands  \
                                                                  Consolidated Statements of Cash Flows - USD ($)  $ in Thousands
0                                                                                              Statement of Cash Flows [Abstract]
1                                                                                                  Consolidated net income (loss)
2                                     Adjustments to reconcile net income to net cash provided by (used in) operating activities:
3                                                                                                   Depreciation and amortization
4                                                                                                        Stock-based compensation
5                                                                                       Loss on non-marketable equity investments
6                                                                                                 Provision for doubtful accounts
7                                                                                            Inventory write-offs and write-downs
8                                                                                                                  Deferred taxes
9                                                                                    Acquired in-process research and development
10                                                                               Change in fair value of contingent consideration
11                                                                                                                          Other
12                                                                                   Changes in operating assets and liabilities:
13                                                                                                            Accounts receivable
14                                                                                                                    Inventories
15                                                                      Prepaid expenses and other current and non-current assets
16                                                                                                               Accounts payable
17                                                                             Accrued expenses and other non-current liabilities
18                                                                                      Net cash provided by operating activities
19                                                                                          CASH FLOWS FROM INVESTING ACTIVITIES:
20                               Asset acquisition (Note 3 and Note 6) and acquisition of business (Note 5), net of cash acquired
21                                                                                    Contributions to non-marketable investments
22                                                                                      Lease payments made prior to commencement
23                                                                                            Purchases of marketable investments
24                                                                                  Proceeds from sales of marketable investments
25                                                                             Proceeds from maturities of marketable investments
26                                                                    Acquisition of intangible assets from a licensing agreement
27                                                                                            Purchases of property and equipment
28                                                                                                                          Other
29                                                                                          Net cash used in investing activities
30                                                                                          CASH FLOWS FROM FINANCING ACTIVITIES:
31                                 Proceeds from issuance of common stock upon underwritten public offering, net of issuance cost
32                                                                                       Proceeds from exercises of stock options
33                                                             Proceeds from issuance of stock under employee stock purchase plan
34                                                                           Payment of obligations on debt and credit facilities
35                                                        Payment of employee taxes related to vested common and restricted stock
36                                                                                          Payments of finance lease obligations
37                                                                                     Payment of acquisition-related obligations
38                                                               Proceeds from capital contribution from non-controlling interest
39                                                                            Net cash (used in) provided by financing activities
40                                                           Effect of foreign exchange rate changes on cash and cash equivalents
41                                                                                      NET INCREASE IN CASH AND CASH EQUIVALENTS
42                                                                                  CASH AND CASH EQUIVALENTS—Beginning of period
43                                                                                        CASH AND CASH EQUIVALENTS—End of period
44                                                                             SUPPLEMENTAL DISCLOSURES OF CASH FLOW INFORMATION:
45                                                                                                     Cash paid for income taxes
46                                                                                    NONCASH INVESTING AND FINANCING ACTIVITIES:
47                               Common shares issued as consideration in connection with a buyout agreement (Notes 7, 10 and 11)
48                                     Purchase of property and equipment funded through accounts payable and accrued liabilities
49  Asset acquisition (Note 3 and Note 6) and acquisition of business (Note 5) related contingent and working capital liabilities
50                      Indefinite-lived intangible assets related to licensed technology related contingent liabilities (Note 7)

   12 Months Ended
     Dec. 31, 2019 Dec. 31, 2018 Dec. 31, 2017
0              NaN           NaN           NaN
1         $ 47,004       $ 2,910       $ 4,657
2              NaN           NaN           NaN
3             8104          6168          3781
4            21485         18422         17812
5                0          3101          1430
6              656          1563           606
7             4411          1700          1037
8             1820       (6,480)       (4,288)
9                0         30835             0
10            (35)           950           109
11              49         (101)          1036
12             NaN           NaN           NaN
13        (25,029)      (25,762)       (9,118)
14        (41,407)      (22,288)      (18,826)
15         (4,001)          2231          2436
16            6038          1329          1851
17            7557         14230         10168
18           26652         28808         12691
19             NaN           NaN           NaN
20               0      (20,414)       (9,253)
21               0       (1,382)       (5,265)
22         (6,636)           NaN           NaN
23        (77,326)     (108,227)     (189,658)
24            4746         12129         28752
25           90614        127112        112803
26               0             0       (2,500)
27        (22,109)       (9,603)      (12,532)
28         (2,000)             0             0
29        (12,711)         (385)      (77,653)
30             NaN           NaN           NaN
31               0             0        106267
32            4120          5064          5048
33            8984          7231          5809
34               0         (404)       (1,079)
35        (18,535)      (17,725)      (11,686)
36         (2,570)           NaN           NaN
37         (1,758)       (4,481)             0
38             800           500             0
39         (8,959)       (9,815)        104359
40            (53)       (1,395)       (1,996)
41            4929         17213         37401
42           67850         50637         13236
43           72779         67850         50637
44             NaN           NaN           NaN
45             175           156           141
46             NaN           NaN           NaN
47               0          5256             0
48            2903          1037           977
49               0          4000          6067
50             $ 0           $ 0      $ 12,717

In [66]:
master_data['APTV']['20']['cash']

                                                                                   Consolidated Statements Of Cash Flows  $ in Millions  \
                                                                                   Consolidated Statements Of Cash Flows  $ in Millions
0                                                                                                 Cash flows from operating activities:
1                                                                                                                            Net income
2                                                                                       Income from discontinued operations, net of tax
3                                                                                                     Income from continuing operations
4                                                     Adjustments to reconcile net income to net cash provided by operating activities:
5                                                                                                                          Depreciation
6                                                                                                                          Amortization
7                                                                                          Amortization of deferred debt issuance costs
8                                                                                               Restructuring expense, net of cash paid
9                                                                                                                 Deferred income taxes
10                                                                                    Pension and other postretirement benefit expenses
11                                                                     Income from equity method investments, net of dividends received
12                                                                                                       Loss on extinguishment of debt
13                                                                                                        (Gain) loss on sale of assets
14                                                                                                             Share-based compensation
15                                                                                         Changes in operating assets and liabilities:
16                                                                                                             Accounts receivable, net
17                                                                                                                          Inventories
18                                                                                                                         Other assets
19                                                                                                                     Accounts payable
20                                                                                              Accrued and other long-term liabilities
21                                                                                                                           Other, net
22                                                                                                                Pension contributions
23                                                                 Net cash provided by operating activities from continuing operations
24                                                               Net cash provided by operating activities from discontinued operations
25                                                                                            Net cash provided by operating activities
26                                                                                                Cash flows from investing activities:
27                                                                                                                 Capital expenditures
28                                                                                         Proceeds from sale of property / investments
29                                                                                  Cost of business acquisitions, net of cash acquired
30                                                                                                       Cost of technology investments
31                                                                                                            Settlement of derivatives
32                                                                     Net cash used in investing activities from continuing operations
33                                                                   Net cash used in investing activities from discontinued operations
34                                                                                                Net cash used in investing activities
35                                                                                                Cash flows from financing activities:
36                                                                                Net repayments under other short-term debt agreements
37                                                                                                            Repayment of senior notes
38                                                                        Proceeds from issuance of senior notes, net of issuance costs
39                                                            Contingent consideration and deferred acquisition purchase price payments
40                                                                Dividend payments of consolidated affiliates to minority shareholders
41                                                                                                        Repurchase of ordinary shares
42                                                                                                       Distribution of cash dividends
43                                                                               Dividend received from spin-off of Delphi Technologies
44                                                                          Cash transferred to Delphi Technologies related to spin-off
45                                                                        Cash transferred from Delphi Technologies related to spin-off
46                                                                        Taxes withheld and paid on employees' restricted share awards
47                                                                                                Net cash used in financing activities
48                                                   Effect of exchange rate fluctuations on cash, cash equivalents and restricted cash
49  Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect
50        Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations

         12 Months Ended
   Dec. 31, 2019 USD ($) Dec. 31, 2018 USD ($) Dec. 31, 2017 USD ($)
0                    NaN                   NaN                   NaN
1                $ 1,009               $ 1,107               $ 1,428
2                      0                     0                   365
3                   1009                  1107                  1063
4                    NaN                   NaN                   NaN
5                    571                   522                   429
6                    146                   154                   117
7                      6                     7                     7
8                     29                  (26)                     2
9                   (33)                  (14)                  (26)
10                    44                    35                    51
11                   (6)                  (11)                  (18)
12                     6                     0                     0
13                   (1)                   (2)                   (3)
14                    66                    58                    62
15                   NaN                   NaN                   NaN
16                  (74)                    55                 (287)
17                     8                 (120)                 (224)
18                 (202)                 (165)                 (187)
19                   133                    62                   268
20                   (9)                    73                  (72)
21                  (31)                  (47)                  (36)
22                  (38)                  (48)                  (40)
23                  1624                  1640                  1106
24                     0                  (12)                   362
25                  1624                  1628                  1468
26                   NaN                   NaN                   NaN
27                 (781)                 (846)                 (698)
28                    14                    13                     7
29                 (334)               (1,197)                 (324)
30                  (10)                  (16)                  (50)
31                     0                   (2)                  (28)
32               (1,111)               (2,048)               (1,093)
33                     0                     0                 (159)
34               (1,111)               (2,048)               (1,252)
35                   NaN                   NaN                   NaN
36                    80                   268                  (15)
37                 (654)                     0                     0
38                   641                     0                   796
39                     0                  (13)                  (24)
40                  (11)                  (30)                  (38)
41                 (420)                 (499)                 (383)
42                 (226)                 (233)                 (310)
43                     0                     0                  1148
44                     0                     0                 (863)
45                     0                     0                   180
46                  (34)                  (35)                  (33)
47                 (649)                 (555)                   456
48                   (3)                  (54)                    86
49                 (139)               (1,029)                   758
50                 $ 429                 $ 568               $ 1,597