In [1]:
import numpy as np
import pandas as pd
import time
import os
import pickle
import re

In [2]:
pd.set_option('display.max_rows', 700)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 100)
pd.options.display.float_format = '{:.2f}'.format

In [3]:
DATA_ROOT_PATH="/mnt/data/projects/MD1/data/R1000/reports/"
PROJ_ROOT_PATH="/home/priyesh/projects/MD1"

In [4]:
# Read from Pickle file

filepath = os.path.join(PROJ_ROOT_PATH,'pickle','clean_master_data_interim.pkl')
clean_master_data = pd.read_pickle(filepath)

In [5]:
def get_line_items(t):
 
  headings = []
  line_items = []
    
  for index, row in t.iterrows():
    
    if row.replace('', np.nan).isna().all():
      # Blank row, so assume heading
    
      headings.append(index)
    else:    
      line_items.append(index)

  return headings, line_items

In [6]:
def get_table_labels(stype):

  master_headings = []
  master_line_items = []

  ticker_list = list(clean_master_data.keys())

  for ticker in ticker_list:
    
    print(ticker)
    
    for yr in clean_master_data[ticker]:
      
      # Allow for the likelihood that statement might be missing for given ticker and yr
        
      if stype in clean_master_data[ticker][yr]:
        try:
          headings, line_items = get_line_items(clean_master_data[ticker][yr][stype]['table'])
    
          master_headings = master_headings + headings
          master_line_items = master_line_items + line_items
        except:
          print("Error : {} {}".format(ticker, yr))
          exit() 

  # Remove duplicates from headings and line items

  unique_list = set(master_headings)
  headings = list(unique_list)

  unique_list = set(master_line_items)
  line_items = list(unique_list)

  return {'headings' : headings,
          'line_items' : line_items}

In [7]:
table_labels = get_table_labels('balance')

AA
AAL
AAP
AAPL
ABBV
ABNB
ABT
ACGL
ACHC
ACI
ACM
ACN
ADBE
ADI
ADM
ADP
ADSK
ADT
AEE
AEP
AES
AFG
AFL
AFRM
AGCO
AGL
AGNC
AGO
AGR
AIG
AIZ
AJG
AKAM
AL
ALB
ALGM
ALGN
ALK
ALL
ALLE
ALLY
ALNY
ALSN
AM
AMAT
AMC
AMCR
AMD
AME
AMED
AMG
AMGN
AMP
AMZN
AN
ANET
ANSS
AON
AOS
APA
APD
APH
APO
APP
APTV
AR
ARES
ARMK
ARW
ASH
ATO
ATR
ATUS
ATVI
AVGO
AVT
AVTR
AWI
AWK
AXON
AXS
AXTA
AYI
AYX
AZEK
AZO
AZTA
BA
BAC
BAH
BALL
BAX
BBWI
BBY
BC
BDX
BEN
BERY
BFAM
BG
BHF
BIIB
BILL
BIO
BJ
BK
BKNG
BLD
BLDR
BLK
BMRN
BMY
BOKF
BR
BRKR
BRO
BSX
BSY
BURL
BWA
BWXT
BX
BYD
C
CABO
CACC
CAH
CAR
CARR
CAT
CB
CBOE
CBSH
CC
CCCS
CCK
CCL
CDAY
CDNS
CDW
CE
CEG
CERT
CF
CFG
CFLT
CFR
CG
CGNX
CHD
CHDN
CHE
CHH
CHPT
CHRW
CHTR
CIEN
CINF
CL
CLH
CLVT
CLX
CMA
CMCSA
CME
CMG
CMI
CMS
CNA
CNM
CNP
CNXC
COF
COIN
COLB
COLM
COO
COST
COTY
CPB
CPRI
CPRT
CR
CRI
CRL
CRUS
CRWD
CSCO
CSL
CTLT
CTRA
CTSH
CTVA
CVNA
CVX
CW
CZR
D
DAL
DAR
DASH
DBX
DCI
DD
DDOG
DECK
DFS
DG
DGX
DHI
DHR
DINO
DIS
DISH
DKNG
DKS
DLB
DLTR
DNA
DOCS
DOCU
DOV
DOW
DPZ
DRVN
DT
DTE
DTM
DUK
DV
DVA
DVN
DXC
DXCM
EA
EBAY
ECL
ED
EEFT
EFX
EHAB
EHC
EIX
EL
ELAN
EMN
EMR
ENOV
ENPH
ENTG
EOG
EPAM
EQH
EQT
ERIE
ES
ESAB
ESI
ESTC
ETN
ETR
ETSY
EVA
EVR
EVRG
EW
EWBC
EXAS
EXC
EXEL
EXP
EXPD
EXPE
F
FAF
FANG
FAST
FCN
FCNCA
FCX
FDS
FE
FFIV
FG
FHB
FHN
FICO
FIS
FISV
FITB
FIVE
FIVN
FLO
FLS
FLT
FMC
FNB
FND
FNF
FOUR
FOX
FRPT
FSLR
FTNT
FTV
G
GD
GDDY
GE
GGG
GILD
GL
GLW
GM
GME
GMED
GNRC
GNTX
GO
GOOG
GOOGL
GPC
GPK
GPN
GPS
GRMN
GS
GTES
GWRE
GWW
GXO
H
HAL
HAS
HAYW
HBAN
HBI
HCA
HD
HE
HEI
HES
HIG
HII
HLT
HOG
HOLX
HON
HPE
HPP
HPQ
HRL
HSIC
HSY
HTZ
HUBB
HUBS
HUN
HWM
HXL
HZNP
IAC
IART
IBKR
IBM
ICE
ICUI
IDA
IDXX
IEX
IFF
ILMN
INCY
INFA
INGR
INTC
INTU
IONS
IP
IPG
IPGP
IQV
IR
ISRG
IT
ITT
ITW
IVZ
J
JAMF
JAZZ
JBHT
JBL
JBLU
JCI
JEF
JHG
JKHY
JNJ
JNPR
JPM
JWN
K
KBR
KDP
KEX
KEY
KEYS
KHC
KKR
KLAC
KMB
KMI
KMPR
KMX
KNX
KO
KR
KSS
L
LAD
LAZ
LBRDA
LCID
LDOS
LEA
LECO
LEG
LEN
LESL
LFUS
LH
LHX
LII
LITE
LKQ
LLY
LMT
LNC
LNG
LNT
LOPE
LOW
LPLA
LPX
LRCX
LSCC
LSTR
LULU
LUMN
LUV
LVS
LYB
LYFT
LYV
M
MA
MAN
MANH
MAR
MAS
MASI
MAT
MCD
MCHP
MCK
MCO
MCW
MDB
MDLZ
MDT
MDU
MET
META
MGM
MHK
MIDD
MKC
MKL
MKSI
MKTX
MLM
MMC
MMM
MNST
MO
MORN
MOS
MP
MPC
MPWR
MRCY
MRK
MRNA
MRO
MRTX
MRVI
MRVL
MS
MSA
MSCI
MSFT
MSGS
MSI
MSM
MTB
MTCH
MTD
MTG
MTN
MTZ
MU
NATI
NBIX
NCLH
NCNO
NCR
NDAQ
NDSN
NEE
NEM
NET
NEU
NEWR
NFE
NFG
NFLX
NI
NLY
NOC
NOV
NOW
NRG
NSC
NTAP
NTNX
NTRA
NTRS
NUE
NVAX
NVCR
NVDA
NVR
NVST
NVT
NWL
NWS
NXST
NYCB
NYT
OC
ODFL
OGE
OGN
OKE
OKTA
OLED
OLLI
OLN
OLPX
OMC
OMF
ON
ORI
ORLY
OSH
OTIS
OVV
OWL
OXY
PACW
PAG
PANW
PARA
PATH
PAYC
PB
PCAR
PCG
PCOR
PCTY
PDCE
PEG
PEGA
PEN
PENN
PEP
PFE
PFG
PFGC
PG
PGR
PH
PHM
PII
PINC
PINS
PKG
PKI
PLNT
PLTK
PLTR
PLUG
PM
PNC
PNFP
PNR
PNW
PODD
POOL
POST
PPC
PPG
PPL
PRGO
PRI
PRU
PSTG
PSX
PTC
PTON
PVH
PWR
PXD
PYPL
QCOM
QDEL
QRVO
QS
RARE
RE
REGN
REYN
RF
RGA
RGEN
RH
RJF
RL
RMD
RNG
RNR
RRC
RRX
RS
RSG
RTX
RUN
S
SAM
SBUX
SCCO
SCHW
SCI
SEB
SEE
SEIC
SF
SGEN
SHC
SHW
SIRI
SITE
SIX
SJM
SKX
SLB
SLGN
SMAR
SMG
SNA
SNDR
SNOW
SNPS
SNV
SNX
SO
SOFI
SON
SPB
SPLK
SPR
SQ
SRCL
SRE
SSNC
SSRM
ST
STE
STLD
STT
STWD
STZ
SWK
SWKS
SWN
SYF
SYK
SYNH
SYY
T
TAP
TDC
TDG
TDOC
TDY
TECH
TER
TFC
TFSL
TFX
TGT
THC
THG
THO
TJX
TKR
TMO
TMUS
TNDM
TNL
TOL
TOST
TPL
TPR
TPX
TREX
TRGP
TRIP
TRMB
TROW
TRU
TRV
TSCO
TSLA
TSN
TT
TTC
TTD
TTEK
TTWO
TW
TWKS
TWLO
TXG
TXN
TXT
TYL
U
UAL
UBER
UGI
UHS
UI
ULTA
UNM
UNP
UNVR
UPS
UPST
URI
USB
USFD
UTHR
UWMC
V
VAC
VEEV
VFC
VIRT
VLO
VMC
VMI
VMW
VNT
VOYA
VRSK
VRSN
VRT
VRTX
VSAT
VSCO
VST
VTRS
VVV
VZ
W
WAB
WAL
WAT
WBA
WBD
WBS
WCC
WDAY
WDC
WEC
WEN
WEX
WFC
WH
WHR
WLK
WM
WMB
WMS
WMT
WOLF
WOOF
WRB
WRK
WSC
WSM
WSO
WST
WTFC
WTM
WTRG
WTW
WU
WWD
WWE
WYNN
X
XEL
XOM
XPO
XRAY
XYL
YETI
YUM
Z
ZBRA

In [9]:
all_table_labels = table_labels['headings'] + table_labels['line_items']
df = pd.DataFrame(all_table_labels,columns=['line_item'])

### Company Shareholders Equity

In [10]:
mask = df['line_item'].str.contains(r" Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Abstract",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Non",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                                                       line_item
2133                             3M Company Shareholders Equity:
2004                                    Aig Shareholders Equity:
51                              Air Products Shareholders Equity
869                   Albemarle Corporation Shareholders Equity:
1545                      Alcoa Corporation Shareholders Equity:
172                                   Alcoa Shareholders Equity:
1139                              Amcor Plc Shareholders Equity:
16085                                    Apa Shareholders Equity
575                                 Arconic Shareholders Equity:
27434                                Bancorp Shareholders Equity
430                       Best Buy Co., Inc. Shareholders Equity
2384                            Bio-Technes Shareholders Equity:
1437                        Biogen Idec Inc. Shareholders Equity
1060                             Biogen Inc. Shareholders Equity
2211           Bristol-Myers Squibb Company Shareholders Equity:
2104                   Campbell Soup Company Shareholders Equity
2340                                  Cisco Shareholders Equity:
1613           Commitments And Contingencies Shareholders Equity
15144                                Company Shareholders Equity
16022                         Crown Holdings Shareholders Equity
19300                Crown Holdings Shareholders Equity/-Deficit
1250                            Cummins Inc. Shareholders Equity
609                    Eli Lilly And Company Shareholders Equity
455                        Encompass Health Shareholders Equity:
1684                                Equifax Shareholders Equity:
1348                           Evergy, Inc. Shareholders Equity:
13312                                    Fhn Shareholders Equity
1422     First Horizon National Corporation Shareholders Equity:
512                            Fiserv, Inc. Shareholders Equity:
28883                        Genpact Limited Shareholders Equity
1323                    Healthsouth Shareholders Equity Deficit:
830                             Healthsouth Shareholders Equity:
2229                  Howmet Aerospace Inc. Shareholders Equity:
1574                       Howmet Aerospace Shareholders Equity:
714                     Hubbell Incorporated Shareholders Equity
6028                                 Hubbell Shareholders Equity
2349                                 Hubbell Shareholders Equity
1940                              Indemnitys Shareholders Equity
1503        Intercontinental Exchange, Inc. Shareholders Equity:
1500   Intercontinentalexchange Group, Inc. Shareholders Equity:
2136                                    Kbr Shareholders Equity:
4384                                     Key Shareholders Equity
15184                       Littelfuse, Inc. Shareholders Equity
214                                 Marriott Shareholders Equity
171                       Masco Corporations Shareholders Equity
2367                     Masco Corporations Shareholders Equity:
2292                                  Micron Shareholders Equity
878                                  Micron Shareholders Equity:
381          Mine Safety Appliances Company Shareholders Equity:
369                          Morgan Stanley Shareholders Equity:
2344                      Morningstar, Inc. Shareholders Equity:
15                           Msc Industrial Shareholders Equity:
14725            Net Duke Energy Corporation Shareholders Equity
31838                 Onemain Holdings, Inc. Shareholders Equity
871                                   Oneok Shareholders Equity:
1158              Regal Rexnord Corporation Shareholders Equity:
1218                Sei Investments Company Shareholders Equity:
1411                        Sei Investments Shareholders Equity:
1362                                  Sonoco Shareholders Equity
11540              Springleaf Holdings, Inc. Shareholders Equity
7207                             Ssr Minings Shareholders Equity
963           Thermo Fisher Scientific Inc. Shareholders Equity:
1906                                   Tyco Shareholders Equity:
1273                            Viatris Inc. Shareholders Equity
1435                           Watsco, Inc. Shareholders Equity:

In [11]:
mask = df['line_item'].str.contains(r" Stockholder[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Temp|Abstract|Before",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Non|Sub",case=True, regex=True, na=False)
df[mask]

                                                                                    line_item
28                                                             Paramount Stockholders Equity:
30                                                    Synnex Corporation Stockholders Equity:
128                                                      Aptargroup, Inc. Stockholders Equity
155                                                          Hf Sinclair Stockholders Equity:
196                                                         Evercore Inc. Stockholders Equity
210                                                  Mckesson Corporation Stockholders Equity
233                                                     Hess Corporation Stockholders Equity:
247                                            Commerce Bancshares, Inc. Stockholders Equity:
251                                                     Agco Corporation Stockholders Equity:
263                                                          Wells Fargo Stockholders Equity:
366                                                                    Hp Stockholders Equity
390                                                              Bio-Rad Stockholders Equity:
417                                                            Hp Stockholders Deficit Equity
436                                                                  Fcx Stockholders Equity:
527                                                                  Dxc Stockholders Equity:
544                                                                  Fis Stockholders Equity:
561                                                            Viacomcbs Stockholders Equity:
659                                                  Virtu Financial Inc. Stockholders Equity
669                                                       Metlife, Inc.S Stockholders Equity:
696                                                 Harbinger Group Inc. Stockholders Equity:
716                                                   The Aes Corporation Stockholders Equity
723                                                   Masimo Corporation Stockholders Equity:
743                                      Intercontinental Exchange, Inc. Stockholders Equity:
761                                                                  Hpe Stockholders Equity:
768                                                Targa Resources Corp. Stockholders Equity:
784                                         Warner Bros. Discovery, Inc. Stockholders Equity:
808                                                            Ingredion Stockholders Equity:
831                                                Evercore Partners Inc. Stockholders Equity
847                                         On Semiconductor Corporation Stockholders Equity:
896                                                  Jabil Circuit, Inc. Stockholders Equity:
900                                         Brighthouse Financial, Inc.S Stockholders Equity:
917                                                                Aecom Stockholders Equity:
1027                                       Starwood Property Trust, Inc. Stockholders Equity:
1033                                                               Kirby Stockholders Equity:
1062                                                   Quest Diagnostics Stockholders Equity:
1089                                                                 Mpc Stockholders Equity:
1105                                                               Cisco Stockholders Equity:
1141                                         Deckers Outdoor Corporation Stockholders Equity:
1175                                           Ipg Photonics Corporation Stockholders Equity:
1182                                                Partners Capital And Stockholders Equity:
1200                                   The Madison Square Garden Company Stockholders Equity:
1212                                           Valero Energy Corporation Stockholders Equity:
1259                                                     Hess Corporation Stockholders Equity
1372                                             Euronet Worldwide, Inc. Stockholders Equity:
1386                                                        Aqua America Stockholders Equity:
1396                                                            Ingredion Stockholders Equity
1401                                             Penske Automotive Group Stockholders Equity:
1561                                                       Enhabit, Inc. Stockholders Equity:
1721                                                                 Ibm Stockholders Equity:
1739                                  Madison Square Garden Sports Corp. Stockholders Equity:
1788                                                 Essential Utilities Stockholders Equity:
1795                                                    Juniper Networks Stockholders Equity:
1843                                                                  Ibm Stockholders Equity
1853                                                              Nasdaq Stockholders Equity:
1872                                                         Viasat, Inc. Stockholders Equity
1933                                         Molson Coors Brewing Company Stockholders Equity
1935                                                                Nucor Stockholders Equity
1941                                                  The Hershey Company Stockholders Equity
1950                                                     Ugi Corporation Stockholders Equity:
1961   Huntsman Corporation Stockholders Equity Or Huntsman International Llc Members Equity:
2016                                                          Nasdaq Omx Stockholders Equity:
2150                                     Hudson Pacific Properties, Inc. Stockholders Equity:
2166                                        Molson Coors Beverage Company Stockholders Equity
2200                                                                 Cbi Stockholders Equity:
2215                                                                  Cpi Stockholders Equity
2257                                                          Jabil Inc. Stockholders Equity:
2259                                                 Unity Software Inc. Stockholders Equity:
2263                                              Waste Management, Inc. Stockholders Equity:
2265                                                 Harbinger Group Inc. Stockholders Equity
2274                                                            Qualcomm Stockholders Equity:
2330                                         Mckesson Corporation Stockholders Equity Deficit
2376                                                        Owens Corning Stockholders Equity
2422                                                    Merck & Co., Inc. Stockholders Equity
4440                                                     Lear Corporation Stockholders Equity
8052                                                            Dow Inc.S Stockholders Equity
8527                                                 Microchip Technology Stockholders Equity
10716                                      Equity Attributable To Gamestop Corp. Stockholders
13059                                             Mastercard Incorporated Stockholders Equity
13252                                Equity Attributable To Iqvia Holdings Inc.S Stockholders
15084                                                          Dowduponts Stockholders Equity
19092                                                          Tetra Tech Stockholders Equity
21950               Equity Deficit Attributable To Quintiles Ims Holdings, Inc.S Stockholders
27116                                                             Newmont Stockholders Equity
27146                                                        Schlumberger Stockholders Equity
28744                                                             Caesars Stockholders Equity
29208                                                                 Slb Stockholders Equity
29922                                                 The Hershey Company Stockholders Equity

In [12]:
mask = df['line_item'].str.contains(r" Shareowner[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Abs|Attrib",case=False, regex=True, na=False)
df[mask]

                                            line_item
136          The Coca-Cola Company Shareowners Equity
1102  Stanley Black & Decker, Inc. Shareowners Equity
2068         Campbell Soup Company Shareowners Equity
5099  Stanley Black & Decker, Inc. Shareowners Equity

### Common Shareholders Equity

In [13]:
mask = df['line_item'].str.contains(r" Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Abstract|Attrib",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Non",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                                                                                                 line_item
100                                                                             Common Shareholders Equity
8069                                                                            Common Shareholders Equity
20471                               Common Shareholders Equity See Statement Of Common Shareholders Equity
27127                                      Common Shareholders Equity See Statement Of Shareholders Equity
2374                                                                           Common Shareholders Equity:
25542  Masco Corporations Shareholders Equity Common Shares Authorized: 1,400,000,000; Issued And Outst...
9660   Masco Corporations Shareholders Equity Common Shares Authorized: 1,400,000,000; Issued And Outst...
306                                                                     Pepsico Common Shareholders Equity
1459                                                            White Mountains Common Shareholders Equity
819                                                            White Mountainss Common Shareholders Equity

In [14]:
mask = df['line_item'].str.contains(r" Stockholder[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Temp|Abstract|Before",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Non|Sub",case=True, regex=True, na=False)
df[mask]

                                                        line_item
685                                   Common Stockholders Equity:
1946                                   Common Stockholders Equity
22531                                  Common Stockholders Equity
31955  Universal Health Services, Inc. Common Stockholders Equity

### Shareholders Equity

In [15]:
mask = df['line_item'].str.contains(r"^Shareowner|^Stockholder|^Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity$",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"NonCon",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Total|Liabilit|Abs|Attrib",case=False, regex=True, na=False)
df[mask]

                                line_item
350         Stockholders / Members Equity
446                   Shareholders Equity
764          Stockholders / Member Equity
806           Stockholders Deficit Equity
851    Stockholders Equity/Members Equity
856                    Stockholdersequity
1255                   Shareowners Equity
2025                  Stockholders Equity
13313                 Stockholders Equity
23322                 Shareholders Equity
29081         Stockholders Deficit Equity

### Total Company Shareholders Equity

In [16]:
mask = df['line_item'].str.contains(r"Total.*Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Abstract",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Non",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                                                                       line_item
25366                                       Total 3M Company Shareholders Equity
11969                                    Total Accenture Plc Shareholders Equity
26209                                              Total Aig Shareholders Equity
4065                                      Total Air Products Shareholders Equity
21941                            Total Albemarle Corporation Shareholders Equity
5177                                 Total Alcoa Corporation Shareholders Equity
18942                                            Total Alcoa Shareholders Equity
27861                                     Total Allegion Plc Shareholders Equity
22768                                         Total Allstate Shareholders Equity
5959                                         Total Amcor Plc Shareholders Equity
14724                       Total Ameriprise Financial, Inc. Shareholders Equity
21946                                              Total Aon Shareholders Equity
10874                                      Total Aon Shareholders Equity Deficit
18993                                            Total Aptiv Shareholders Equity
16933                                          Total Arconic Shareholders Equity
17975                                           Total Axalta Shareholders Equity
4698                                  Total Ball Corporation Shareholders Equity
27419                                          Total Bancorp Shareholders Equity
24125                  Total Bath & Body Works, Inc. Shareholders Equity Deficit
30590                 Total Baxter International Inc. Baxter Shareholders Equity
15364                                           Total Baxter Shareholders Equity
7288                                Total Best Buy Co., Inc. Shareholders Equity
9165                                        Total Bio-Techne Shareholders Equity
7463                                       Total Bio-Technes Shareholders Equity
27164                                 Total Biogen Idec Inc. Shareholders Equity
12942                                      Total Biogen Inc. Shareholders Equity
6522                      Total Bristol-Myers Squibb Company Shareholders Equity
19855                                            Total Bunge Shareholders Equity
16644                            Total Campbell Soup Company Shareholders Equity
24777                            Total Cardinal Health, Inc. Shareholders Equity
29665                   Total Cardinal Health, Inc. Shareholders Equity/-Deficit
26964                                         Total Catalent Shareholders Equity
3227                                 Total Catalent Shareholders Equity/-Deficit
18517                             Total Celanese Corporation Shareholders Equity
26476                                          Total Charter Shareholders Equity
17390                                  Total Charter Shareholders Equity Deficit
6615                      Total Churchill Downs Incorporated Shareholders Equity
28376                                            Total Cisco Shareholders Equity
16716                                        Total Cme Group Shareholders Equity
4940                         Total Colgate-Palmolive Company Shareholders Equity
24161                      Total Columbia Sportswear Company Shareholders Equity
21467                              Total Comcast Corporation Shareholders Equity
11063                                 Total Company Share Of Shareholders Equity
28940                                    Total Comprehensive Shareholders Equity
9094                              Total Corning Incorporated Shareholders Equity
20067                                     Total Cummins Inc. Shareholders Equity
30710                  Total Davita Healthcare Partners Inc. Shareholders Equity
12155                                      Total Davita Inc. Shareholders Equity
29042                                           Total Delphi Shareholders Equity
6517                                            Total Disney Shareholders Equity
8619                                             Total Eaton Shareholders Equity
25119                                           Total Ecolab Shareholders Equity
27906                            Total Edison Internationals Shareholders Equity
20530                            Total Eli Lilly And Company Shareholders Equity
15631                                 Total Encompass Health Shareholders Equity
31449                                   Total Entegris, Inc. Shareholders Equity
4873                                           Total Equifax Shareholders Equity
11840                                     Total Evergy, Inc. Shareholders Equity
25956                Total Fidelity National Financial, Inc. Shareholders Equity
28242               Total First Horizon National Corporation Shareholders Equity
16573                                     Total Fiserv, Inc. Shareholders Equity
26550                            Total Flowserve Corporation Shareholders Equity
8467                                                Total Ge Shareholders Equity
22474                                  Total Global Payments Shareholders Equity
30759                Total Graphic Packaging Holding Company Shareholders Equity
17312                            Total Harley-Davidson, Inc. Shareholders Equity
27503                                      Total Healthsouth Shareholders Equity
27639                              Total Healthsouth Shareholders Equity Deficit
26208                                            Total Heico Shareholders Equity
30825                            Total Howmet Aerospace Inc. Shareholders Equity
16567                                 Total Howmet Aerospace Shareholders Equity
16975                                  Total Hrg Group, Inc. Shareholders Equity
19665                             Total Hubbell Incorporated Shareholders Equity
12337                                          Total Hubbell Shareholders Equity
19646                        Total Huntington Bancshares Inc Shareholders Equity
9045                                               Total Iac Shareholders Equity
11334                                    Total Idacorp, Inc. Shareholders Equity
5784                                         Total Indemnity Shareholders Equity
2027                                         Total Indemnity Shareholders Equity
26345                                   Total Ing U.S., Inc. Shareholders Equity
5285                                Total Ingersoll-Rand Plc Shareholders Equity
9772                   Total Intercontinental Exchange, Inc. Shareholders Equity
29568             Total Intercontinentalexchange Group, Inc. Shareholders Equity
6865                               Total International Paper Shareholders Equity
15056                                  Total Itt Corporation Shareholders Equity
17363                                         Total Itt Inc. Shareholders Equity
20764                         Total Jazz Pharmaceuticals Plc Shareholders Equity
21009                   Total Jefferies Financial Group Inc. Shareholders Equity
18646                                              Total Kbr Shareholders Equity
14928                                      Total Kraft Foods Shareholders Equity
17573             Total Landstar System, Inc. And Subsidiary Shareholders Equity
24241                    Total Leucadia National Corporation Shareholders Equity
20128                                      Total Macys, Inc. Shareholders Equity
17643                                    Total Manpowergroup Shareholders Equity
22395                       Total Masco Corporations Shareholders Deficit Equity
23955                               Total Masco Corporations Shareholders Equity
21655                       Total Masco Corporations Shareholders Equity Deficit
18592                                           Total Mastec Shareholders Equity
25545                                     Total Mastec, Inc. Shareholders Equity
26396                                Total Match Group, Inc. Shareholders Equity
4979                                            Total Micron Shareholders Equity
6473                    Total Mine Safety Appliances Company Shareholders Equity
25856                           Total Mondelez International Shareholders Equity
12783                           Total Mondelēz International Shareholders Equity
16632                                           Total Moodys Shareholders Equity
17497                                   Total Moodys Shareholders Equity Deficit
28154                                   Total Morgan Stanley Shareholders Equity
4684                           Total Msa Safety Incorporated Shareholders Equity
5676                                    Total Msc Industrial Shareholders Equity
23413                                              Total Mvw Shareholders Equity
25621                                            Total Oneok Shareholders Equity
25151                                      Total Pfizer Inc. Shareholders Equity
3617                                               Total Ppg Shareholders Equity
6809                         Total Regal Rexnord Corporation Shareholders Equity
19763                                         Total Reliance Shareholders Equity
14230                                  Total Sei Investments Shareholders Equity
7589                                           Total Shareholders Deficit Equity
18347                                          Total Shareholders Deficit/Equity
1318                                                   Total Shareholders Equity
18430                                                  Total Shareholders Equity
25191                            Total Shareholders Equity  Controlling Interest
14770                                  Total Shareholders Equity  The Kroger Co.
24493                               Total Shareholders Equity  Yum! Brands, Inc.
18875                                Total Shareholders Equity / Members Deficit
26003             Total Shareholders Equity Attributable To Amphenol Corporation
30062            Total Shareholders Equity Attributable To Assured Guaranty Ltd.
20405                     Total Shareholders Equity Attributable To Axis Capital
13888            Total Shareholders Equity Attributable To Blue Owl Capital Inc.
2795                Total Shareholders Equity Attributable To Bruker Corporation
6191       Total Shareholders Equity Attributable To Driven Brands Holdings Inc.
12565                 Total Shareholders Equity Attributable To Everest Re Group
2599                     Total Shareholders Equity Attributable To Renaissancere
26701             Total Shareholders Equity Attributable To Snap-On Incorporated
23619                                Total Shareholders Equity Available To Arch
29758                            Total Shareholders Equity Before Treasury Stock
22593                             Total Shareholders Equity Controlling Interest
8883                                           Total Shareholders Equity Deficit
23644                Total Shareholders Equity Including Cost Of Treasury Shares
10628                                         Total Shareholders Equity Of Capri
17483                                          Total Shareholders Equity Of Mkhl
23065                                         Total Shareholders Equity/-Deficit
30800                                           Total Sonoco Shareholders Equity
22357                           Total Stifel Financial Corp. Shareholders Equity
28757                                          Total Stryker Shareholders Equity
28176          Total The Bank Of New York Mellon Corporation Shareholders Equity
25018                    Total Thermo Fisher Scientific Inc. Shareholders Equity
2975                            Total Trane Technologies Plc Shareholders Equity
4778                        Total Trimble Navigation Limited Shareholders Equity
12129                          Total Trimble Navigation Ltd. Shareholders Equity
14521                                             Total Tyco Shareholders Equity
19570                                            Total Tyson Shareholders Equity
5024                                      Total U.S. Bancorp Shareholders Equity
18594                                      Total Upjohn Inc. Shareholders Equity
26557                         Total Valmont Industries, Inc. Shareholders Equity
11724                                           Total Vertex Shareholders Equity
17145                           Total Victorias Secret & Co. Shareholders Equity
13574                             Total Voya Financial, Inc. Shareholders Equity
8964                               Total W.W. Grainger, Inc. Shareholders Equity
17588                   Total Walgreens Boots Alliance, Inc. Shareholders Equity
5355                                           Total Walmart Shareholders Equity
17659                                     Total Watsco, Inc. Shareholders Equity
9726                     Total Webster Financial Corporation Shareholders Equity
9616   Total Westinghouse Air Brake Technologies Corporation Shareholders Equity
30899                                              Total Wtw Shareholders Equity
27085                                             Totalequifaxshareholdersequity

In [17]:
mask = df['line_item'].str.contains(r"Total.* Stockholder[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Temp|Abstract|Before",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Attrib",case=True, regex=True, na=False)
df[mask]

                                                                                 line_item
2604                                                      Total Nasdaq Stockholders Equity
2621                                                      Total Mosaic Stockholders Equity
2995                                    Total Idexx Laboratories, Inc. Stockholders Equity
3716                                        Total Kinder Morgan, Inc.S Stockholders Equity
3717                                     Total Duke Energy Corporation Stockholders Equity
3722                                              Total Metlife, Inc.S Stockholders Equity
3844                                 Total Southern Copper Corporation Stockholders Equity
3853                                        Total Virtu Financial Inc. Stockholders Equity
4153                                     Total Boyd Gaming Corporation Stockholders Equity
4334                                                 Total Pmi Stockholders Deficit Equity
4438                                                         Total Fcx Stockholders Equity
4489                                               Total Enhabit, Inc. Stockholders Equity
4625                          Total Reinsurance Group Of America, Inc. Stockholders Equity
4942                                          Total Penn Entertainment Stockholders Equity
4956                         Total Six Flags Entertainment Corporation Stockholders Equity
5054                                                    Total Synopsys Stockholders Equity
5082                               Total Starwood Property Trust, Inc. Stockholders Equity
5293                                                     Total Stockholders/Members Equity
5378                                                  Total Oge Energy Stockholders Equity
5393                                             Total Ugi Corporation Stockholders Equity
5401                                   Total Valero Energy Corporation Stockholders Equity
5476                                Total Molson Coors Brewing Company Stockholders Equity
5499                                                   Total Paramount Stockholders Equity
5899                        Total Stockholders Equity Allocated To Oak Street Health, Inc.
6027                                                   Total Permanent Stockholders Equity
6124                                 Total Stockholders Equity See Accompanying Statements
6250                                                  Total Booz Allen Stockholders Equity
6297                                                      Total Gilead Stockholders Equity
6397                                           Total Epam Systems Inc. Stockholders Equity
6662                                     Total Penske Automotive Group Stockholders Equity
6750                                Total Stockholders Equity Of The Blackstone Group Inc.
6843                                         Total Ingersoll Rand Inc. Stockholders Equity
6856                                               Total Expedia, Inc. Stockholders Equity
6897                                      Total Evercore Partners Inc. Stockholders Equity
6942                                              Total Fortinet, Inc. Stockholders Equity
7171                                                 Total Hf Sinclair Stockholders Equity
7256                                  Total Pilgrims Pride Corporation Stockholders Equity
7317                                                 Total Live Nation Stockholders Equity
7324                                                     Total Danaher Stockholders Equity
7353                                                      Total Paypal Stockholders Equity
7581           Total Stockholders Equity, Net Of Non-Controlling Interests In Subsidiaries
7657                                                         Total Cna Stockholders Equity
7875                                           Total Merck & Co., Inc. Stockholders Equity
8252                                       Total Altice Usa Stockholders Equity Deficiency
8834                                      Total Euronet Worldwide, Inc Stockholders Equity
8885                                                Total Viasat, Inc. Stockholders Equity
9194                                         Total Jabil Circuit, Inc. Stockholders Equity
9528                                        Total Harbinger Group Inc. Stockholders Equity
9686                                             Total Blackrock, Inc. Stockholders Equity
9699                                            Total News Corporation Stockholders Equity
10123                                              Total Owens Corning Stockholders Equity
10376                                        Total Expedia Group, Inc. Stockholders Equity
10441                                  Total Church & Dwight Co., Inc. Stockholders Equity
10818                                        Total Wesco International Stockholders Equity
10901                                                Total Ads Stockholders Equity Deficit
10942                                                   Total Mckesson Stockholders Equity
10981                                                    Total Vontier Stockholders Equity
11017                                           Total Juniper Networks Stockholders Equity
11883                          Total The Madison Square Garden Company Stockholders Equity
11933                           Total Motorola Solutions, Inc. Stockholders Equity Deficit
12233                               Total On Semiconductor Corporation Stockholders Equity
12241                                         Total Masimo Corporation Stockholders Equity
12270                                                   Total Darlings Stockholders Equity
12316                            Total Uber Technologies, Inc. Stockholders Equity Deficit
12386                           Total Stockholders Equity  The Estee Lauder Companies Inc.
12502                                       Total Stockholders Equity  Lithia Motors, Inc.
12825                                                            Total Stockholders Equity
12858                                       Total Huntsman Corporation Stockholders Equity
12967                                  Total Nexstar Media Group, Inc. Stockholders Equity
12975                          Total Stockholders Equity – The Estée Lauder Companies Inc.
13044                                                        Total Cbi Stockholders Equity
13268                             Total Apollo Global Management, Inc. Stockholders Equity
13385                                                 Total Nasdaq Omx Stockholders Equity
13466                                  Total Mgm Resorts International Stockholders Equity
13541                                         Total Synnex Corporation Stockholders Equity
13631                                              Total Penn National Stockholders Equity
13635                                Total Agilon Health, Inc. Stockholders Equity Deficit
13915                                                    Total Eastman Stockholders Equity
14181                              Total Wynn Resorts, Limited Stockholders Equity Deficit
14204                                                 Total Lazard Ltd Stockholders Equity
14320                                                    Total Stockholders Equity Deficit
14323                                       Total Mckesson Corporation Stockholders Equity
14333                                        Total Unity Software Inc. Stockholders Equity
14361                                             Total Kkr & Co. Inc. Stockholders Equity
14496  Total Stockholders Equity Deficit, Net Of Non-Controlling Interests In Subsidiaries
14663                            Total United States Steel Corporation Stockholders Equity
14753                                   Total Intuitive Surgical, Inc. Stockholders Equity
14809                                 Total Crowdstrike Holdings, Inc. Stockholders Equity
14944                                                        Total Dxc Stockholders Equity
14965                                                        Total Fmc Stockholders Equity
15096                                        Total Chevron Corporation Stockholders Equity
15133                                                  Total Stockholders / Members Equity
15188                                         Total Henry Schein, Inc. Stockholders Equity
15428                                              Total Evercore Inc. Stockholders Equity
15486                                                  Total Citigroup Stockholders Equity
15487                                                    Total Fortive Stockholders Equity
15768                                            Total Borgwarner Inc. Stockholders Equity
16103                                                  Total Whirlpool Stockholders Equity
16338                           Total Nexstar Broadcasting Group, Inc. Stockholders Equity
16483                                           Total Hess Corporation Stockholders Equity
16657                                  Total Commerce Bancshares, Inc. Stockholders Equity
16944                                                      Total Intel Stockholders Equity
17045                                           Total Stockholders Equity/Partners Capital
17102                                                  Total Coty Inc. Stockholders Equity
17433                                                    Total Ashland Stockholders Equity
17726                                                     Total Baxter Stockholders Equity
17765                                                    Total Company Stockholders Equity
17790                            Total Intercontinental Exchange, Inc. Stockholders Equity
17864                             Total Stockholders Equity Including Treasury Stock Value
17953           Total Stockholders Equity, Net Of Non-Controlling Interest In Subsidiaries
17955                                             Total Snowflake Inc. Stockholders Equity
18006                                        Total—The Hershey Company Stockholders Equity
18124                                                      Total Kirby Stockholders Equity
18183                                        The Hershey Company Total Stockholders Equity
18398                                                      Total Group Stockholders Equity
18411                                                   Total Chemours Stockholders Equity
18615                                                        Total Ncr Stockholders Equity
18661                                                     Total Dupont Stockholders Equity
18992                                             Total Hilton Stockholders Equity Deficit
19310               Total Stockholders Deficit Equity Allocated To Oak Street Health, Inc.
19362                                                 Total Transunion Stockholders Equity
19566                                                    Total Bio-Rad Stockholders Equity
19574                                            Total Equity Of Marathon Oil Stockholders
19644                                               Total Knight-Swift Stockholders Equity
19755                              Total Molson Coors Beverage Company Stockholders Equity
19795                                                     Total Leidos Stockholders Equity
19892                                   Total Motorola Solutions, Inc. Stockholders Equity
19983                                                Total Wells Fargo Stockholders Equity
20174                                                        Total Ads Stockholders Equity
20240                                       Total Celanese Corporation Stockholders Equity
20363                                    Total Euronet Worldwide, Inc. Stockholders Equity
20582  Total Stockholders Deficit Equity, Net Of Non-Controlling Interests In Subsidiaries
20707                                                    Total Stockholders Deficit Equity
20912                                                        Total Fis Stockholders Equity
20978                                                        Total Kla Stockholders Equity
21206                               Total Brighthouse Financial, Inc.S Stockholders Equity
21289                                      Total Targa Resources Corp. Stockholders Equity
21315                         Total Crowdstrike Holdings, Inc. Stockholders Equity Deficit
21383                              Total Westlake Chemical Corporation Stockholders Equity
21416                                                 Total Hp Stockholders Deficit Equity
21424                                   Total Franklin Resources, Inc. Stockholders Equity
21554                                                         Total Hp Stockholders Equity
21784                                                     Total Hilton Stockholders Equity
21912                                               Total Aqua America Stockholders Equity
21934                             Total Ginkgo Bioworks Holdings, Inc. Stockholders Equity
22074                                                  Total Ingredion Stockholders Equity
22164                                         Total Stockholders Equity Of Blackstone Inc.
22205                                                     Total Clorox Stockholders Equity
22378                         Total Kimberly-Clark Corporation Stockholders Equity Deficit
22379                                    Total Mohawk Industries, Inc. Stockholders Equity
22408                                                   Total Teledyne Stockholders Equity
22459                  Total Amc Entertainment Holdings, Inc.S Stockholders Equity Deficit
22489                                              Total Vmware, Inc.S Stockholders Equity
22935                                                     Total Jacobs Stockholders Equity
23069                                           Total Transunion Corp. Stockholders Equity
23088                                Total Deckers Outdoor Corporation Stockholders Equity
23150                   Total Nexstar Broadcasting Group, Inc. Stockholders Equity Deficit
23283                                               Total Vmware, Inc. Stockholders Equity
23475                            Total Hudson Pacific Properties, Inc. Stockholders Equity
23502                                                           Total Stockholdersʼ Equity
23518                            Total Live Nation Entertainment, Inc. Stockholders Equity
23519                              Total Gardner Denver Holdings, Inc. Stockholders Equity
23604                                     Total New York Times Company Stockholders Equity
23851                                           Total Aptargroup, Inc. Stockholders Equity
23950                                                     Total Verisk Stockholders Equity
24515                                                        Total Mpc Stockholders Equity
24533                                                    Total Envista Stockholders Equity
24545                                             Total Amedisys, Inc. Stockholders Equity
24705                   Total Stockholders Equity/Members Deficit Allocated To The Company
24713                                       Total Westlake Corporation Stockholders Equity
24823                                    Total Uber Technologies, Inc. Stockholders Equity
25007                                            Total Stockholders Equity/Members Deficit
25040                           Total Idexx Laboratories, Inc. Stockholders Equity Deficit
25072                         Total Madison Square Garden Sports Corp. Stockholders Equity
25147                                                   Total Reliance Stockholders Equity
25408                                            Total Aes Corporation Stockholders Equity
25578                                                        Total Hpe Stockholders Equity
26035                                           Total Stockholders Equity / Net Investment
26251                                         Total Vail Resorts, Inc. Stockholders Equity
26469                                                        Total Cpi Stockholders Equity
26554                                                      Total Nucor Stockholders Equity
26618                                        Total The Aes Corporation Stockholders Equity
26687                                               Total Trimble Inc. Stockholders Equity
27038                                             Total Assurant, Inc. Stockholders Equity
27547                                       Total Dish Network Stockholders Equity Deficit
27564                                                      Total Aecom Stockholders Equity
27652                         Total Penn National Gaming, Inc. Stockholders Equity Deficit
27948                                           Total Company Share Of Stockholders Equity
28017                                           Total Agco Corporation Stockholders Equity
28230                                                   Total Stockholders Equity/-Deficit
28324                                  Total Ipg Photonics Corporation Stockholders Equity
28430                                                 Total Jabil Inc. Stockholders Equity
28507                                 Total Kimberly-Clark Corporation Stockholders Equity
28511                                       Total Partners Capital And Stockholders Equity
28586                                 Total Stockholders Equity – Dolby Laboratories, Inc.
28667                                                        Total Ibm Stockholders Equity
28761                                                  Total Viacomcbs Stockholders Equity
28864                                             Total Stockholders Equity/Members Equity
28869                               Total Warner Bros. Discovery, Inc. Stockholders Equity
29029                                    Total Republic Services, Inc. Stockholders Equity
29155                                                     Total Cooper Stockholders Equity
29280                                                 Total Stockholders Equity Deficiency
29308                                            Total Fox Corporation Stockholders Equity
29550                                                   Total Nisource Stockholders Equity
29558                                   Total Stockholders Equity-Dolby Laboratories, Inc.
29629                                             Total Penumbra, Inc. Stockholders Equity
29630                                                   Total Seaboard Stockholders Equity
29631                                                        Total Ipg Stockholders Equity
29637                                     Total Waste Management, Inc. Stockholders Equity
29710                               Total Mckesson Corporation Stockholders Equity Deficit
29805                                                   Total Illumina Stockholders Equity
29876                                              Total Broadcom Inc. Stockholders Equity
29954                                                   Total Wex Inc. Stockholders Equity
30172                                          Total Quest Diagnostics Stockholders Equity
30261                                                      Total Ionis Stockholders Equity
30323                                   Total Diamondback Energy, Inc. Stockholders Equity
30374                                                     Total Costco Stockholders Equity
30480                                                   Total Hologics Stockholders Equity

In [18]:
mask = df['line_item'].str.contains(r"Total.* Shareowner[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Abs|Attrib",case=False, regex=True, na=False)
df[mask]

                                            line_item
3496                      Total Ge Shareowners Equity
5159                 Total Company Shareowners Equity
13949        Total Shareowners Equity  The Kroger Co.
22861                        Total Shareowners Equity
27074              Total Honeywell Shareowners Equity
30169  Total Campbell Soup Company Shareowners Equity
30993                 Total Shareowners Common Equity

### Total Common Shareholders

In [19]:
mask = df['line_item'].str.contains(r"Total.* Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Abstract",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Non|Attrib",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                                                                       line_item
6804                                            Total Common Shareholders Equity
10674  Total Common Shareholders Equity Before Items Of Other Comprehensive Loss
23048                     Total Edison Internationals Common Shareholders Equity
9995             Total Jefferies Financial Group Inc. Common Shareholders Equity
4847                                    Total Pepsico Common Shareholders Equity
10979                           Total White Mountains Common Shareholders Equity
19101                          Total White Mountainss Common Shareholders Equity

In [20]:
mask = df['line_item'].str.contains(r"Total.* Stockholder[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Temp|Abstract|Before",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Non|Sub|Attrib",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                              line_item
23915  Total Common Stockholders Equity

In [21]:
mask = df['line_item'].str.contains(r"Total.* Shareowner[s]?",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Common",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Ordinary|Par Value|Per Share",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Temp|Abstract|Before",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Liabilit|Non|Sub|Attrib",case=True, regex=True, na=False)

df[mask].sort_values(by='line_item')

                             line_item
30993  Total Shareowners Common Equity

### Total Liabilities and Shareholder Equity

In [22]:
mask = df['line_item'].str.contains(r"Stockholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Total",case=True, regex=True, na=False) & \
           df['line_item'].str.contains(r"Liab",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Indemnity",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Non|Convert|Redeem",case=True, regex=True, na=False)
df[mask]

                                                                         line_item
3417                    Total Liabilities And Stockholders Equity/Partners Capital
4060                                    Total Liabilities, And Stockholders Equity
4629           Total Liabilities, Temporary Equity And Stockholders Deficit Equity
6450                             Total Liabilities And Stockholders Equity Deficit
6743                     Total Liabilities And Stockholders Equity/Members Deficit
6746                  Total Liabilities, Temporary Equity, And Stockholders Equity
7696                    Total Liabilities And Stockholders Equity / Net Investment
11754                            Total Liabilities And Stockholders/Members Equity
12137                            Total Liabilities And Stockholders Deficit Equity
12295                  Total Liabilities, Mezzanine Equity And Stockholders Equity
12864            Total Liabilities And Temporary And Permanent Stockholders Equity
12934                           Total Liabilities And Stockholders Equity/-Deficit
13722                              Total Liabilities & Stockholders Equity Deficit
14594          Total Liabilities, Temporary Equity And Stockholders Equity Deficit
15890                             Total Liabilities And Common Stockholders Equity
16021                                   Total Liabilities And Stockholdersʼ Equity
16113                                      Total Liabilities & Stockholders Equity
16162                    Total Liabilities And Stockholders Deficit/Members Equity
18471                                    Total Liabilities And Stockholders Equity
19003               Total Liabilities And Partners Capital And Stockholders Equity
22647                    Total Liabilities And Stockholders Equity/Members Capital
25506                                   Liabilities And Stockholders Equity, Total
25658  Total Liabilities, Temporary Equity & Stockholders Equity / Members Deficit
26379                  Total Liabilities, Temporary Equity And Stockholders Equity
28575                     Total Liabilities And Stockholders Equity/Members Equity
28889          Total Liabilities, Mezzanine Equity And Stockholders Equity Deficit
31353                           Total Liabilities And Stockholders / Member Equity

In [23]:
mask = df['line_item'].str.contains(r"Shareholder",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Total",case=True, regex=True, na=False) & \
           df['line_item'].str.contains(r"Liab",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Indemnity",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Non|Convert|Redeem",case=True, regex=True, na=False)
df[mask]

                                                               line_item
3163                   Total Liabilities And Shareholders Equity Deficit
4323                   Total Liabilities And Shareholders Deficit/Equity
7468         Total Liabilities And Shareholders Equity / Members Deficit
7531                             Total Liabilities & Shareholders Equity
10677                         Liabilities And Shareholders Equity, Total
11343  Total Liabilities, Preferred Stock And Common Shareholders Equity
12089                          Total Liabilities And Shareholders Equity
13196                           Total Liabilities And Shareholdersequity
20468        Total Liabilities, Mezzanine Equity And Shareholders Equity
20684                  Total Liabilities And Bancorp Shareholders Equity
23236                          Total Shareholders Equity And Liabilities
23311                   Total Liabilities And Common Shareholders Equity
26950       Total Liabilities, Temporary Equity, And Shareholders Equity
28596                 Total Liabilities And Shareholders Equity/-Deficit

In [24]:
mask = df['line_item'].str.contains(r"Shareowner",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Equity",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Total",case=True, regex=True, na=False) & \
           df['line_item'].str.contains(r"Liab",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Parent|Indemnity",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Non|Convert|Redeem",case=True, regex=True, na=False)
df[mask]

                                      line_item
30646  Total Liabilities And Shareowners Equity

### Total Liabilities

In [25]:
mask = df['line_item'].str.contains(r"Total",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"liabilities",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"Variable Interest Entities|Res",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"-|services|controllling|discontinued",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"long|current|sale|equity|obligations",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"investment|deposit|deficit|capital",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"other|subject|vehicle|deferred|tax",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"deficiency|Vie|insurance|accruals",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"banking|policy|accrued|consumer|lease",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"-|services|controllling|discontinued",case=False, regex=True, na=False)

df[mask]

                line_item
14074  Liabilities, Total
27089   Total Liabilities

In [26]:
mask = df['line_item'].str.contains(r"Total",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"liabilities",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Res",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"Variable Interest Entities",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"long|current|sale|equity|obligations",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"investment|deposit|deficit|capital",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"other|subject|vehicle|deferred|tax",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"deficiency|Vie|insurance|accruals",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"banking|policy|accrued|consumer|lease",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"-|services|controllling|discontinued",case=False, regex=True, na=False)

df[mask]

                                                                                               line_item
5922                              Total Liabilities Restricted  .1 Billion On December 31, 2013 And 2012
12085  Total Liabilities Restricted  .6 Billion On December 31, 2011 And .8 Billion On December 31, 2010

### Property, Plant and Equipment

In [28]:
mask = df['line_item'].str.contains(r"Property",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Plant",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equipment",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree|^Other",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg|Total|Member",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,154,"Property, Plant And Equipment [Abstract]"
1,179,"Property, Plant And Equipment, At Cost:"
2,339,"Net Property, Plant And Equipment"
3,611,"Property, Plant And Equipment Note"
4,625,"Property, Plant, And Equipment"
5,739,"Property, Plant And Equipment:"
6,777,"Property, Plant And Equipment, Net"
7,786,"Property, Plant And Equipment—At Cost"
8,789,Property Plant And Equipment
9,833,"Property, Plant And Equipment At Cost"
10,1003,"Property, Plant, And Equipment, At Cost:"
11,1325,"Property, Plant And Equipment"
12,1479,"Plant, Property, And Equipment At Cost"
13,1819,"Plant, Property, And Equipment"
14,1828,"Property, Plant And Equipment, Net [Abstract]"
15,1954,"Property, Plant, And Equipment:"
16,2228,"Property, Plant And Equipment, At Cost"
17,2562,"Nonutility Property, Plant And Equipment, Less Accumulated Depreciation Of 123 And 113 At Respec..."
18,2615,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 27,656 And 23,075, Respectively"
19,2848,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 357.7 And 291.1, Respectively"
20,2899,"Property, Plant And Equipment, Net Of Accumulated Depreciation 8,332 And 7,865 Note"
21,2977,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 36,164 And 34,253, Respectively"
22,3083,Net Depreciable Property Plant And Equipment
23,3459,"Property, Plant And Equipment Net Of Accumulated Depreciation Of 11,198 And 11,576"
24,3641,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 583.8 And 498...."
25,3658,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 17,2..."
26,4168,"Property, Plant And Equipment, Less Accumulated Depreciation And Amortization Of 506.4 And 482.8..."
27,4405,"Property, Plant, And Equipment, Net Of Accumulated Depreciation And Amortization Of 8,878.7 And ..."
28,4483,"Nonutility Property, Plant And Equipment, Less Accumulated Depreciation"
29,4577,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 20,3..."
30,4728,"Property, Plant, And Equipment, Net Of Accumulated Depreciation And Amortization Of 10,383.8 And..."
31,4944,"Property, Plant And Equipment, Net Mplx: 12,187 And 11,408, Respectively"
32,5171,"Property, Plant, And Equipment, At Cost, Net Of Accumulated Depreciation And Amortization"
33,5174,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 468.0 In 2013 And 416.8 In 2012"
34,5236,"Property, Plant And Equipment, Net Of Accumulated Depreciation 9,884 And 9,188 Note"
35,5242,"Property, Plant And Equipment, Net Of Accumulated Depreciation 9,188 And 8,332 Note"
36,5243,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,194.1 And 3,690.6, Respectively"
37,5390,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 21,8..."
38,5437,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 117.1 Million As Of December 3..."
39,5478,"Property, Plant, And Equipment, At Cost"
40,5570,"Property, Plant And Equipment, Less Accumulated Depreciation Of 426,019 In 2015 And 364,124 In 2014"
41,5616,"Property, Plant And Equipment, At Cost, Less Accumulated Depreciation And Amortization"
42,5760,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 577.1 In 2011 And 539.6 In 2010"
43,6528,"Plant, Property And Equipment, Net"
44,6530,"Property, Plant And Equipment And Finance Lease Right-Of-Use Asset, Net"
45,6577,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 717.2 And 682.9 In 2016 And 20..."
46,6732,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 22,2..."
47,6998,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 718.6 And 644...."
48,7067,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 373.3 And 298.4, Respectively"
49,7124,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 21,8..."
50,7241,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,831 In 2016 And 4,849 In 2015"
51,7292,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,192.1 And 2,694.5, Respectively"
52,7303,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 1,578,266 At August 31, 2012 A..."
53,7419,"Property, Plant And Equipment, At Cost, Net"
54,7424,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 7,258 For 2022 And 6,819 For 2021"
55,7679,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 123.4 And 70.2"
56,7770,"​Property, Plant And Equipment, Net"
57,7782,"Property, Plant And Equipment, Net...Note"
58,7911,"Property, Plant, And Equipment, Net"
59,7935,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 2,599,579 And 1,039,297"
60,8074,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,563 And 2,364, Respectively"
61,8153,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 23,075 And 18,077, Respectively"
62,8270,"Utility Property, Plant And Equipment, Less Accumulated Depreciation Of 6,894 And 6,319 At Respe..."
63,8320,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 17.1 Million And 11.5 Million,..."
64,8335,"Property, Plant And Equipment, Net Of Accumulated Depreciation 13,663 And 12,995 Note"
65,8485,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 31,639 And 27,656, Respectively"
66,8597,"Property, Plant, And Equipment Net Of Accumulated Depreciation Of 7,096 And 6,064"
67,8615,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 2,364 And 1,190, Respectively"
68,8621,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 80.8 Million In 2016 And 64.7 ..."
69,8670,"Property, Plant, And Equipment And Finance Lease Right-Of-Use Asset, After Accumulated Depreciat..."
70,8701,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 22,4..."
71,8779,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 19,271 And 31,596"
72,8997,"Property, Plant And Equipment"
73,9248,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 447.5 And 412...."
74,9249,"Plant, Property And Equipment"
75,9290,"Property, Plant And Equipment, Less Accumulated Depreciation Of 667.8 In 2019 And 678.1 In 2018"
76,9401,"Property Plant And Equipment, Gross"
77,9419,"Property, Plant And Equipment Net Of Accumulated Depreciation 2021: 3,484; 2020: 3,279"
78,9455,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 18,0..."
79,9586,"Property, Plant, And Equipment Net Of Accumulated Depreciation And Amortization Of 16,726 And 15..."
80,9674,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 8,056 And 7,096"
81,9795,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 25,155 And 11,313 As Of Decemb..."
82,9797,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 445.2 And 388.3"
83,10055,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 644.3 And 592...."
84,10158,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 367.3 And 323...."
85,10224,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 6,819 For 2021 And 6,335 For 2020"
86,10310,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,850 For 2019 And 5,369 For 2018"
87,10318,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 1,363,481 At August 31, 2011 A..."
88,10655,"Property, Plant, And Equipment – Net"
89,10676,"Property Plant And Equipment, Net"
90,10688,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 778.5 And 774.2 In 2018 And 20..."
91,11238,"Property, Plant And Equipment, Net Of Accumulated Depreciation 12,995 And 11,932 Note"
92,11379,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 34,253 And 31,639, Respectively"
93,11431,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 8,214.6 And 7,919.1, Respecti..."
94,11810,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 7,142,852 And 6,431,843"
95,12235,"Property, Plant, And Equipment"
96,12322,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 298.4 And 250.0, Respectively"
97,12702,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 711.3 And 625.4"
98,12727,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 625.4 And 532.3"
99,13001,"Accumulated Depreciation, Depletion And Amortization, Property, Plant, And Equipment"
100,13356,"Property, Plant & Equipment, Net"
101,13487,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 203.8 And 146.1, Respectively"
102,13532,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,690.6 And 3,192.1, Respectively"
103,13691,"Net Property, Plant And Equipment Note"
104,13838,"Property, Plant And Equipment In Service Net Of Accumulated Provision For Depreciation"
105,13889,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 70.2 And 26.4"
106,14490,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,849 In 2015 And 4,611 In 2014"
107,14627,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 23,8..."
108,14886,"Property, Plant And Equipment And Right Of Use Assets, Net"
109,15045,"Property, Plant And Equipment—Net"
110,15277,"Utility Property, Plant And Equipment, Less Accumulated Depreciation Of 7,424 And 6,894 At Respe..."
111,15412,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 174.3 And 123.4"
112,15464,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 445.5 And 403...."
113,15484,"Property, Plant And Equipment, Net Mplx: 10,730 And 9,997, Respectively"
114,15604,"Property, Plant, And Equipment Net"
115,15698,"Property, Plant And Equipment-Net Note"
116,15761,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,175 And 3,056, Respectively"
117,15912,"Property, Plant And Equipment, Net Of Accumulated Depreciation 11,932 And 10,809 Note"
118,15940,"Property, Plant And Equipment, Gross"
119,16098,"Nonutility Property, Plant And Equipment, Less Accumulated Depreciation Of 74 And 123 70 And 117..."
120,16347,"Nonutility Property, Plant And Equipment, Less Accumulated Depreciation Of 76 And 74 75 And 70 F..."
121,16685,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 366.2 And 299.3"
122,16959,"Property, Plant, Equipment And Development Costs, Net"
123,17478,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 19,2..."
124,17649,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,146 In 2012 And 3,933 In 2011"
125,17883,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 64.7 Million In 2015 And 40.9 ..."
126,17944,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,337 In 2013 And 4,146 In 2012"
127,18025,"Property, Plant And Equipment, Net"
128,18170,"Property, Plant And Equipment, At Cost, Net Of Accumulated Depreciation"
129,18623,"Property, Plant And Equipment, Net Note"
130,18639,"Property, Plant And Equipment Net Note"
131,18645,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 19,886 And 19,271"
132,18647,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 513.7 In 2014 And 468.0 In 201..."
133,18655,"Property, Plant And Equipment, Net Of Accumulated Depreciation"
134,18675,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 774.2 And 717.2 In 2017 And 20..."
135,18775,"Property, Plant And Equipment, At Cost Note"
136,19257,Property Plant And Equipment Other Net
137,19263,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 299.3 And 235.6"
138,19307,"Property, Plant And Equipment – Net"
139,19754,"Property, Plant And Equipment, Other, Gross"
140,19895,"Property, Plant And Equipment At Cost"
141,19960,"Property, Plant And Equipment, Gross, Ending Balance"
142,20298,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 417.4 And 357.7, Respectively"
143,20453,Property Plant And Equipment Net
144,20839,"Property, Plant And Equipment Note"
145,20921,"Property, Plant And Equipment Net Of Accumulated Depreciation"
146,20935,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 31,596 And 29,346"
147,21257,"Property, Plant, And Equipment, Net Of Accumulated Depreciation And Amortization Of 9,364.7 And ..."
148,21396,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 6,335 For 2020 And 5,850 For 2019"
149,21406,"Net Property, Plant And Equipment In Service"
150,21610,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 23,2..."
151,21646,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 568.7 In 2015 And 513.7 In 20..."
152,21928,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,044,671 And 2,599,579"
153,21943,"Property, Plant, And Equipment Net Of Accumulated Depreciation Of 11,007 And 9,480"
154,22226,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 824.3 And 778.5 In 2019 And 20..."
155,22403,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 548.9 And 454.4"
156,22600,"Property, Plant And Equipment Net"
157,22751,"Property, Plant And Equipment, Less Accumulated Depreciation Of 495,215 In 2016 And 426,019 In 2015"
158,22752,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 21,5..."
159,22774,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 2,694.5 And 2,172.0, Respectively"
160,22958,"Utility Property, Plant And Equipment, Less Accumulated Depreciation And Amortization Of 8,132 A..."
161,23348,"Property, Plant And Equipment And Finance Lease Right-Of-Use Assets, Net"
162,23485,"Plant, Property, And Equipment, Gross"
163,23528,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,232 And 3,175, Respectively"
164,23574,"Property, Plant And Equipment—At Cost"
165,23832,"Property, Plant And Equipment Net Of Accumulated Depreciation 2011: 1,316; 2010: 1,131"
166,23961,"Property, Plant, Equipment And Mine Development Costs, Net"
167,24007,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,369 For 2018 And 5,066 For 2017"
168,24189,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 518.4 And 445.2"
169,24308,"Plant, Property, And Equipment, Net"
170,24312,"Property, Plant And Equipment, Net Of Accumulated Depreciation 10,809 And 9,884 Note"
171,24378,"Property, Plant And Equipment, Less Accumulated Depreciation Of 603.2 In 2017 And 495.2 In 2016"
172,24383,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,066 For 2017 And 4,831 For 2016"
173,24392,"Property, Plant, And Equipment, Net Note"
174,24429,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,787 And 3,563, Respectively"
175,24944,"Property, Plant, And Equipment Net Of Accumulated Depreciation Of 9,789 And 11,007"
176,25054,"Property, Plant, Equipment And Mining Development Costs, Net"
177,25412,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,363.8 And 4,765.0, Respectively"
178,25530,"Net Property, Plant, And Equipment"
179,25768,"Property, Plant And Equipment Net Of Accumulated Depreciation Of 12,249 And 11,198"
180,25822,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 9,480 And 8,056"
181,25893,"Gross Property, Plant, And Equipment"
182,26088,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,611 In 2014 And 4,337 In 2013"
183,26123,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 388.3 And 307.8"
184,26213,"Property, Plant And Equipment – Net Note"
185,26243,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 235.6 And 174.3"
186,26394,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 6,518 And 5,484, Respectively"
187,26440,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 26.4 And 342.3"
188,26492,"Property, Plant, And Equipment, Less Accumulated Depreciation And Amortization Of 639.7 And 583...."
189,26707,"Property, Plant And Equipment, Less Accumulated Depreciation, Depletion And Amortization Of 21,8..."
190,26769,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 4,765.0 And 4,194.1, Respectively"
191,26890,"Competitive Power Generation And Other Property, Plant And Equipment, Less Accumulated Depreciat..."
192,26937,"Property, Plant And Equipment, Less Accumulated Depreciation Of 629.7 In 2020 And 667.8 In 2019"
193,27055,"Property, Plant, And Equipment, Gross"
194,27392,"Property, Plant And Equipment, Net Of Accumulated Depreciation And Amortization Of 454.4 And 366.2"
195,27676,"Non-Real Estate Property, Plant And Equipment, Net"
196,28156,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 6,431,843 And 5,276,921"
197,28278,"Property, Plant And Equipment, At Cost"
198,28707,"Net Property, Plant And Equipment"
199,28787,"Property, Plant And Equipment, Less Accumulated Depreciation Of 657.7 In 2022 And 658.5 In 2021"
200,28998,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 6,025.4 And 5,363.8, Respectively"
201,29011,"Property, Plant And Equipment, Less Accumulated Depreciation Of 658.5 In 2021 And 629.7 In 2020"
202,29238,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 18,077 And 11,103, Respectively"
203,29370,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 8,515.9 And 8,618.5, Respecti..."
204,29466,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,484 And 4,787, Respectively"
205,29575,"Nonutility Property, Plant And Equipment, Less Accumulated Depreciation At Respective Dates"
206,29970,"Property, Plant And Equipment Gross"
207,29994,"Utility Property, Plant And Equipment, Less Accumulated Depreciation Of 7,493 And 7,424 At Respe..."
208,30170,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 8,618.5 And 8,214.6, Respecti..."
209,30279,"Property, Plant And Equipment, Less Accumulated Depreciation Of 678.1 In 2018 And 603.2 In 2017"
210,30329,"Property, Plant And Equipment Net Of Accumulated Depreciation 2022: 3,687; 2021: 3,484"
211,30351,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,326 And 3,232, Respectively"
212,30419,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 3,056 And 2,915, Respectively"
213,30420,"Property, Plant And Equipment, At Cost, Less Accumulated Depreciation Of 1,186.1 And 1,168.3"
214,30447,"Deferred Tax Assets, Property, Plant And Equipment"
215,30448,"Property, Plant And Equipment, At Cost, Less Accumulated Depreciation And Depletion"
216,30557,"Property, Plant, And Equipment, Net Of Accumulated Depreciation Of 29,204 And 27,970, Respectively"
217,30703,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 250.0 And 203.8, Respectively"
218,30708,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 635.7 In 2012 And 577.1 In 2011"
219,30807,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 11,103 And 6,518, Respectively"
220,31228,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 5,276,921 And 4,044,671"
221,31245,"Property, Plant And Equipment-Net"
222,31417,"Property, Plant And Equipment, Less Accumulated Depreciation"
223,31734,"Property, Plant And Equipment, Net Of Accumulated Depreciation Of 307.8 And 225.8"
224,31869,"Utility Property, Plant And Equipment, Less Accumulated Depreciation And Amortization"

### Total Current Liabilities

In [29]:
mask = df['line_item'].str.contains(r"Total",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"liabilities",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"current",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"Variable Interest Entities",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"long|Res|Vie|sale|equity|obligations",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"investment|deposit|deficit|capital",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"other|subject|vehicle|deferred|tax",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"deficiency|insurance|accruals|non",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"banking|policy|accrued|consumer|lease",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"-|services|controllling|discontinued",case=False, regex=True, na=False)

df[mask]

                         line_item
11813    Current Liabilities Total
24697  Liabilities, Current, Total
26053    Total Current Liabilities

### Total Non-Current Liabilities

In [30]:
mask = df['line_item'].str.contains(r"Total",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"liabilities",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Non.*Current",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"Variable Interest Entities",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"long|Res|Vie|sale|equity|obligations",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"investment|deposit|deficit|capital",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"other|subject|vehicle|deferred|tax",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"deficiency|insurance|accruals",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"banking|policy|accrued|consumer|lease",case=False, regex=True, na=False) & \
         ~ df['line_item'].str.contains(r"-|services|controllling|discontinued",case=False, regex=True, na=False)

df[mask]

                           line_item
6969    Total Noncurrent Liabilities
19659  Total Non‑Current Liabilities

### Accounts Receivable

In [31]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Net Of Allow",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp",case=False, regex=True, na=False)
df[mask]

                                                                                                 line_item
2441                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 173 And 336
2487                                                 Accounts Receivable, Net Of Allowances Of 845 And 882
2576                                                  Accounts Receivable, Net Of Allowance Of 1.3 And 1.6
2593                           Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 704 And 454
2597                           Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 483 And 547
2610   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 5,807 And 5,362 As Of January 31,...
2791                                  Accounts Receivable, Net Of Allowance Of 114 In 2022 And 122 In 2021
2819                                 Accounts Receivable, Net Of Allowances Of 254 Million And 251 Million
2855                                                 Accounts Receivable  Net Of Allowances Of 174 And 189
2888   Accounts Receivable, Net Of Allowances For Doubtful Accounts Of 1 Million And 2 Million As Of De...
2959                                             Accounts Receivable, Net Of Allowances Of 4,465 And 2,752
3056   Accounts Receivable, Net Of Allowances For Doubtful Accounts Of 1 Million Each As Of December 31...
3068                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 58.0 And 61.7
3078                                             Accounts Receivable, Net Of Allowances Of 2,062 And 1,979
3098                                 Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 14 And
3108                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 405 And 426
3189                             Accounts Receivable Net Of Allowance For Doubtful Accounts Of 450 And 504
3216                             Accounts Receivable, Net Of Allowances Of 214.7 Million And 213.8 Million
3275                               Accounts Receivable, Net Of Allowances Of 43.5 In 2018 And 36.6 In 2017
3292                                  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 7 And
3398     Accounts Receivable, Net Of Allowances Of 1,032 At December 31, 2015 And 356 At December 31, 2014
3400                Accounts Receivable Net Of Allowance For Doubtful Accounts Of 7 In 2021 And 18 In 2020
3670                                                 Accounts Receivable  Net Of Allowances Of 189 And 233
3674                                              Accounts Receivable, Net Of Allowance Of 7,959 And 6,930
3675                                                Accounts Receivable, Net Of Allowance Of 64.9 And 59.0
3851                                                   Accounts Receivable, Net Of Allowance Of 65 And 101
3899                           Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 907 And 663
4031                                 Accounts Receivable, Net Of Allowances Of 251 Million And 270 Million
4096                Accounts Receivable, Net Of Allowance Of 944 And 2,000 As Of January 31, 2016 And 2017
4154   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 55 At December 31, 2015 And 43 At...
4212   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 15 As Of Both December 31, 2019 A...
4353                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 633 And 751
4599                                             Accounts Receivable, Net Of Allowances Of 5,215 And 5,447
4606   Accounts Receivable Net Of Allowance For Doubtful Accounts Of 4,246 At October 29, 2017, And 4,0...
4733        Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 3,761 In 2015 And 4,246 In 2014
4795                                  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 2 And
4841                                    Accounts Receivable, Net Of Allowances Of 20 In 2012 And 5 In 2011
4906                                                   Accounts Receivable, Net Of Allowances Of 67 And 86
5035                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 38 38 In 2013
5344                                        Accounts Receivable  Net Of Allowance For Doubtful Accounts Of
5388                                                     Accounts Receivable, Net Of Allowance Of 9 And 10
5411                              Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 31 And 96
5441   Accounts Receivable, Net Of Allowances Of 334,307 At December 31, 2013 And 261,013 At December 3...
5482                                               Accounts Receivable, Net Of Allowances Of 26.4 And 26.2
5507                                                       Accounts Receivable, Net Of Allowance Of 10 And
5593   Accounts Receivable Net Of Allowance For Doubtful Accounts Of 4,033 At October 31, 2021, And 4,0...
5609                               Accounts Receivable, Net Of Allowances Of 29.1 In 2012 And 28.0 In 2011
5699                                          Accounts Receivable, Net Of Allowances Of 22.5 2021 And 25.9
5712   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 1,073 At December 31, 2016 And 1,...
5810                                                Accounts Receivable, Net Of Allowance Of 1,033 And 945
5943                                          Accounts Receivable, Net Of Allowances Of 44.3 2015 And 55.0
5966               Accounts Receivable And Accrued Revenues Net Of Allowances Of 4 Million 2019: 3 Million
6607   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 93 At December 31, 2018 And 68 At...
6617                Accounts Receivable, Net Of Allowance Of 1,062 And 660 As Of January 31, 2018 And 2019
6665                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 61.7 And 58.1
6668                                   Accounts Receivable, Net Of Allowances Of 43 In 2019 And 43 In 2018
6725                                                   Accounts Receivable  Net Of Allowances Of 91 And 94
6745                                       Accounts Receivable, Net Of Allowance Of None For 2011 And 2010
6798                           Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 454 And 483
6839                              Accounts Receivable, Net Of Allowance Of 2,429 In 2021 And 3,080 In 2020
6859   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 68 At December 31, 2017 And 54 At...
6902                             Accounts Receivable Net Of Allowance For Doubtful Accounts Of 456 And 450
6986                                                 Accounts Receivable, Net Of Allowances Of 102 And 116
7121                              Accounts Receivable, Net Of Allowance Of 2,919 In 2019 And 1,788 In 2018
7307   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 1,127 At December 31, 2014 And 1,...
7566                            Accounts Receivable Net Of Allowances Of 12,860 In 2014 And 14,252 In 2013
7593   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 5,362 And 2,982 As Of January 31,...
7610                              Accounts Receivable, Net Of Allowance Of 2,000 In 2017 And 1,890 In 2016
7616                              Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 51 And 45
7684                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 2,191 And 173
7759                              Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 43 And 38
7857              Accounts Receivable Net Of Allowance For Doubtful Accounts Of 86 In 2019 And 119 In 2018
7889                                             Accounts Receivable, Net Of Allowances Of 1,472 And 1,306
7896                                       Accounts Receivable, Net Of Allowance Of None For 2015 And 2014
8035   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 108 At December 31, 2020 And 103 ...
8072                                          Accounts Receivable, Net Of Allowances Of 55.0 2014 And 62.2
8110                                  Accounts Receivable, Net Of Allowance Of 122 In 2021 And 125 In 2020
8346                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 336 And 261
8397                           Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 878 And 957
8517                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 336 And 389
8738             Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 39.3 In 2015; 22.2 In 2014
8775                                           Accounts Receivable, Net Of Allowance For Doubtful Accounts
8811        Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 1,885 In 2012 And 2,408 In 2011
8875                                                  Accounts Receivable, Net Of Allowance Of 225 And 296
9024                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 333 And 375
9032            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 3.6 In 2017 And 3.5 In 2016
9181                                             Accounts Receivable, Net Of Allowances Of 9,398 And 5,839
9376                                              Accounts Receivable, Net Of Allowances Of 13 2022 And 12
9470                               Accounts Receivable, Net Of Allowances Of 25.7 In 2016 And 27.5 In 2015
9610                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 37 40 In 2015
9684                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 24.9 And 22.5
9785                            Accounts Receivable Net Of Allowances Of 46,948 In 2018 And 33,387 In 2017
9802                                                Accounts Receivable, Net Of Allowance Of 945 And 1,057
9858                             Accounts Receivable Net Of Allowance For Doubtful Accounts Of 488 And 443
9919   Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 136 At July 27, 2019 And 129 At J...
9974                                             Accounts Receivable, Net Of Allowances Of 3,105 And 3,259
9979                          Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 38 38 In 2012
9989                            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 788 And 411
10113                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 61.0 And 58.0
10151                             Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 38 And 46
10331  Accounts Receivable Net Of Allowance For Doubtful Accounts Of 195 In 2016 And 165 In 2015 Exclud...
10336                                      Accounts Receivable, Net Of Allowance Of None For 2012 And 2011
10447                                 Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 3 And
10507                            Accounts Receivable, Net Of Allowances Of 213.8 Million And 276.2 Million
10522                                                  Accounts Receivable, Net Of Allowance Of 101 And 41
10567                                         Accounts Receivable, Net Of Allowances Of 38.7 2017 And 40.3
10576  Accounts Receivable Net Of Allowance For Doubtful Accounts Of 3,507 At October 30, 2022, And 4,0...
10707                                                Accounts Receivable  Net Of Allowances Of 105 And 108
10756                             Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 46 And 20
10817                                                   Accounts Receivable, Net Of Allowance Of 41 And 34
10956  Accounts Receivable Net Of Allowance For Doubtful Accounts Of 4,051 At October 28, 2018, And 4,2...
11030                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 32.1 And 24.9
11085                                            Accounts Receivable, Net Of Allowances Of 1,166 And 2,098
11091                                               Accounts Receivable Net Of Allowances Of 49.7 And 45.8
11156                                     Accounts Receivable, Net Of Allowance For Bad Debts Of 24 And 27
11192                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 783 And 613
11241                            Accounts Receivable, Net Of Allowances Of 222.2 Million And 214.4 Million
11283                                              Accounts Receivable, Net Of Allowances Of 12 2021 And 9
11288                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 426 And 335
11309                                    Accounts Receivable, Net Of Allowances Of 5 In 2011 And 0 In 2010
11321                                                Accounts Receivable, Net Of Allowances Of 939 And 845
11357                                                 Accounts Receivable, Net Of Allowances Of 86 And 102
11399                              Accounts Receivable, Net Of Allowances Of 36.6 In 2017 And 25.7 In 2016
11471                                               Accounts Receivable Net Of Allowances Of 66.3 And 53.2
11487  Accounts Receivable Net Of Allowance For Doubtful Accounts Of 4,000 At October 28, 2012 And 4,00...
11490                                                   Accounts Receivable, Net Of Allowance Of 34 And 31
11522                                            Accounts Receivable, Net Of Allowances Of 5,447 And 3,751
11536                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 24.9 And 32.6
11621                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 24.7 And 21.7
11630                 Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 5.7 In 2020 2019  2.5
11647             Accounts Receivable, Net Of Allowance Of 2,000 And 1,062 As Of January 31, 2017 And 2018
11826                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 41.1 And 46.7
11830           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 5.4 In 2021 And 4.9 In 2020
11847                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 301 And 336
11864                                                 Accounts Receivable, Net Of Allowance Of 1.2 And 0.8
11885                           Accounts Receivable Net Of Allowances Of 14,542 In 2017 And 16,815 In 2016
12196  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 2,447 At December 31, 2017 And 1,...
12251  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 6,011 And 5,807 As Of January 31,...
12637                                     Accounts Receivable, Net Of Allowance For Bad Debts Of 19 And 18
12648              Accounts Receivable, Net Of Allowance Of 660 And 542 At The End Of Fiscal 2019 And 2020
12790                                 Accounts Receivable, Net Of Allowance Of 971 In 2015 And 527 In 2014
12804   Accounts Receivable, Net Of Allowances Of 0 As Of December 31, 2013 And 20 As Of December 31, 2012
12807                                               Accounts Receivable, Net Of Allowance Of 542 And 1,033
12846                             Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 96 And 12
13011  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 54 At December 31, 2016 And 55 At...
13050                                                Accounts Receivable, Net Of Allowances Of 641 And 802
13072                                     Accounts Receivable, Net Of Allowance For Bad Debts Of 15 And 24
13153                                                     Accounts Receivable, Net Of Allowances Of 17 And
13237  Accounts Receivable Net Of Allowance For Doubtful Accounts Of 4,050 At October 26, 2014 And 4,00...
13263                                            Accounts Receivable, Net Of Allowances Of 3,259 And 2,040
13295                                            Accounts Receivable, Net Of Allowance Of 10,771 And 7,959
13403                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 33 25 In 2017
13459                              Accounts Receivable, Net Of Allowances Of 28.0 In 2011 And 33.0 In 2010
13500                                           Accounts Receivable, Net Of Allowances Of 16,546 And 9,398
13735  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 129 At July 28, 2018 And 211 At J...
13737            Accounts Receivable Net Of Allowance For Doubtful Accounts Of 163 In 2012 And 131 In 2011
13774                       Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 4,267 And 3,794
13799  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 265 At July 26, 2014 And 228 At J...
13802                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 377 And 345
13829                             Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 46 And 51
14110                                Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 12 And
14166                                  Accounts Receivable Net Of Allowances: 2013 – 14,252; 2012 – 15,452
14193                          Accounts Receivable  Net Of Allowances For Doubtful Accounts Of 547 And 878
14277                                                 Accounts Receivable, Net Of Allowance Of 467 And 674
14319                                                 Accounts Receivable, Net Of Allowance Of 674 And 729
14346                                                     Accounts Receivable, Net Of Allowances Of 22 And
14445                                           Accounts Receivable, Net Of Allowances Of 6.2 2019 And 8.4
14592       Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 1,251 In 2014 And 1,195 In 2015
14649                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 35.9 And 40.6
14657                         Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 38 36 In 2011
14681  Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 211 At July 29, 2017 And 249 At J...
14717                            Accounts Receivable Net Of Allowance For Doubtful Accounts Of 389 And 488
14765           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 4.9 In 2020 And 4.4 In 2019
14768              Accounts Receivable Net Of Allowance For Doubtful Accounts Of 72 In 2022 And 62 In 2021
14816                                            Accounts Receivable, Net Of Allowances Of 1,979 And 4,958
15052                                               Accounts Receivable Net Of Allowances Of 53.2 And 49.7
15152                                            Accounts Receivable, Net Of Allowances Of 4,958 And 3,259
15177                                     Accounts Receivable, Net Of Allowance For Bad Debts Of 17 And 19
15182                 Accounts Receivable, Net Of Allowance Of 210 And 944 As Of January 31, 2015 And 2016
15210            Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 53.9 In 2016; 39.3 In 2015
15339                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 751 And 788
15348                                            Accounts Receivable, Net Of Allowances Of 4,359 And 3,451
15397                           Accounts Receivable Net Of Allowances Of 59,147 In 2020 And 52,274 In 2019
15619                           Accounts Receivable, Net Of Allowance For Doubtful Accounts Of 5.5 And 5.7
15626              Accounts Receivable And Accrued Revenues Net Of Allowances Of 5 Million 2020: 4 Million

In [32]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Less",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net of allow|Party|Parties",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Pledge|Total|Finan",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Collat|Trade|From|Other|Aff",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp|bill",case=False, regex=True, na=False)

df[mask]

                                                                                                 line_item
1984                                             Accounts Receivable, Less Allowance For Doubtul Accounts:
2423                                              Accounts Receivable Less Allowance For Doubtful Accounts
2474   Accounts Receivable, Less Allowance For Doubtful Accounts 397 At December 31, 2011 And 352 At De...
2739                                   Accounts Receivable, Less Allowance Of 0 In 2011 And 10,160 In 2010
2831        Accounts Receivable, Less Allowance For Doubtful Accounts Of 18,330 In 2014 And 20,367 In 2013
3013                          Accounts Receivable, Less Allowances: 2011  19.0 Million; 2010  27.6 Million
3210                                                   Accounts Receivable, Less Allowances Of 3.1 And 2.9
3388    Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 6,923 In 2016; 3,018 In 2015
3394                                                 Accounts Receivable, Less Allowance Of 131 88 In 2019
3569                                              Accounts Receivable And Accrued Revenue, Less Allowances
3581              Accounts Receivable, Less Allowance For Doubtful Accounts Of 789 In 2011 And 723 In 2010
3611          Accounts Receivable, Less Allowance For Doubtful Accounts Of 7,820 In 2015 And 7,119 In 2014
3720   Accounts Receivable, Less Allowance For Doubtful Accounts Of 4,720 As Of June 26, 2011 And 10,60...
3859        Accounts Receivable, Less Allowance For Doubtful Accounts Of 26,694 In 2014 And 45,350 In 2013
3873   Accounts Receivable Less Allowance For Losses And Sales Adjustments Of 5,738 In 2019 And 4,647 I...
4211                                                  Accounts Receivable, Less Allowance Of 88 64 In 2018
4553                                       Accounts Receivable, Less Allowances 2016  25,874; 2015  17,486
4636                             Accounts Receivable, Less Allowance For Doubtful Accounts: 2011-227; 2010
4682                                            Accounts Receivable Less Allowances Of 7,213 5,117 In 2016
4711            Accounts Receivable, Less Allowance For Doubtful Accounts Of 1,166 In 2012 And 789 In 2011
5005       Accounts Receivable, Less Allowance For Doubtful Accounts Of 54,010 In 2011 And 44,599, In 2010
5065                                   Accounts Receivable, Less Allowances Of 4.2 In 2019 And 3.6 In 2018
5198   Accounts Receivable, Less Allowance For Bad Debts Of 10,835 At January 3, 2015 And 2,241 At Dece...
5386                                                 Accounts Receivable, Less Allowances Of 22.0 And 19.3
5413                                            Accounts Receivable Less Allowances Of 10,892 2011  11,524
5422        Accounts Receivable, Less Allowance Of 5,255 As Of June 27, 2021 And 5,465 As Of June 28, 2020
5463                                            Accounts Receivable Less Allowances Of 14,236 2015  13,244
5637                                                   Accounts Receivable, Less Allowances Of 3.5 And 5.5
5746   Accounts Receivable, Less Allowance For Bad Debts Of 8,090 At December 31, 2016 And 9,732 At Jan...
5816        Accounts Receivable, Less Allowance For Doubtful Accounts Of 23,700 In 2011 And 31,200 In 2010
5897              Accounts Receivable Less Allowance For Doubtful Accounts Of 7,734 In 2014; 8,398 In 2013
5957                                             Accounts Receivable, Less Allowances Of 14,000 And 12,700
6059   Accounts Receivable, Less Allowance For Bad Debts Of 10,815 At January 2, 2021 And 8,802 At Dece...
6135                          Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,488 And 4,988
6215                                            Accounts Receivable Less Allowances Of 1,465 1,581 In 2010
6307      Accounts Receivable  Customers, Less Allowance For Uncollectible Accounts Of 87 In 2013 And 2012
6390                                            Accounts Receivable Less Allowances Of 2,721 1,465 In 2011
6478                          Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,559 And 4,994
6520                                                     Accounts Receivable, Less Allowances Of 30 And 29
6649                  Accounts Receivable Less Allowance For Doubtful Accounts Of 898 At December 31, 2017
6842   Accounts Receivable, Less Allowance For Doubtful Accounts Of 18.3 At December 31, 2014 And 18.9 ...
6995                                       Accounts Receivable, Less Allowances 2013  16,907; 2012  13,508
7020                      Accounts Receivable Less Allowance For Losses Of 4,647 In 2018 And 5,427 In 2017
7061                                            Accounts Receivable, Less Allowance Of 252,056 And 264,144
7075   Accounts Receivable, Less Allowance For Doubtful Accounts Of: March 2019  28,376; March 2018  24...
7191        Accounts Receivable, Less Allowance For Doubtful Accounts Of 30,596 In 2012 And 30,224 In 2011
7293                                                  Accounts Receivable, Less Allowance Of 64 59 In 2017
7345         Accounts Receivable, Less Allowance For Doubtful Accounts Of 7,080 In 2021 And 11,086 In 2020
7451                          Accounts Receivable, Less Allowance For Doubtful Accounts Of 8,784 And 6,118
7638                                                Accounts Receivable, Less Allowance Of 154 167 In 2021
7705                                               Accounts Receivable, Less Allowances Of 5,400 And 5,300
7826                                                  Accounts Receivable, Less Allowance Of 59 56 In 2016
7952                           Accounts Receivable, Less Allowances 2015  16.9 Million; 2014  13.7 Million
8085                                                   Accounts Receivable, Less Allowances Of 2.4 And 3.1
8199           Accounts Receivable, Less Allowance For Doubtful Accounts 13,238 In 2018 And 12,717 In 2017
8239   Accounts Receivable, Less Allowance For Bad Debts Of 2,241 At December 28, 2013 And 2,171 At Dec...
8328        Accounts Receivable, Less Allowance Of 5,606 As Of June 26, 2022 And 5,255 As Of June 27, 2021
8454   Accounts Receivable, Less Allowance For Doubtful Accounts Of: March 2020  37,099; March 2019  19...
8625                                                 Accounts Receivable, Less Allowances Of 55.5 And 65.8
8730        Accounts Receivable, Less Allowance For Doubtful Accounts Of 10,865 In 2017 And 11,056 In 2016
8827                              Accounts Receivable, Less Allowance For Doubtful Accounts Of 314 And 568
8867   Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,155 As Of June 26, 2016 And 4,890...
8940   Accounts Receivable, Less Allowance For Bad Debts Of 7,830 At December 29, 2018 And 8,045 At Dec...
9092                                       Accounts Receivable, Less Allowances 2014  19,418; 2013  16,907
9283        Accounts Receivable, Less Allowance For Doubtful Accounts Of 19,000 In 2013 And 19,600 In 2012
9581                                               Accounts Receivable, Less Allowances Of 7,000 And 3,900
9641        Accounts Receivable, Less Allowance For Doubtful Accounts Of 15,345 In 2018 And 12,858 In 2017
9850   Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,248 As Of June 24, 2012 And 4,720...
9901                                                Accounts Receivable, Less Allowance Of 167 131 In 2020
10096                                                  Accounts Receivable, Less Allowances Of 150 And 135
10411           Accounts Receivable Less Allowance For Doubtful Accounts Of 16,002 In 2019; 12,827 In 2018
10629   Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 3,018 In 2015; 5,311 In 2014
10960                     Accounts Receivable Less Allowance For Losses Of 1,725 In 2014 And 1,113 In 2013
11044  Accounts Receivable, Less Allowance For Doubtful Accounts Of 20.5 At December 31, 2012 And 22.2 ...
11062                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,326 And 5,011
11083  Accounts Receivable, Less Allowance For Doubtful Accounts Of 2,494 At December 31, 2015 And 2,27...
11133                                                  Accounts Receivable, Less Allowances Of 117 And 109
11265                                              Accounts Receivable, Less Allowances Of 4,400 And 5,300
11358                                                  Accounts Receivable, Less Allowances Of 189 And 150
11492                                                Accounts Receivable, Less Allowances Of 16.3 And 16.0
11646                                 Accounts Receivable, Less Allowances Of 12.9 In 2011 And 7.7 In 2010
11794                                                Accounts Receivable, Less Allowances Of 54.2 And 42.6
12462           Accounts Receivable, Less Allowance For Doubtful Accounts Of 65.2 In 2017 And 49.6 In 2016
12472       Accounts Receivable, Less Allowance For Doubtful Accounts Of 16,800 In 2016 And 14,900 In 2015
12524   Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 5,311 In 2014; 5,171 In 2013
12568            Accounts Receivable, Less Allowance For Doubtful Accounts 8,713 In 2014 And 6,661 In 2013
12662                                                  Accounts Receivable, Less Allowances Of 1.9 And 0.8
12725                        Accounts Receivable, Less Allowance For Doubtful Accounts, 2012—374; 2011—226
12773                                               Accounts Receivable, Less Allowance Of 6,908 And 6,315
12886                          Accounts Receivable, Less Allowances 2014  13.7 Million; 2013  10.1 Million
12971                                                                 Accounts Receivable, Less Allowances
13021                                                    Accounts Receivable, Less Allowances Of 30 And 33
13273  Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,343 As Of June 24, 2018 And 5,103...
13283  Accounts Receivable, Less Allowance For Doubtful Accounts Of 16.3 At December 31, 2015 And 18.3 ...
13352             Accounts Receivable Less Allowance For Doubtful Accounts Of 8,398 In 2013; 8,654 In 2012
13550                                           Accounts Receivable Less Allowances Of 13,244 2014  14,728
13567                     Accounts Receivable Less Allowance For Losses Of 3,396 In 2016 And 1,640 In 2015
13633       Accounts Receivable, Less Allowance For Doubtful Accounts Of 15,283 In 2015 And 23,992 In 2014
13746                                              Accounts Receivable, Less Allowances Of 3,900 And 4,400
13749   Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 8,226 In 2017; 6,923 In 2016
13897                                  Accounts Receivable, Less Allowances Of 7.2 In 2016 And 6.5 In 2015
13900                         Accounts Receivable, Less Allowances: 2012  12.1 Million; 2011  19.0 Million
13948                                                  Accounts Receivable, Less Allowances Of 5.5 And 3.7
13953                                           Accounts Receivable Less Allowances Of 2,658 4,350 In 2020
14206         Accounts Receivable, Less Allowance For Doubtful Accounts Of 7,119 In 2014 And 8,695 In 2013
14412           Accounts Receivable Less Allowance For Doubtful Accounts Of 14,779 In 2020; 16,002 In 2019
14438             Accounts Receivable Less Allowance For Doubtful Accounts Of 7,299 In 2015; 7,858 In 2014
14441  Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 16,371 In 2011; 18,335 In ...
14450                                                Accounts Receivable, Less Allowances Of 74.1 And 54.1
14494                                                 Accounts Receivable, Less Allowance Of 61 59 In 2014
14527  Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,465 As Of June 28, 2020 And 5,021...
14548                                  Accounts Receivable, Less Allowances Of 3.6 In 2018 And 3.1 In 2017
14652                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 4,846 And 4,106
14729                          Accounts Receivable, Less Allowances 2017  20.3 Million; 2016  20.2 Million
14823                       Accounts Receivable Less Allowance For Losses Of 990 In 2011 And 1,603 In 2010
14831                                              Accounts Receivable And Accrued Revenue, Less Allowance
14838                                              Accounts Receivable, Less Allowances Of 5,500 And 5,600
14926                          Accounts Receivable, Less Allowances 2018  21.9 Million; 2017  20.3 Million
14943       Accounts Receivable, Less Allowance For Doubtful Accounts Of 14,669 In 2016 And 13,805 In 2015
15025                                                  Accounts Receivable, Less Allowances Of 135 And 102
15095                          Accounts Receivable, Less Allowances 2016  20.2 Million; 2015  16.9 Million
15192                                              Accounts Receivable, Less Allowances Of 6,600 And 5,500
15194  Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,448 As Of June 30, 2013 And 5,248...
15214                                Accounts Receivable, Less Allowances Of 14.4 In 2022 And 16.8 In 2021
15215                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 4,994 And 2,719
15334          Accounts Receivable, Less Allowance For Doubtful Accounts 12,717 In 2017 And 12,040 In 2016
15481   Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 8,648 In 2018; 7,780 In 2017
15536                            Accounts Receivable Less Provision For Doubtful Accounts: 6,239 And 6,861
15561                                                 Accounts Receivable, Less Allowance Of 72 58 In 2012
15638                                                Accounts Receivable, Less Allowances Of 17.0 And 16.3
15668         Accounts Receivable, Less Allowance For Doubtful Accounts Of 9,247 In 2016 And 7,820 In 2015
15672  Accounts Receivable, Less Allowance For Bad Debts Of 8,802 At December 28, 2019 And 7,830 At Dec...
15806  Accounts Receivable, Less Allowance For Doubtful Accounts Of 2,275 At December 31, 2014 And 2,65...
15810        Accounts Receivable, Less Allowance For Doubtful Accounts Of 17,200 In 2019 And 9,100 In 2018
16025                                                                  Accounts Receivable Less Allowances
16038                                           Accounts Receivable, Less Allowances Of 70,790 And 117,695
16048            Accounts Receivable, Less Allowance For Doubtful Accounts 6,661 In 2013 And 6,447 In 2012
16092                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,488 And 4,846
16148                                           Accounts Receivable, Less Allowance Of 245,122 And 250,343
16244          Accounts Receivable, Less Allowance For Doubtful Accounts 14,417 In 2019 And 13,238 In 2018
16324  Accounts Receivable Less Allowance For Losses And Sales Adjustments Of 12,086 In 2021 And 9,255 ...
16519                                  Accounts Receivable, Less Allowances Of 7.5 In 2020 And 4.2 In 2019
16625       Accounts Receivable, Less Allowance For Doubtful Accounts Of 13,367 In 2016 And 15,283 In 2015
16681            Accounts Receivable, Less Allowance For Doubtful Accounts 9,637 In 2015 And 8,713 In 2014
16692  Accounts Receivable, Less Allowance For Doubtful Accounts Of 2,658 At December 31, 2013 And 1,16...
16808                                           Accounts Receivable Less Allowances Of 4,571 2,658 In 2021
16827           Accounts Receivable, Less Allowance For Doubtful Accounts Of 43.3 In 2021 And 56.2 In 2020
16834                                                   Accounts Receivable, Less Allowances Of 109 And 77
16936        Accounts Receivable, Less Allowance For Doubtful Accounts Of 9,383 In 2012 And 10,381 In 2011
17031                                                Accounts Receivable, Less Allowances Of 86.7 And 22.0
17608                                            Accounts Receivable, Less Allowances Of 25,388 And 22,623
17655                                Accounts Receivable, Less Allowances Of 10.5 In 2012 And 12.9 In 2011
17961                                              Accounts Receivable, Less Allowances Of 8,100 And 6,300
17976                                                  Accounts Receivable, Less Allowances Of 1.0 And 1.9
18333                                           Accounts Receivable Less Allowances Of 8,387 2,284 In 2018
18360                     Accounts Receivable Less Allowance For Losses Of 1,113 In 2013 And 1,621 In 2012
18390  Accounts Receivable Less Allowance For Losses And Sales Adjustments Of 9,255 In 2020 And 5,738 I...
18494       Accounts Receivable, Less Allowance For Doubtful Accounts Of 20,367 In 2013 And 20,582 In 2012
18506       Accounts Receivable, Less Allowance For Doubtful Accounts Of 48,998 In 2012 And 54,010 In 2011
18680                            Accounts Receivable  Customers, Less Allowance For Uncollectible Accounts
18835       Accounts Receivable, Less Allowance For Doubtful Accounts Of 15,900 In 2014 And 19,000 In 2013
18944                                           Accounts Receivable, Less Allowance Of 237,143 And 245,122
18994                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 4,988 And 5,326
19083                                                    Accounts Receivable, Less Allowances Of 33 And 67
19131       Accounts Receivable, Less Allowance For Doubtful Accounts Of 19,443 In 2012 And 18,905 In 2011
19342             Accounts Receivable Less Allowance For Doubtful Accounts Of 7,768 In 2016; 7,299 In 2015
19538                                Accounts Receivable Less Provision For Doubtful Accounts: 605 And 321
19540       Accounts Receivable, Less Allowance For Doubtful Accounts Of 22,329 In 2015 And 19,083 In 2014
19680                                                Accounts Receivable, Less Allowances Of 67.4 And 39.2
19815                                                  Accounts Receivable, Less Allowances Of 2.9 And 2.1
19961                                             Accounts Receivable, Less Allowances Of 10,400 And 8,100
20205         Accounts Receivable, Less Allowance For Doubtful Accounts Of 6,403 In 2011 And 8,349 In 2010
20340                                                   Accounts Receivable, Less Allowance Of 114 And 191
20527       Accounts Receivable, Less Allowance For Doubtful Accounts Of 19,600 In 2012 And 23,700 In 2011
20570                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 7,111 And 5,559
20642                         Accounts Receivable, Less Allowances: 2019  18.1 Million; 2018  21.9 Million
20773   Accounts Receivable Less Accumulated Provision For Doubtful Accounts: 5,171 In 2013; 5,883 In 2012
20956                            Accounts Receivable Less Provision For Doubtful Accounts: 6,861 And 8,648
20966  Accounts Receivable, Less Allowance For Doubtful Accounts Of 5,103 As Of June 25, 2017 And 5,155...
21104                 Accounts Receivable And Accrued Revenue, Less Allowance Of 29 In 2020 And 20 In 2019
21142                                           Accounts Receivable Less Allowances Of 2,284 7,213 In 2017
21174         Accounts Receivable, Less Allowance For Doubtful Accounts Of 8,695 In 2013 And 8,482 In 2012
21204                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 3,004 And 8,784
21233                         Accounts Receivable, Less Allowance For Doubtful Accounts Of 2,494 And 2,374
21366  Accounts Receivable, Less Allowance For Bad Debts Of 2,171 At December 29, 2012 And 2,241 At Dec...

In [33]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net|Allow",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Interest|Carrying",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Less|Sec|No Allow|Non[- ]?Current",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net of allow|Party|Parties|Invest",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Pledge|Total|FinanInvest|Abstract",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Collat|Trade|From|Other|Aff|Long",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp|bill|Fina|Accru",case=False, regex=True, na=False)

df[mask]

                                   line_item
2157                    Accounts Receivable:
2272                     Accounts Receivable
15187                   Accounts Receivables
15373                    Accounts Receivable
20944  Accounts Receivable  Antero Resources

In [34]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"No Allow",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Less|Sec|Non[- ]?Current",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net of allow|Party|Parties",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Pledge|Total|FinanInvest|Abstract",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Collat|Trade|From|Other|Aff",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp|bill",case=False, regex=True, na=False)
df[mask]

                                                 line_item
4015   Accounts Receivable, No Allowance For 2021 And 2020
14643  Accounts Receivable, No Allowance For 2020 And 2019
15525  Accounts Receivable, No Allowance For 2017 And 2016
19182  Accounts Receivable, No Allowance For 2022 And 2021
26431  Accounts Receivable, No Allowance For 2019 And 2018
26946  Accounts Receivable, No Allowance For 2018 And 2017
31119  Accounts Receivable, No Allowance For 2016 And 2015

In [35]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Non|Long",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Interest",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Less|Sec|No Allow",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net of allow|Party|Parties|Invest",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Pledge|Total|FinanInvest|Abstract",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Collat|Trade|From|Other|Aff",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp|bill|Fina|Accru",case=False, regex=True, na=False)

df[mask]

                                    line_item
5110         Accounts Receivable, Non-Current
8533   Accounts Receivable, Long-Term Portion
12146          Accounts Receivable, Long-Term

In [36]:
mask = df['line_item'].str.contains(r"^Accounts Rec",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Current|Short",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Interest",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Less|Sec|No Allow|Non",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net of allow|Party|Parties|Invest",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Pledge|Total|FinanInvest|Abstract",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Collat|Trade|From|Other|Aff",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Reser|Vies|Cred|Resp|bill|Fina|Accru",case=False, regex=True, na=False)

df[mask]

                                     line_item
9433         Accounts Receivable, Net, Current
17051  Accounts Receivable, Allowance, Current

### Accounts Payable

In [37]:
mask = df['line_item'].str.contains(r"^Accounts Payable",case=False, regex=True, na=False) & \
           df['line_item'].str.contains(r"Current",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Affiliat|Party|Parties|Subsid",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Cost|Entit|Interest",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Merchant|Invest|Secu|Proj|Equip",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Other|To|Trade|Finan|Client",case=True, regex=True, na=False)
df[mask]

                                               line_item
12021                          Accounts Payable  Current
15851  Accounts Payable And Accrued Liabilities, Current
27792                          Accounts Payable, Current

In [38]:
mask = df['line_item'].str.contains(r"^Accounts Payable",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Current|Abstract",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Affiliat|Party|Parties|Subsid",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Cost|Entit|Interest",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Merchant|Invest|Secu|Proj|Equip",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Other|To|Trade|Finan|Client",case=True, regex=True, na=False)
df[mask]

                                                                                                 line_item
733                                                                                       Accounts Payable
735                                                                                      Accounts Payable:
2073                                                             Accounts Payable And Accrued Liabilities:
2536       Accounts Payable, Including Book Overdrafts Of 35,827 And 42,053 In 2013 And 2012, Respectively
2550                                                                           Accounts Payable And Drafts
2772       Accounts Payable, Including Book Overdrafts Of 48,380 And 63,594 In 2011 And 2010, Respectively
3458                                                                                 Accounts Payable Note
3462                                       Accounts Payable, Construction Payables And Accrued Liabilities
5932       Accounts Payable, Including Book Overdrafts Of 72,800 And 99,690 In 2017 And 2016, Respectively
7047                                                               Accounts Payable Derivative Instruments
7271                                                            Accounts Payable And Accrued Expenses Note
7801                                          Accounts Payable And Accrued Expenses Includes Restructuring
10594      Accounts Payable, Including Book Overdrafts Of 60,547 And 32,586 In 2015 And 2014, Respectively
11356  Accounts Payable, Including Book Overdrafts Of 51,827 And 54,381 At December 31, 2019 And 2018, ...
11622  Accounts Payable, Including Book Overdrafts Of 87,578 And 87,462 At December 31, 2022 And 2021, ...
11760                                                      Accounts Payable And Accrued Liabilities...Note
12799                                                 Accounts Payable, Notes Payable And Accrued Expenses
12891      Accounts Payable, Including Book Overdrafts Of 99,690 And 60,547 In 2016 And 2015, Respectively
13102                                                                   Accounts Payable  Antero Resources
15547  Accounts Payable, Including Book Overdrafts Of 84,505 And 51,827 At December 31, 2020 And 2019, ...
16146                                                                                    Accounts Payable:
16919                                                    Accounts Payable And Accrued Liabilities See Note
18044      Accounts Payable, Including Book Overdrafts Of 42,053 And 48,380 In 2012 And 2011, Respectively
18826                                                Accounts Payable Hep: 27,199 And 28,954, Respectively
19829                                                                                     Accounts Payable
22372  Accounts Payable, Including Book Overdrafts Of 87,462 And 84,505 At December 31, 2021 And 2020, ...
23798                                                        Accounts Payable And Accrued Liabilities Note
24066                                                     Accounts Payable Mplx: 621 And 541, Respectively
26007                                                             Accounts Payable And Accrued Liabilities
27686                                                                 Accounts Payable And Book Overdrafts
30510                                                     Accounts Payable Mplx: 506 And 449, Respectively
30639      Accounts Payable, Including Book Overdrafts Of 54,381 And 72,800 In 2018 And 2017, Respectively
30783      Accounts Payable, Including Book Overdrafts Of 32,586 And 35,827 In 2014 And 2013, Respectively
31699                                                                Accounts Payable And Accrued Expenses

### Total Long-Term Debt

In [39]:
mask = df['line_item'].str.contains(r"Debt",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Long",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Total",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Lease",case=False, regex=True, na=False)
df[mask]

                                          line_item
2602   Total Long-Term Debt Less Current Maturities
2788   Total Long-Term Debt Excluding Held For Sale
6641     Total Long-Term Debt, Less Current Portion
13024                     Total Long-Term Debt, Net
19005   Total Long-Term Debt Net Of Current Portion
26670                          Total Long-Term Debt
29387              Total Medium- And Long-Term Debt

### Long-Term Debt

In [40]:
mask = df['line_item'].str.contains(r"Debt",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Long",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Current",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Intercompany|Party|Convert|Abstract",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"To|Due Within|Fin|Bank|Hedg",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Inv|Sec|Mark|Payable Within",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Other|Subord|Mort|Affil|Vie",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Total|Short|Interest|Mat",case=True, regex=True, na=False)
         
df[mask]

                                                                                                 line_item
464                                                     Long-Term Debt And Right-Of-Use Lease Liabilities:
1243                                                                                       Long-Term Debt:
1870                                                                                        Long-Term Debt
2057                                                                Long-Term Debt Excluding Notes Payable
2192                                                                    Long-Term Debt Due After One Year:
2801                                                                                   Long-Term Debt Note
2940                                      Long-Term Debt Includes 49,161 And 46,239 Measured At Fair Value
3879                                                                                Long-Term Debt Note 10
4219                                      Long-Term Debt Includes 32,200 And 34,975 Measured At Fair Value
4624                                 Long-Term Debt, Less Debt Issuance Costs And Discounts Of 239 And 157
4807                                               Long-Term Debt Included 72,281 And 74,934 At Fair Value
4871                                               Long-Term Debt Included 33,065 And 30,226 At Fair Value
4921                                      Long-Term Debt Includes 30,097 And 36,404 Measured At Fair Value
5431                                                    Long-Term Debt Includes 359 And 347, At Fair Value
5483                                                    Long-Term Debt Includes 400 And 387, At Fair Value
5684                                                                                        Long Term Debt
5890                                                           Long-Term Debt And Capital Lease Obligation
6089                                               Long-Term Debt Included 28,878 And 30,788 At Fair Value
6547                                                                                       Debt  Long-Term
6686                                                                             Noncurrent Long-Term Debt
7201                                                    Long-Term Debt Mplx: 6,945 And 4,422, Respectively
7216                                                                               Long-Term Debt See Note
7351                                   Long-Term Debt Estimated Fair Value: 2021—1,667,009; 2020—1,871,754
7460                                   Long-Term Debt Estimated Fair Value: 2014-1,148,749; 2013-1,131,391
7933                                   Long-Term Debt Estimated Fair Value: 2020—1,871,754; 2019—1,473,364
8634                                                    Long-Term Debt Mplx: 4,422 And 5,255, Respectively
8661                                      Long-Term Debt Includes 27,637 And 31,786 Measured At Fair Value
9157                                      Long-Term Debt Includes 30,037 And 30,097 Measured At Fair Value
9309                                                          Long-Term Debt And Capital Lease Obligations
9328                                                             Long-Term Debt, Less Unamortized Discount
9542                                                                            Medium- And Long-Term Debt
9733       Long-Term Debt Obligation Less Unamortized Debt Issuance Costs Of 2,419 And 2,293, Respectively
10297                                  Long-Term Debt Estimated Fair Value: 2017—1,228,392; 2016—1,233,019
10686  Long-Term Debt Including 38,229 And 31,392 As Of December 31, 2018 And 2017, Respectively, At Fa...
10776                                    Long-Term Debt, Less Unamortized Discount And Debt Issuance Costs
11291                                                                            Long-Term Debt Obligation
11410     Long-Term Debt Obligations Less Unamortized Debt Issuance Costs Of 1,648 And 2,030, Respectively
11565                                    Long-Term Debt Estimated Fair Value: 2016—1,233,019; 2015—856,291
12310                                              Long-Term Debt Included 74,934 And 76,817 At Fair Value
13037                                                                    Long-Term Debt Due After One Year
13041                                                   Long-Term Debt Includes 345 And 326, At Fair Value
13434                                                                                      Long- Term Debt
14090                                                      Long-Term Debt Includes  And 400, At Fair Value
14749                                                                           Long-Term Debt Obligations
14824                                     Long-Term Debt Includes 33,070 And 29,708 Measured At Fair Value
15893                                                   Long-Term Debt Includes 321 And 345, At Fair Value
15915                                                       Long-Term Debt See Statement Of Capitalization
15982                                                                                 Long-Term Debt  Note
16012                                                                           Long-Term Debt, Noncurrent
16044                              Long-Term Debt Portion Measured At Fair Value: 2015  3,670; 2014  5,466
16086                                                Long-Term Debt Includes 1 And 0 Carried At Fair Value
16203                              Long-Term Debt Portion Measured At Fair Value: 2016  3,428; 2015  3,670
16555                                     Long-Term Debt Less Unamortized Discount And Debt Issuance Costs
16673      Long-Term Debt Obligation Less Unamortized Debt Issuance Costs Of 1,723 And 3,131, Respectively
16889      Long-Term Debt Obligation Less Unamortized Debt Issuance Costs Of 2,293 And 3,028, Respectively
16945                                              Long-Term Debt Included 54,886 And 47,519 At Fair Value
17346                                    Long-Term Debt Estimated Fair Value: 2012-1,191,320; 2011-947,142
17397  Long-Term Debt Including 82,609 And 67,063 As Of December 31, 2021 And 2020, Respectively, At Fa...
17602                                                  Long-Term Debt And Obligations Under Capital Leases
17772                                                   Long-Term Debt Includes 363 And 359, At Fair Value
17985  Long-Term Debt Including 26,254 And 25,293 As Of December 31, 2016 And December 31, 2015, Respec...
18094                                                                               Long-Term Debt Note 11
18118                                                                 Long-Term Debt And Lease Obligations
18736                                  Long-Term Debt Estimated Fair Value: 2022—1,440,277; 2021—1,667,009
18854                                      Long-Term Debt Estimated Fair Value: 2011-947,142; 2010-933,336
18902  Long-Term Debt Including 25,293 And 26,180 As Of December 31, 2015 And December 31, 2014, Respec...
19927                                                Long-Term Debt Includes 0 And 1 Carried At Fair Value
20584      Long-Term Debt Obligation Less Unamortized Debt Issuance Costs Of 2,030 And 2,419, Respectively
20709                                  Long-Term Debt Estimated Fair Value: 2013-1,360,461; 2012-1,191,320
20990                                              Long-Term Debt Included 76,817 And 75,745 At Fair Value
21086                                                     Long-Term Debt And Capitalized Lease Obligations
21392      Long-Term Debt Obligation Less Unamortized Debt Issuance Costs Of 3,028 And 1,723, Respectively
21670                                              Long-Term Debt Included 37,686 And 33,065 At Fair Value
22266                                              Long-Term Debt Included 30,226 And 28,878 At Fair Value
22613                                                   Long-Term Debt Includes 387 And 371, At Fair Value
23608                                              Long-Term Debt Includes 0 And 306 Carried At Fair Value
23821                                  Long-Term Debt Estimated Fair Value: 2018—1,384,455; 2017—1,228,392
24043  Long-Term Debt Including 105,995 And 82,609 As Of December 31, 2022 And 2021, Respectively, At F...
24298                              Long-Term Debt Portion Measured At Fair Value: 2014  5,466; 2013  6,747
24349                                                                                       Long-Term Debt
24605                              Long-Term Debt Portion Measured At Fair Value: 2017  2,888; 2016  3,428
25090                              Long-Term Debt Portion Measured At Fair Value: 2013  6,747; 2012  8,055
25137                                                   Long-Term Debt Includes 371 And 367, At Fair Value
25644                                     Long-Term Debt Includes 29,708 And 32,200 Measured At Fair Value
25808                                              Long-Term Debt Included 30,788 And 34,720 At Fair Value
26135                                              Long-Term Debt Included 75,745 And 54,886 At Fair Value
26419                                                                  Long-Term Debt And Lease Obligation
26612                                                                    Long-Term Debt And Capital Leases
26657                                                           Long-Term Debt / Revolving Credit Facility
26693                                     Long-Term Debt Includes 36,404 And 47,035 Measured At Fair Value
26904                                Long-Term Debt, Less Debt Issuance Costs And Discounts Of 301 And 248
27013  Long-Term Debt Includes 1,583,828 And 1,843,598 At Fair Value At November 30, 2022 And 2021, Res...
27431                                    Long-Term Debt Estimated Fair Value: 2015–856,291; 2014–1,148,749
27545                                                   Long-Term Debt Includes 367 And 363, At Fair Value
27557  Long-Term Debt Including 67,063 And 55,783 As Of December 31, 2020 And 2019, Respectively, At Fa...
27575                              Long-Term Debt Portion Measured At Fair Value: 2019  2,062; 2018  2,213
27839                                     Long-Term Debt Includes 34,975 And 27,689 Measured At Fair Value
27854                             Long-Term Debt Portion Measured At Fair Value: 2012  8,055; 2011  10,766
28002                                                                 Unsecured Long-Term Debt, Noncurrent
28411                                Long-Term Debt, Less Debt Issuance Costs And Discounts Of 236 And 239
28942                                                   Long-Term Debt Includes 326 And 269, At Fair Value
29033                                     Long-Term Debt Includes 47,035 And 49,161 Measured At Fair Value
29110                                     Long-Term Debt Includes 31,786 And 30,037 Measured At Fair Value
29928                                                                                         Longtermdebt
30118                                            Long-Term Debt Hep: 1,556,334 And 1,333,049, Respectively
30276                               Long-Term Debt, Revolving Loan Facility, And Capital Lease Obligations
30390                                Long-Term Debt, Less Debt Issuance Costs And Discounts Of 248 And 236
30434                              Long-Term Debt Portion Measured At Fair Value: 2018  2,213; 2017  2,888
30518  Long-Term Debt Including 55,783 And 38,229 As Of December 31, 2019 And 2018, Respectively, At Fa...
30717                                              Long-Term Debt Included 47,519 And 37,686 At Fair Value
30965  Long-Term Debt Including 31,392 And 26,254 As Of December 31, 2017 And December 31, 2016, Respec...
31335                                              Long-Term Debt Included 34,720 And 38,839 At Fair Value
32008                                                                               Long-Term Indebtedness

In [41]:
mask = df['line_item'].str.contains(r"Debt",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Long",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Current",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Intercompany|Party|Convert|Abstract",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"To|Due Within|Fin|Bank|Hedg",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Inv|Sec|Mark|Payable Within",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Other|Subord|Mort|Affil|Vie",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Total|Short|Interest|Mat",case=True, regex=True, na=False)
         
df[mask]

                                                                                                 line_item
1642                                                                                  Long-Term Debt, Net:
4801                                      Long-Term Debt, Net Of Premium, Discount And Debt Issuance Costs
5945                                           Long-Term Debt, Less Net Debt Issuance Costs Of 157 And 164
7476                                                                                    Long-Term Debt—Net
7645                                                                        Long-Term Portion Of Debt, Net
8498                                                                                   Long-Term Debt, Net
11469                Long-Term Debt, Net Of Discount Of 175,908 And 178,427 In 2011 And 2010, Respectively
12008                                                                      Long-Term Debt, Net Of Discount
12208           Long-Term Debt Net Of Unamortized Discount And Debt Issuance Costs: 35 In 2017, 41 In 2016
13358             Long-Term Debt, Net, Including 1,445,775 And 0 Measured At Fair Value, Respectively Note
13656                                          Long-Term Debt, Less Net Debt Issuance Costs Of 164 And 170
14224                                        Long-Term Obligations, Net Of Unamortized Debt Issuance Costs
14759                Long-Term Debt, Net Of Discount Of 182,213 And 175,908 In 2012 And 2011, Respectively
14856              Long-Term Debt, Revolving Loan Facility, And Capital Lease Obligations, Net Of Discount
16414              Long-Term Debt, Net, Including Zero And 1,403 Measured At Fair Value, Respectively Note
16560                                  Long-Term Debt, Net Of Unamortized Discount And Debt Issuance Costs
16891                                          Long-Term Debt, Less Net Debt Issuance Costs Of 167 And 219
19118                                                               Long-Term Debt, Net And Capital Leases
20183                                                                                  Long-Term Debt  Net
20345  Long-Term Borrowings, Net Of Unamortized Debt Issuance Cost Of 19,525 And 22,812 At December 31,...
20380                                          Long-Term Debt, Less Net Debt Issuance Costs Of 170 And 167
27333                                                                             Long-Term Debt, Net Note
28222                                                      Long-Term Debt-Related Parties, Net Of Discount
29404                                                                          Long-Term Debt, Net Note 10
31187                Long-Term Debt, Net Of Discount Of 174,686 And 183,644 In 2013 And 2012, Respectively
31850             Long-Term Debt, Net, Including 1,403 And 1,446 Measured At Fair Value, Respectively Note
31893           Long-Term Debt Net Of Unamortized Discount And Debt Issuance Costs: 41 In 2016, 42 In 2015

### Short-Term Debt

In [42]:
mask = df['line_item'].str.contains(r"Debt",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Short",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Interest|Long|Total|Part|Aff|Carr",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Mort|Conver|Mat|Sub|Fin|Inv|Sec",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Note|Intercompany|Current|Other",case=False, regex=True, na=False)

df[mask]

                                                                                       line_item
1505                                                                            Short-Term Debt:
3954                                                                       Short-Term Debt R And
6885                                                                            Debt  Short-Term
9693                                                                       Short-Term Debt I And
17866                                                                       Short-Term Debt, Net
21459                                                                            Short-Term Debt
21495  Short-Term Debt Net Of Unamortized Discount And Debt Issuance Costs: 3 In 2016, 1 In 2015
23516                                              Short-Term Debt And Capital Lease Obligations
24374                                                                            Short Term Debt
26064                                                                      Short-Term Debt P And
28120  Short-Term Debt Net Of Unamortized Discount And Debt Issuance Costs: 2 In 2017, 3 In 2016
31945                                                                Short-Term Debt Obligations

In [43]:
mask = df['line_item'].str.contains(r"Borrow",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Short",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Due|Under|Unsec",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Interest|Long|Total|Part|Aff|Carr",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Mort|Conver|Mat|Sub|Fin|Inv|Sec",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Note|Intercompany|Current|Other",case=False, regex=True, na=False)

df[mask]

                                                                                                 line_item
281                                                                                  Short-Term Borrowings
1858                                                                                Short-Term Borrowings:
3450   Short-Term Borrowings Including 4,627 And 2,700 As Of December 31, 2017 And December 31, 2016, R...
4466                                 Short-Term Borrowings Includes 2,024 And 1,325 Measured At Fair Value
4949   Short-Term Borrowings Including 1,496 And 3,692 As Of December 31, 2014 And December 31, 2013, R...
5594                                 Short-Term Borrowings Includes 1,648 And 1,494 Measured At Fair Value
7159                                 Short-Term Borrowings Includes 1,494 And 2,024 Measured At Fair Value
8151                           Short-Term Borrowings Including 1,731 And 1,115 At Fair Value, Respectively
10026                                                                                Short Term Borrowings
11191                          Short-Term Borrowings Including 1,551 And 1,731 At Fair Value, Respectively
11915  Short-Term Borrowings Including 4,683 And 4,946 As Of December 31, 2020 And 2019, Respectively, ...
12959                                  Short-Term Borrowings Includes 832 And 4,279 Measured At Fair Value
13599                                       Short-Term Borrowings Included 15,792 And 20,015 At Fair Value
14879                                                                            Short-Term Borrowings K &
16605                                         Short-Term Borrowings Included 5,920 And 7,130 At Fair Value
17550  Short-Term Borrowings Including 6,222 And 7,358 As Of December 31, 2022 And 2021, Respectively, ...
17792                                           Short-Term Borrowings Includes 406 And 1,648 At Fair Value
18148  Short-Term Borrowings Including 1,207 And 1,496 As Of December 31, 2015 And December 31, 2014, R...
18174                                                                  Short-Term Borrowings Assumed By Ge
19285  Short-Term Borrowings Including 7,358 And 4,683 As Of December 31, 2021 And 2020, Respectively, ...
20000                          Short-Term Borrowings Including 1,115 And 1,074 At Fair Value, Respectively
20265  Short-Term Borrowings Including 4,946 And 4,483 As Of December 31, 2019 And 2018, Respectively, ...
21064                                         Short-Term Borrowings Included 7,130 And 9,191 At Fair Value
21078                                Short-Term Borrowings Includes 5,874 And 3,941 Measured At Fair Value
21884                                Short-Term Borrowings Includes 1,325 And 2,697 Measured At Fair Value
22022  Short-Term Borrowings Including 4,483 And 4,627 As Of December 31, 2018 And 2017, Respectively, ...
22458                                         Short-Term Borrowings Included 9,191 And 9,105 At Fair Value
23565                                Short-Term Borrowings Includes 4,279 And 5,874 Measured At Fair Value
24976                                                                                Short-Term Borrowings
25008                                Short-Term Borrowings Includes 1,520 And 4,074 Measured At Fair Value
25518  Short-Term Borrowings Includes 1,648 And 1,765 At Fair Value At December 31, 2015 And December 3...
26264                                        Short-Term Borrowings Included 16,893 And 5,920 At Fair Value
26555  Short-Term Borrowings Including 2,700 And 1,207 As Of December 31, 2016 And December 31, 2015, R...
26722                                Short-Term Borrowings Includes 3,941 And 1,648 Measured At Fair Value
26823                                                                            Short-Term Borrowed Funds
27283                                Short-Term Borrowings Includes 2,697 And 1,520 Measured At Fair Value
27913                                                                          Short-Term Borrowings J And
28092                                       Short-Term Borrowings Included 20,015 And 16,893 At Fair Value
29491                                                                     Short-Term Borrowings From Banks

In [44]:
mask = df['line_item'].str.contains(r"Borrow",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Short",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Unsec",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Due|Under",case=False, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Interest|Long|Total|Part|Aff|Carr",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Mort|Conver|Mat|Sub|Fin|Inv",case=True, regex=True, na=False) & \
          ~df['line_item'].str.contains(r"Note|Intercompany|Current|Other",case=False, regex=True, na=False)

df[mask]

                                                                      line_item
6811   Unsecured Short-Term Borrowings Includes 26,007 And 16,963 At Fair Value
18182  Unsecured Short-Term Borrowings Includes 26,750 And 26,007 At Fair Value
20261  Unsecured Short-Term Borrowings Includes 39,731 And 29,832 At Fair Value
23252  Unsecured Short-Term Borrowings Includes 16,963 And 16,904 At Fair Value
25362  Unsecured Short-Term Borrowings Includes 16,904 And 14,792 At Fair Value
26262  Unsecured Short-Term Borrowings Includes 29,832 And 26,750 At Fair Value

### Retained Earnings

In [45]:
mask = df['line_item'].str.contains(r"Earnings$",case=False, regex=True, na=False) & \
          df['line_item'].str.contains(r"Retained",case=False, regex=True, na=False) & \
        ~ df['line_item'].str.contains(r"Dist|Appropriated|Capital",case=False, regex=True, na=False)
         
df[mask]

                                       line_item
3952   -Accumulated Deficits / Retained Earnings
4325                   Retained Deficit Earnings
6879     Accumulated Earnings/ Retained Earnings
11470                  Retained Deficit/Earnings
12217                     Retained Loss Earnings
12635     -Accumulated Deficit/Retained Earnings
14651                          Retained Earnings
16636   -Accumulated Deficit / Retained Earnings
16768                         —Retained Earnings
18571     -Accumulated Deficit Retained Earnings

### Intangible Assets

In [46]:
mask = df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Goodwill|other|brand|acquired",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Liabil",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Acquisition|Not Subject|Amort",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Total|Purchase|Lease",case=False, regex=True, na=False)
df[mask].reset_index()

,index,line_item
0,1987,Intangible Assets:
1,2354,Intangible Assets
2,3890,"Intangible Assets, Net Variable Interest Entity Restricted 2017: 25; 2016: 26"
3,4107,"Intangible Assets, Net Of 217,705 And 169,329, Respectively"
4,5282,"Intangible Assets Including Msrs Of 665 And 404 As Of December 31, 2022 And 2021, Respectively, ..."
5,5830,Intangibles Net
6,6748,"Intangible Assets, Net Variable Interest Entity Restricted 2019: 22; 2018: 23"
7,7979,"Intangible Assets, Net Variable Interest Entity Restricted 2015: 27; 2014:"
8,9147,Intangibles – Net
9,12518,"Intangibles, Net"
10,13218,Intangible Assets – Net
11,14036,Intangible Lng Assets
12,16707,"Intangibles, Including Dac And Voba, Net"
13,18377,"Intangible Assets, Net Variable Interest Entity Restricted 2018: 23; 2017: 25"
14,19319,Intangible Assets Net Note
15,20545,Intangible Assets—Net
16,20671,"Intangible Asset, Net"
17,21033,Intangible Assets
18,21074,"Intangible Assets Including Msrs Of 584 And 558 As Of December 31, 2018 And 2017, Respectively, ..."
19,21827,Net Intangible Assets
20,21841,"Intangible Assets, Net Variable Interest Entity Restricted 2016: 26; 2015: 27"
21,24891,"Intangible Assets Including Msrs Of 336 And 495 As Of December 31, 2020 And 2019, Respectively, ..."
22,25890,Intangibles Note
23,26077,Intangible Assets Net
24,26777,"Intangibles Assets, Net"
25,28374,"Intangible Assets Including Msrs Of 404 And 336 As Of December 31, 2021 And 2020, Respectively, ..."
26,28916,"Intangible Assets Including Msrs Of 495 And 584 As Of December 31, 2019 And 2018, Respectively, ..."
27,29332,Intangible Assets-Net Note
28,30194,Intangibles-Net
29,30983,"Intangible Assets, Net"
30,31168,"Intangibles, Net Note"
31,31460,"Intangible Assets, Net Note"
32,31982,Intangibles

In [47]:
mask = df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Amort",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Goodwill|other|brand|acquired",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Less",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Acquisition|Not Subject",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Total|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,1416,"Intangible Assets, Net Of Amortization:"
1,2792,"Intangible Assets Net Of Accumulated Amortization Of 2,877 And 2,730"
2,2812,"Intangible Assets, Net Of Accumulated Amortization Of 265,940 And 241,731 As Of December 31, 201..."
3,3048,"Amortizable Intangible Assets, Net Of Accumulated Amortization"
4,3202,"Intangibles Net Of Accumulated Amortization Of 253,161 And 183,494 As Of December 31, 2021 And D..."
5,3219,"Intangibles, Net Of Accumulated Amortization Of 704 And 663, Respectively"
6,3627,"Intangible Assets, Net Of Accumulated Amortization Of 498.0 And 416.9"
7,4116,"Intangible Assets Net Of 289,912 And 245,160 Accumulated Amortization, Respectively"
8,4641,"Intangible Assets, Net Of Accumulated Amortization Of 817,961 And 737,694"
9,4673,"Intangible Assets Net Of Accumulated Amortization Of 185 And 244 At December 31, 2019 And 2018, ..."
10,4792,"Intangible Assets, Net Of Accumulated Amortization Of 856.5 And 817.2"
11,4815,"Intangible Assets, Net Of Accumulated Amortization Of 817.2 And 759.2"
12,4826,"Amortizable Intangibles, Net Of Accumulated Amortization Of 4,409,312 And 3,670,679"
13,4855,"Intangible Assets, Net Of Accumulated Amortization Of 109.5 And 47.4"
14,4866,"Intangible Assets Net Of Accumulated Amortization Of 4,253 And 3,819"
15,4985,"Intangible Assets Net Of Accumulated Amortization Of 3,294 And 2,932 At December 31, 2021 And 20..."
16,5642,"Intangible Assets Net Of Accumulated Amortization Of 316,099 And 255,579 At December 31, 2012 An..."
17,5688,"Intangible Assets, Net Of Accumulated Amortization Of 3,399 And 2,603"
18,5722,"Intangible Assets Net Of Accumulated Amortization Of 2,421 And 2,130"
19,5742,"Intangible Assets, Net Of Accumulated Amortization Of 151 And 122"
20,6038,"Intangible Assets, Net Of Accumulated Amortization Of 777.6 And 680.7"
21,6353,"Intangible Assets Net Of 99,198 And 50,870 Accumulated Amortization, Respectively"
22,6594,"Intangible Assets Net Of Accumulated Amortization Of 27,538 And 20,002 At December 31, 2013 And ..."
23,6764,"Intangible Assets, Net Of Accumulated Amortization Of 611.4 And 552.3"
24,6990,"Intangible Assets, Net Of Accumulated Amortization Of 455 And 405, At 2022 And 2021, Respectively."
25,7138,"Intangible Assets Net Of 50,870 And 17,815 Accumulated Amortization, Respectively"
26,7195,"Intangible Assets, Net Of Accumulated Amortization Of 322,611 And 294,449 As Of December 31, 201..."
27,7230,"Intangible Assets, Net Of Accumulated Amortization Of 7.0 Million In 2015 And 1.0 Million In 2014"
28,7339,"Intangible Assets, Net Of Accumulated Amortization Of 184 And 151"
29,7563,"Intangibles, Net Of Accumulated Amortization Of 483,773 And 304,323"
30,7631,"Intangible Assets, Net Of Accumulated Amortization Of 30,261 And 17,716"
31,7807,"Intangible Assets Net Of Accumulated Amortization Of 1,250 And 910 At December 31, 2012 And Dece..."
32,7951,"Intangible Assets Net Of Accumulated Amortization Of 1,057 And 899 At December 31, 2013 And 2012..."
33,7977,"Intangible Assets, Net Of Accumulated Amortization Of 879.9 And 777.6"
34,8010,"Intangible Assets Net Of Accumulated Amortization Of 1,040 And 1,057 At December 31, 2014 And 20..."
35,8099,"Intangible Assets, Net Of Accumulated Amortization Of 175.7 And 109.5"
36,8177,"Amortizable Intangible Assets, Net"
37,8473,"Intangibles Net Of Accumulated Amortization Of 123,408 And 110,908 As Of December 31, 2017 And D..."
38,8636,"Intangible Assets Net Of Accumulated Amortization Of 1,703 And 1,250 At December 31,2013 And Dec..."
39,8911,"Intangible Assets, Net Of Accumulated Amortization Of 582,272 And 603,637"
40,9018,"Intangible Assets, Net Of Accumulated Amortization Of 1,706 And 1,452"
41,9475,"Intangible Assets, Net Of Accumulated Amortization Of 122 And 100"
42,9648,"Intangible Assets Net Of Accumulated Amortization Of 20,002 And 25,701 At December 31, 2012 And ..."
43,9783,"Intangible Assets Net Of Accumulated Amortization Of 41,217 And 32,018 At December 31, 2018 And ..."
44,9945,"Intangible Assets, Net Of Accumulated Amortization Of 291 And 228"
45,10120,"Intangible Assets, Net Of Accumulated Amortization Of 20,611 And 17,135"
46,10146,"Intangible Assets, Net Of Accumulated Amortization Of 652,902 And 591,202"
47,10231,"Intangible Assets, Net Of Accumulated Amortization Of 4,422 And 4,347"
48,10278,"Intangible Assets Net Of Accumulated Amortization Of 541,967 And 507,612 At December 31, 2018 An..."
49,10281,"Intangibles, Net Of Accumulated Amortization Of 663 And 622, Respectively"
50,10328,"Amortizable Intangibles, Net Of Accumulated Amortization Of 5,051,149 And 4,409,312"
51,10351,"Intangible Assets Net Of Accumulated Amortization Of 899 And 751 At December 31, 2012 And 2011, ..."
52,10391,"Intangible Assets Net Of Accumulated Amortization Of 507,612 And 462,860 At December 31, 2017 An..."
53,10449,"Intangible Assets, Net Of Accumulated Amortization Of 360 And 319, At 2020 And 2019, Respectively."
54,10469,"Intangible Assets Net Of Accumulated Amortization Of 372,209 And 374,377 At December 31, 2014 An..."
55,10774,"Intangible Assets, Net Of Accumulated Amortization Of 1,525 And 1,402"
56,10865,"Intangible Assets, Net Of Accumulated Amortization Of 405 And 360, At 2021 And 2020, Respectively."
57,11109,"Intangible Assets Net Of 197,858 And 144,574 Accumulated Amortization, Respectively"
58,11250,"Intangible Assets Net Of Accumulated Amortization Of 3,265 And 3,204"
59,11704,"Intangible Assets, Net Of Accumulated Amortization Of 819.9 And 856.5"
60,11723,"Intangible Assets Net Of Accumulated Amortization Of 7,292 And 41,217 At December 31, 2019 And 2..."
61,11877,"Intangible Assets, Net Of Accumulated Amortization Of 1,452 And 1,064"
62,12003,"Intangible Assets, Net Of Accumulated Amortization Of 680.7 And 611.4"
63,12405,Intangible Assets – Net Of Accumulated Amortization
64,12809,"Intangible Assets, Net Of Accumulated Amortization Of 759.2 And 737.4"
65,12998,Intangibles Net Of Accumulated Amortization
66,13789,"Intangible Assets, Net Of Accumulated Amortization Of 237,681 At December 31, 2012 And 198,139 A..."
67,13809,"Intangible Assets Net Of Accumulated Amortization Of 745 And 1,040 At December 31, 2015 And 2014..."
68,13878,"Intangible Assets Net Of Accumulated Amortization Of 25,701 And 13,337 At December 31, 2011 And ..."
69,14041,"Intangible Assets, Net Of Accumulated Amortization Of 158.6 And 383.8"
70,14212,"Intangible Assets Net Of Accumulated Amortization Of 3,294 At December 31, 2021"
71,14272,"Intangible Assets, Net Of Accumulated Amortization Of 100 And 91"
72,14431,"Intangible Assets, Net Of Accumulated Amortization Of 198,139 At December 31, 2011 And 172,726 A..."
73,14488,"Intangibles Net Of Accumulated Amortization Of 318,013 And 253,161 As Of December 31, 2022 And D..."
74,14915,"Intangible Assets Net Of Accumulated Amortization Of 399 And 291 At December 31, 2021 And 2020, ..."
75,15072,"Intangible Assets, Net Of Accumulated Amortization Of 8,773 And 5,090"
76,15251,"Intangible Assets, Net Of Accumulated Amortization Of 1,402 And 1,977"
77,15439,"Intangibles, Net Of Accumulated Amortization Of 786 And 745, Respectively"
78,15502,"Intangible Assets, Net Of Amortization"
79,15936,"Intangible Assets, Net Of Accumulated Amortization Of 27,864 And 25,386"
80,16172,"Intangible Assets Net Of 17,815 And 20,302 Accumulated Amortization, Respectively"
81,16763,"Intangible Assets Net Of Accumulated Amortization Of 255,579 And 196,061 At December 31, 2011 An..."
82,16903,"Intangible Assets Net Of Accumulated Amortization Of 832 And 745 At December 31,2016 And 2015, R..."
83,17088,"Intangible Assets Net Of Accumulated Amortization Of 32,018 And 24,690 At December 31, 2017 And ..."
84,17347,"Intangible Assets, Net Of Accumulated Amortization Of 169,329 And 127,172, Respectively"
85,17500,"Intangibles, Net Of Accumulated Amortization"
86,17598,"Intangible Assets Net Of 20,302 And 17,238 Accumulated Amortization, Respectively"
87,17687,"Intangible Assets, Net Of Accumulated Amortization Of 14,604 And 19,900"
88,17797,"Intangible Assets Net Of Accumulated Amortization Of 2,130 And 1,824 At December 31, 2015 And De..."
89,17874,"Intangible Assets, Net Of Accumulated Amortization Of 5,090 And 1,552"
90,17951,"Intangible Assets, Net Of Accumulated Amortization Of 215,485 And 181,227 As Of December 31, 201..."
91,18186,"Intangible Assets, Net Of Accumulated Amortization Of 23,457 And 20,611"
92,18270,"Intangible Assets, Net Of Accumulated Amortization Of 247.7 And 175.7"
93,18363,"Intangible Assets Net Of Accumulated Amortization Of 21,754 And 33,735 At December 31, 2015 And ..."
94,18632,"Intangible Assets, Net Of Accumulated Amortization Of 332 And 291"
95,18671,"Intangible Assets, Net Of Accumulated Amortization Of 489,538 And 439,703"
96,18839,"Intangible Assets Net Of Accumulated Amortization Of 244 And 219 At December 31, 2018 And 2017, ..."
97,18860,"Intangible Assets, Net Of Accumulated Amortization Of 326.1 And 314.0"
98,18865,"Intangible Assets, Net Of Accumulated Amortization Of 5,124 And 4,422"
99,18877,"Intangible Assets, Net Of Accumulated Amortization Of 91 Million And 96 Million"
100,19055,"Intangibles, Net Of Accumulated Amortization Of 745 And 704, Respectively"
101,19132,"Intangible Assets Net Of Accumulated Amortization Of 462,860 And 418,512 At December 31, 2016 An..."
102,19156,"Intangible Assets Net Of Accumulated Amortization Of 483 And 399 At December 31, 2022 And 2021, ..."
103,19536,"Intangible Assets, Net Of Accumulated Amortization Of 33,050 And 30,610"
104,19768,"Intangible Assets, Net Of Accumulated Amortization Of 4,347 And 3,399"
105,19811,"Intangible Assets, Net Of Accumulated Amortization Of 17,716 And 12,456"
106,19845,"Intangible Assets, Net Of Accumulated Amortization Of 10.3 Million As Of December 31, 2017 And 9..."
107,19857,"Intangible Assets, Net Of Accumulated Amortization Of 552.3 And 498.0"
108,20063,"Intangible Assets Net Of 217,582 And 289,912 Accumulated Amortization, Respectively"
109,20064,"Intangible Assets, Net Of Accumulated Amortization Of 25,374 And 25,133"
110,20101,"Intangible Assets Net Of 245,160 And 197,858 Accumulated Amortization, Respectively"
111,20285,"Intangible Assets, Net Of Accumulated Amortization Of 12.1 Million And 10.5 Million, Respectively"
112,20721,"Intangible Assets, Net Of Accumulated Amortization Of 1,977 And 1,706"
113,20887,"Amortizable Intangibles, Net Of Accumulated Amortization Of 2,882,787 And 2,008,573"
114,21019,"Intangible Assets, Net Of Accumulated Amortization Of 294,676 And 265,940 As Of December 31, 201..."
115,21127,"Intangible Assets, Net Of Accumulated Amortization Of 1,552"
116,21234,"Intangible Assets, Net Of Accumulated Amortization Of 181,227 And 142,880 As Of December 31, 201..."
117,21500,"Intangible Assets, Net Of Accumulated Amortization Of 314.0 And 247.7"
118,22072,"Intangible Assets, Net Of Accumulated Amortization Of 294,449 And 269,868 As Of December 31, 201..."
119,22584,Amortizable Intangible Assets Net
120,22601,"Amortizable Intangibles, Net Of Accumulated Amortization Of 3,670,679 And 2,882,787"
121,22797,"Intangible Assets, Net Of Accumulated Amortization Of 737.4 And 879.9"
122,22879,"Intangible Assets, Net Of Accumulated Amortization Of 12,456 And 8,773"
123,22972,"Intangible Assets Net Of Accumulated Amortization Of 3,819 And 3,265"
124,22978,"Intangible Assets Subject To Amortization, Net Note"
125,23104,"Intangible Assets, Net Of Accumulated Amortization Of 603,637 And 546,038"
126,23587,"Intangible Assets Net Of Accumulated Amortization Of 3,204 And 2,877"
127,23735,"Intangible Assets, Net Of Accumulated Amortization Of 3,457 And 2,293"
128,23976,"Intangible Assets, Net Of 456 And 407 In Accumulated Amortization, Respectively"
129,24490,"Intangible Assets, Net Of Accumulated Amortization Of 7,044 And 693"
130,24517,"Intangible Assets, Net Of Accumulated Amortization Of 546,038 And 489,538"
131,24553,"Intangible Assets, Net Of Accumulated Amortization Of 141,572 At August 31, 2012 And 128,467 At ..."
132,24597,"Intangible Assets Net Of Accumulated Amortization Of 374,377 And 316,099 At December 31, 2013 An..."
133,24748,"Intangible Assets Net Of Accumulated Amortization Of 2,730 And 2,421"
134,24837,"Intangible Assets Net Of Accumulated Amortization Of 1,824 And 1,527 At December 31, 2014 And De..."
135,24979,"Intangible Assets Net Of Accumulated Amortization Of 418,512 And 372,209 At December 31, 2015 An..."
136,25053,"Intangible Assets, Net Of Accumulated Amortization Of 9.1 Million In 2016 And 7.0 Million In 2015"
137,25513,"Intangibles, Net Of Accumulated Amortization Of 578 And 502, Respectively"
138,25771,"Intangible Assets, Net Of Accumulated Amortization Of 416.9 And 354.8"
139,25780,"Intangible Assets, Net Of Accumulated Amortization Of 215,341 And 184,865 As Of December 31, 201..."
140,25818,"Intangibles Net Of Accumulated Amortization Of 148,644 And 123,408 As Of December 31, 2018 And D..."
141,25925,"Intangible Assets, Net Of Accumulated Amortization Of 439,703 And 411,543"
142,25958,"Intangible Assets Net Of Accumulated Amortization Of 291 And 185 At December 31, 2020 And 2019, ..."
143,26012,"Intangible Assets, Net Of Accumulated Amortization Of 22,973 And 7,044"
144,26302,"Intangible Assets, Net Of 407 And 373 In Accumulated Amortization, Respectively"
145,26426,"Intangible Assets, Net Of Accumulated Amortization Of 228 And 184"
146,26869,"Intangible Assets, Net Of Accumulated Amortization Of 297 And 228 In 2021 And 2020, Respectively"
147,27151,"Intangibles, Net Of Accumulated Amortization Of 622 And 578, Respectively"
148,28148,"Intangible Assets, Net Of Accumulated Amortization Of 96 Million And 112 Million"
149,28726,"Intangible Assets, Net Of Accumulated Amortization Of 383.8 And 326.1"
150,29153,"Intangible Assets Net Of Accumulated Amortization Of 219 And 832 At December 31, 2017 And Decemb..."
151,29585,"Intangible Assets, Net Of Accumulated Amortization Of 25,133 And 23,457"
152,29715,"Intangible Assets, Net Of Accumulated Amortization"
153,29785,"Intangible Assets Net Of Accumulated Amortization Of 24,690 And 21,754 At December 31, 2016 And ..."
154,29796,"Intangibles Net Of Accumulated Amortization Of 219,239 And 148,644 As Of December 31, 2019 And D..."
155,29934,"Intangible Assets, Net Of Accumulated Amortization Of 30,610 And 27,864"
156,30350,"Amortizable Intangibles, Net Of Accumulated Amortization Of 5,549,674 And 5,051,149, Respectively"
157,30383,"Intangible Assets Net Of Accumulated Amortization Of 2,932 And 7,292 At December 31, 2020 And 20..."
158,30631,"Intangible Assets, Net Of Accumulated Amortization Of 19,900 And 22,973"
159,31030,"Intangible Assets, Net Of Accumulated Amortization Of 128,467 At August 31, 2011 And 112,687 At ..."
160,31186,"Intangible Assets Net Of 153,635 And 99,198 Accumulated Amortization, Respectively"
161,31297,"Intangible Assets Net Of Accumulated Amortization Of 751 And 615 At December 31, 2011 And 2010, ..."
162,31332,"Intangible Assets, Net Of Accumulated Amortization Of 25,386 And 25,374"
163,31657,"Intangible Assets, Net Of Accumulated Amortization Of 411,543 And 373,706"
164,31801,"Intangibles, Net Of Accumulated Amortization Of 827 And 786, Respectively"

In [48]:
mask = df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Amort",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Goodwill|other|brand|acquired",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Less|Not Subject",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

   index                           line_item
0   1475       Amortizable Intangible Assets
1   5366       Amortizable Intangible Assets
2  11223  Amortizable Intangible Assets Note

### Acquired Intangible Assets

In [49]:
mask = df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Acqui",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Goodwill|other|brand",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Not Subject",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Total|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,465,Intangible Assets Acquired
1,3449,Acquisition-Related Intangibles
2,4992,"Acquired Intangibles, Net"
3,5544,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 185,054 And 175,210"
4,6975,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 132,927 At December 31, 2013 And ..."
5,8841,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 131,095 At December 31, 2015 And ..."
6,10011,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 204,853 At December 31, 2019 And ..."
7,10390,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 129,119 At December 31, 2011 And ..."
8,11612,"Acquisition-Related Intangible Assets, Net Of Accumulated Amortization Of 3,169.3 And 2,539.1"
9,11625,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 199,237 And 185,054"
10,12075,"Acquired Intangible Assets, Net"
11,12827,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 179,142 At December 31, 2017 And ..."
12,13697,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 140,829 At December 31, 2012 And ..."
13,14660,"Acquisition-Related Intangibles, Net"
14,15387,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 113,153 At December 31, 2014 And ..."
15,18234,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 175,210 And 204,853"
16,19237,Acquired Intangible Assets Net
17,20156,"Acquisition Related Intangible Assets, Net"
18,23529,"Acquisition-Related Intangible Assets, Net"
19,29540,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 190,920 At December 31, 2018 And ..."
20,30789,"Acquired Intangible Assets, Net Of Accumulated Amortization Of 150,347 At December 31, 2016 And ..."

### Goodwill

In [50]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Intangible|other|brand|acquired",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Beg|End|Rec",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Acquisition|Not Subject|Amort",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Total|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

   index           line_item
0  21220      Goodwill – Net
1  23248       Goodwill, Net
2  23690       Goodwill  Net
3  28067  Goodwill, Net Note

In [51]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Intangible|other|brand|acquired",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Beg|End|Rec",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Prod|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Acquisition|Not Subject|Amort",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Total|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,9509,Goodwill See Note
1,10993,"Goodwill Hep: 431,985 And 312,873, Respectively"
2,12749,Goodwill Value
3,17494,Goodwill In Dollars
4,18290,Goodwill A &
5,18446,Goodwill Note
6,24766,"Goodwill Mplx: 2,245 And 2,245, Respectively"
7,25751,Goodwill A And
8,26515,"Goodwill Mplx: 2,199 And 2,570, Respectively"
9,26895,Goodwill
10,28504,"Goodwill Less Accumulated Impairment Losses Of 957,311 In 2011 And 805,218 In 2010"
11,29797,"Goodwill Less Accumulated Impairment Losses Of 805,218 In 2012 And 2011"
12,29972,Goodwill Note
13,30573,Goodwill...Note

In [52]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Net",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Intangible",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Finite|Beg|End|Rec|Total",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Held|Trad|Dep|Ind|Ide|Ins",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Acquisition|Not Subject",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Estate|Deferred|Leasing|Customer",case=False, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"market|Purchase|Lease",case=False, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,585,Goodwill And Other Assets
1,9509,Goodwill See Note
2,10993,"Goodwill Hep: 431,985 And 312,873, Respectively"
3,11635,Goodwill Less Accumulated Amortization Of 11
4,12749,Goodwill Value
5,17494,Goodwill In Dollars
6,18290,Goodwill A &
7,18446,Goodwill Note
8,24766,"Goodwill Mplx: 2,245 And 2,245, Respectively"
9,25751,Goodwill A And
10,26515,"Goodwill Mplx: 2,199 And 2,570, Respectively"
11,26895,Goodwill
12,28504,"Goodwill Less Accumulated Impairment Losses Of 957,311 In 2011 And 805,218 In 2010"
13,29797,"Goodwill Less Accumulated Impairment Losses Of 805,218 In 2012 And 2011"
14,29972,Goodwill Note
15,30573,Goodwill...Note
16,30976,Goodwill And Other Long-Term Assets

### Intangible and Goodwill

In [53]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Net|Other",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Subsid|Eclud",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,510,Goodwill And Other Intangible Assets
1,2980,"Goodwill, Msrs And Other Intangible Assets"
2,3409,"Intangible Assets, Net And Goodwill"
3,4024,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 26,922 And 15,007 At Dec..."
4,5829,"Goodwill And Intangible Assets, Net, Total"
5,6601,"Goodwill And Intangible Assets, Net Of Accumulated Amortization"
6,6635,Intangibles Net Of Amortization And Goodwill
7,7436,"Goodwill And Other Intangibles, Net"
8,9634,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 35,281 And 26,922 At Dec..."
9,10069,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,155 And 68,305 At Dec..."
10,11279,Goodwill And Other Intangible Assets Note
11,11636,Goodwill And Other Intangibles
12,12342,Net Goodwill And Other Intangible Assets
13,12548,"Intangible Assets, Net Excluding Goodwill"
14,13198,Goodwill And Other Intangibles Net
15,13452,Goodwill And Net Intangible Assets Note
16,14134,"Goodwill And Acquisition-Related Intangible Assets, Net"
17,14789,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 57,561 And 51,754 At Dec..."
18,15746,"Goodwill And Other Intangible Assets, Less Accumulated Amortization"
19,17146,"Goodwill And Acquisition Related Intangible Assets, Net"
20,17396,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 68,305 And 65,949 At Dec..."
21,18686,"Intangible Assets Other Than Goodwill, Net"
22,20411,Goodwill And Other Indefinite-Lived Intangible Assets
23,21175,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 63,099 And 60,080 At Dec..."
24,22923,"Goodwill And Other Intangible Assets, Net"
25,24788,"Goodwill And Intangibles, Net"
26,25693,"Goodwill And Identifiable Intangible Assets, Net"
27,26013,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,221 And 70,155 At Dec..."
28,26382,"Intangible Assets, Net Including Goodwill"
29,27179,"Goodwill, Intangible Assets And Deferred Costs, Net"
30,27273,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 51,754 And 45,379 At Dec..."
31,27513,"Goodwill And Finite-Lived Intangible Assets, Net"
32,28798,"Goodwill And Other Intangible Assets, Net Note"
33,29617,"Goodwill And Intangible Assets, Net"
34,29980,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 65,949 And 63,099 At Dec..."
35,29989,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 45,379 And 35,281 At Dec..."
36,30092,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 60,080 And 57,561 At Dec..."
37,30660,Goodwill And Other Intangible Assets
38,31712,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,118 And 70,221 At Dec..."

In [54]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Other",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Excl|Amort|Subsid|Total",case=True, regex=True, na=False)

df[mask].reset_index()

    index                                              line_item
0     510                   Goodwill And Other Intangible Assets
1    2980             Goodwill, Msrs And Other Intangible Assets
2    7436                    Goodwill And Other Intangibles, Net
3   11279              Goodwill And Other Intangible Assets Note
4   11636                         Goodwill And Other Intangibles
5   12342               Net Goodwill And Other Intangible Assets
6   13198                    Goodwill And Other Intangibles  Net
7   18686             Intangible Assets Other Than Goodwill, Net
8   20411  Goodwill And Other Indefinite-Lived Intangible Assets
9   22923              Goodwill And Other Intangible Assets, Net
10  28798         Goodwill And Other Intangible Assets, Net Note
11  30660                   Goodwill And Other Intangible Assets

In [55]:
mask = df['line_item'].str.contains(r"Goodwill",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Intangible",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Other",case=True, regex=True, na=False) & \
          df['line_item'].str.contains(r"Accum",case=True, regex=True, na=False) & \
         ~df['line_item'].str.contains(r"Excl|Subsid|Total",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,4024,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 26,922 And 15,007 At Dec..."
1,9634,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 35,281 And 26,922 At Dec..."
2,10069,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,155 And 68,305 At Dec..."
3,14789,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 57,561 And 51,754 At Dec..."
4,15746,"Goodwill And Other Intangible Assets, Less Accumulated Amortization"
5,17396,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 68,305 And 65,949 At Dec..."
6,21175,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 63,099 And 60,080 At Dec..."
7,26013,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,221 And 70,155 At Dec..."
8,27273,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 51,754 And 45,379 At Dec..."
9,29980,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 65,949 And 63,099 At Dec..."
10,29989,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 45,379 And 35,281 At Dec..."
11,30092,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 60,080 And 57,561 At Dec..."
12,31712,"Goodwill And Other Intangible Assets Net Of Accumulated Amortization Of 70,118 And 70,221 At Dec..."

### Common Stock

In [56]:
mask = df['line_item'].str.contains(r"^Common Stock",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Additional Paid",case=False, regex=True, na=False)
     
df[mask].reset_index()

,index,line_item
0,2543,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
1,2820,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
2,3075,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,298 An..."
3,3964,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value; 12,600,000 Shares Authorized; 5,..."
4,3987,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 126,464..."
5,4080,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
6,4236,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
7,4385,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 127,386..."
8,4437,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 219.4 Outs..."
9,4478,"Common Stock And Additional Paid-In Capital, 0.001 Par Value; 2,900 Shares Authorized; 408 And 4..."
10,4537,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital; Shares Authorized: 4,687,..."
11,4811,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,5..."
12,5869,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000 Issued ..."
13,5992,"Common Stock And Additional Paid-In Capital: 0.001 Par Value; Shares Authorized: 150,000; Shares..."
14,6281,Common Stock And Additional Paid-In-Capital
15,6444,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 99.6 A..."
16,6647,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized As Of December 31, 2021 And..."
17,6758,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
18,6932,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 97.3 A..."
19,7170,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,110 An..."
20,7490,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000,000 Iss..."
21,7565,"Common Stock And Additional Paid-In Capital: 0.001 Par Value; Shares Authorized: 150,000; Shares..."
22,7641,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
23,8354,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 240 And 263..."
24,8702,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,5..."
25,8807,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized As Of December 31, 2022 And..."
26,8823,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,5..."
27,8882,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
28,9324,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital; Shares Authorized: 4,687,..."
29,9445,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750; 215 And 218 ..."
30,9723,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
31,9871,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
32,10211,"Common Stock, No Par Value, Including Additional Paid-In Capital"
33,10290,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
34,10667,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,5..."
35,11146,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 219.4 Outs..."
36,11301,"Common Stock And Additional Paid-In Capital, 0.001 Par Value And 200,000 Shares Authorized, Issu..."
37,11371,"Common Stock And Additional Paid-In Capital: 0.001 Par Value; Shares Authorized: 150,000; Shares..."
38,12001,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 220.3 Outs..."
39,12275,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 227.0 Outs..."
40,12566,"Common Stock, Par Value 0.20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,..."
41,12949,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,029 An..."
42,13156,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,614 An..."
43,13474,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 91.5 A..."
44,13998,"Common Stock And Additional Paid-In Capital, 300,000 Shares Authorized, 0.01 Par Value, 124,129 ..."
45,14263,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
46,14296,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,217 An..."
47,14481,"Common Stock And Additional Paid-In Capital: 0.001 Par Value; Shares Authorized: 150,000; Shares..."
48,14854,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 281 And 306 Shares Issued And Outs..."
49,14906,"Common Stock And Additional Paid-In Capital, 0.001 Par Value; Shares Authorized: 150,000; Shares..."
50,14917,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 12,600,000 Shares Authorized; 5,..."
51,14991,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
52,15063,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 226.7 Outs..."
53,15212,"Common Stock, Par Value 0.20 Per Share, And Additional Paid-In Capital, Shares Authorized: 4,687..."
54,15528,"Common Stocks, Including Additional Paid In Capital, Net Of Discount"
55,15605,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 50,400,000 Shares Authorized; 16..."
56,15819,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized At December 31, 2019 And 20..."
57,15962,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 50,400,000 Shares Authorized; 16..."
58,15973,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
59,16493,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,237 An..."
60,16626,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,250 An..."
61,16718,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
62,17181,"Common Stock, Par Value 0.20 Per Share, And Additional Paid-In Capital; Shares Authorized: 4,687..."
63,17514,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 96.8 A..."
64,18090,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 219 And 240..."
65,18162,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,107 An..."
66,18350,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000,000 Iss..."
67,18378,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
68,18435,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
69,18445,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital; Shares Authorized: 4,687,..."
70,18901,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,389 An..."
71,18977,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 12,600,000 Shares Authorized; 4,..."
72,19147,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 218.2 And ..."
73,19934,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 224.4 Outs..."
74,20497,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 4,983 An..."
75,20659,Common Stock And Additional Paid-In Capital
76,20933,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 220 And 222..."
77,20980,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized At December 31, 2018 And 20..."
78,21040,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 96.3 A..."
79,21091,"Common Stock And Additional Paid-In Capital, 0.001 Par Value And 200,000 Shares Authorized, Issu..."
80,21309,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,085 An..."
81,21509,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
82,21904,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 1,000.0 Shares Authorized; 90.5 A..."
83,22059,"Common Stock And Additional Paid-In Capital, 0.001 Par Value; Shares Authorized: 150,000; Shares..."
84,22093,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; -- Outstan..."
85,22125,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000 Issued ..."
86,23056,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 12,600,000 Shares Authorized; 4,..."
87,23383,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 50,400,000 Shares Authorized; 15..."
88,23762,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 12,600,000 Shares Authorized; 5,..."
89,23816,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
90,24082,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 263 And 269..."
91,24164,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000,000 Iss..."
92,24560,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 218.3 Outs..."
93,24581,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
94,24816,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 223.6 Outs..."
95,25277,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized At December 31, 2017 And 20..."
96,25634,"Common Stock, Par Value .20 Per Share, And Additional Paid-In Capital Shares Authorized: 4,687,5..."
97,25652,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 119,063..."
98,25923,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: Authorized Shares 200,000 Issued ..."
99,26464,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value Per Share; 2,750.0 Shares Authoriz..."
100,26749,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 106,303..."
101,27291,"Common Stock And Additional Paid-In Capital, 0.00001 Par Value: 12,600,000 Shares Authorized; 5,..."
102,27299,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
103,27587,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 269 And 281..."
104,27665,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 114,625..."
105,27788,"Common Stock And Additional Paid-In Capital, 0.001 Par Value: 20,000 Shares Authorized; 5,435 An..."
106,28180,"Common Stock And Additional Paid-In Capital, 300,000 Shares Authorized, 0.01 Par Value, 119,378 ..."
107,28720,"Common Stock And Additional Paid-In Capital, 0.01 Par Value, 2,000 Shares Authorized; 433.4 Shar..."
108,28866,"Common Stock And Additional Paid-In Capital, 400.0 Shares Authorized At December 31, 2020 And 20..."
109,28896,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
110,28915,"Common Stock And Additional Paid-In Capital, 0.001 Par Value, 885 Shares Authorized; 222 And 219..."
111,29335,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Shares Authorized 750.0; 219.6 And ..."
112,29647,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 112,557..."
113,29833,"Common Stock, Par Value 0.20 Per Share, And Additional Paid-In Capital; Shares Authorized: 4,687..."
114,29881,"Common Stocks, Including Additional Paid In Capital"
115,30148,"Common Stock And Additional Paid-In Capital, 0.001 Par Value; Shares Authorized: 150,000; Shares..."
116,30161,"Common Stock And Additional Paid-In Capital, 400.0 And 300.0 Shares Authorized At December 31, 2..."
117,30380,"Common Stock And Additional Paid-In Capital, 300,000 And 150,000 Shares Authorized At December 3..."
118,30651,"Common Stock And Additional Paid-In Capital, .0001 Par Value; 405,000 Shares Authorized; 126,322..."
119,31034,"Common Stock And Additional Paid-In Capital, 0.01 Par Value; Authorized – 12,800,000,000 Shares;..."
120,31733,"Common Stock And Additional Paid-In Capital; 0.0001 Par Value; 2,750.0 Shares Authorized; Outsta..."
121,31902,"Common Stock And Additional Paid-In Capital, 0.001 Par Value; Shares Authorized: 150,000; Shares..."

### Preferred Stock

In [57]:
mask = df['line_item'].str.contains(r"^Preferred Stock",case=True, regex=True, na=False)
     
df[mask].reset_index()

,index,line_item
0,1,"Preferred Stock-0.0001 Par Value Per Share, 10,000,000 Shares Authorized, No Shares Issued Or Ou..."
1,2,"Preferred Stock Par Value 0.01; 100,000,000 Shares Authorized; No Shares Issued"
2,5,"Preferred Stock, .01 Par Value, 25,000,000 Shares Authorized, No Shares Issued Or Outstanding"
3,7,"Preferred Stock, 0.001 Par Value, 5,000 Authorized, No Shares Issued And Outstanding At June 30,..."
4,10,"Preferred Stock, 0.01 Par Value: 20,000,000 Shares Authorized, No Shares Issued And Outstanding ..."
...,...,...
1774,32031,"Preferred Stock: 0.0001 Par Value—5,000,000 Shares Authorized; None Issued"
1775,32047,"Preferred Stock, No Par Value; 10,000 Shares Authorized, No Shares Outstanding"
1776,32055,"Preferred Stock, No Par Value, At Stated Value; 27 Shares Authorized; No Shares Issued Or Outsta..."
1777,32058,"Preferred Stock Aggregate Liquidation Preference Of 1,688 And 1,538"
1778,32065,"Preferred Stock, 1.00 Par Value"

### Cash and Cash Equivalent

In [58]:
mask = df['line_item'].str.contains(r"Cash",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equivalent",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Total|Restricted|Disc|Marg|Reg",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,0,Cash And Cash Equivalents
1,796,Current Assets And Cash Equivalents:
2,1482,Cash And Cash Equivalents:
3,2473,Cash And Cash Equivalents Of Cip
4,2598,"Cash And Cash Equivalents Includes Pledged Assets Of 1,648,545 And 1,581,775, Respectively"
5,3414,"Cash And Cash Equivalents, At Cost, Which Approximates Fair Value"
6,4053,"Cash And Cash Equivalents, Including Short-Term Investments Of 1,110 And 3,008"
7,4492,"Cash And Cash Equivalents Including Cash Pledged As Collateral Of 620,681 And 1,584,686, Respect..."
8,5250,"Cash And Cash Equivalents Including Cash Pledged As Collateral Of 1,584,686 And 1,584,701, Respe..."
9,5493,"Cash And Cash Equivalents Including Cash Pledged As Collateral Of 1,428,475 And 1,584,686, Respe..."
10,6474,"Cash And Cash Equivalents 3,406 And 3,409 As Of December 31, 2020 And 2019, Respectively, For Jo..."
11,6560,"Cash And Cash Equivalents Mplx: 234 And 43, Respectively"
12,8316,"Cash And Cash Equivalents 3,395 And 3,382 As Of December 31, 2022 And 2021, Respectively, For Jo..."
13,9456,"Cash, Including Cash Equivalents"
14,10347,"Cash And Cash Equivalents Includes Pledged Assets Of 1,222,505 And 1,137,809, Respectively"
15,10578,"Cash And Cash Equivalents 3,382 And 3,406 As Of December 31, 2021 And 2020, Respectively, For Jo..."
16,11546,"Cash, Cash Equivalents And Marketable Securities"
17,14200,"Cash And Cash Equivalents, Including Short-Term Investments Of 3 And 130"
18,14716,"Cash And Cash Equivalents, Including Short-Term Investments Of 130 And 194"
19,16448,"Cash And Cash Equivalents, At Carrying Value"
20,17413,"Cash And Cash Equivalents Hep: 10,917 And 14,381, Respectively"
21,17490,"Cash And Cash Equivalents Including Cash Pledged As Collateral Of 1,584,701 And 371,790, Respect..."
22,17756,"Cash And Cash Equivalents, December 31"
23,17836,Cash & Cash Equivalents
24,17886,Cash And Equivalents
25,19108,Cash Equivalents
26,19980,"Cash And Cash Equivalents Includes Pledged Assets Of 1,581,775 And 579,213, Respectively"
27,20534,"Cash Equivalents, At Carrying Value"
28,21795,Cash And Cash Equivalents Note
29,22839,"Cash And Cash Equivalents, At Cost, Which Approximates Market"
30,22952,Cash And Cash Equivalents
31,23254,"Cash And Cash Equivalents, Including Short-Term Investments Of 1,520 And"
32,23936,Cash And Cash Equivalents Of Consolidated Investment Products
33,24244,"Cash And Cash Equivalents, Including Short-Term Investments Of 3,008 And 1,520"
34,27621,"Cash And Cash Equivalents, Principally At Estimated Fair Value"
35,28187,"Cash And Cash Equivalents Includes Pledged Assets Of 1,424,160 And 1,222,505, Respectively"
36,30682,"Cash, Cash Equivalents And Investment Securities"
37,30948,"Cash And Cash Equivalents Mplx: 5 And 234, Respectively"
38,31376,"Cash And Cash Equivalents Includes Pledged Assets Of 1,137,809 And 1,648,545, Respectively"

In [59]:
mask = df['line_item'].str.contains(r"Cash",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equivalent",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Total",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Total Restricted",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,2972,"Total Cash, Cash Equivalents, Restricted Cash And Restricted Cash Equivalents"
1,5114,"Total Cash, Cash Equivalents, And Marketable Securities"
2,5240,Total Cash And Cash Equivalents And Marketable Securities
3,6229,"Total Cash, Cash Equivalents, Restricted Cash, And Restricted Cash Equivalents"
4,6765,Cash Equivalents And Short-Term Investments Total
5,8751,"Total Cash And Cash Equivalents Restricted 1.2 Million On December 31, 2013 And On December 31..."
6,8761,"Total Cash, Cash Equivalents And Marketable Securities"
7,14689,"Total Cash And Cash Equivalents Restricted-- Million On December 31, 2012 And 4.9 Million On Dec..."
8,15928,Total Cash And Equivalents And Short-Term Investments
9,17269,"Total Cash, Cash Equivalents And Restricted Cash"
10,17817,"Total Cash, Cash Equivalents And Short-Term Investments"
11,18161,"Total Cash, Cash Equivalents And Investment Securities"
12,19529,"Total Cash, Cash Equivalents, And Restricted Cash"
13,21126,"Total Cash, Cash Equivalents, And Short-Term Investments"
14,23438,"Total Cash And Cash Equivalents Restricted 4.9 Million On December 31, 2011 And 3.1 Million On ..."
15,23819,"Total Unrestricted Cash, Cash Equivalents And Short-Term Investments"
16,26565,"Total Cash, Cash Equivalents And Short-Term Investment Securities"
17,26876,Total Cash And Cash Equivalents
18,27069,"Total Cash, Cash Equivalents, And Marketable Securities Including Securities Loaned Of 4,531 And"
19,28020,"Total Cash, Cash Equivalents, And Marketable Securities Including Securities Loaned Of 4,058 And..."
20,31795,"Total Cash, Cash Equivalents And Short-Term Investments In Marketable Securities"
21,31990,Total Cash And Cash Equivalents And Restricted Cash And Cash Equivalents

In [60]:
mask = df['line_item'].str.contains(r"Cash",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equivalent",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"^Restricted",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,248,Restricted Cash And Cash Equivalents
1,3160,Restricted Cash Equivalents—U.S. Litigation Escrow
2,5566,"Restricted Cash, Cash Equivalents And Short-Term Investments"
3,7930,"Restricted Cash, Cash Equivalents And Marketable Investment Securities"
4,12708,Restricted Cash And Cash Equivalents:
5,14216,Restricted Cash And Cash Equivalents Alios
6,17972,"Restricted And Segregated Cash, Cash Equivalents And Investments"
7,20266,"Restricted Cash And Cash Equivalents, Current"
8,21296,Restricted Cash And Cash Equivalents
9,23238,Restricted Cash Equivalents
10,24097,Restricted Cash And Restricted Cash Equivalents
11,24717,Restricted Cash And Cash Equivalents Note
12,25070,"Restricted Cash, Cash Equivalents And Investments"
13,25279,Restricted Cash And Equivalents

In [61]:
mask = df['line_item'].str.contains(r"Cash",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equivalent",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Restricted$",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"^Restricted",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg",case=True, regex=True, na=False)

df[mask].reset_index()

   index                               line_item
0  17529   Cash And Cash Equivalents  Restricted
1  20806  Cash And Cash Equivalents – Restricted

In [62]:
mask = df['line_item'].str.contains(r"Cash",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Equivalent",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Restricted",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Incl",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"^Restricted",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg|Total",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,3051,"Cash And Cash Equivalents, Including Restricted Cash Of 3,635 And 0, Respectively"
1,9721,"Cash And Cash Equivalents, Including Restricted Cash Of 18,000 As Of December 31, 2010"
2,12097,"Cash And Cash Equivalents Including Restricted Cash Of 200 At December 31, 2012"
3,13875,Cash And Cash Equivalents Including Restricted Cash Of 35.8 In 2021 And 73.2 In 2020
4,17426,Cash And Cash Equivalents Including Restricted Cash Of 14.5 In 2022 And 35.8 In 2021
5,17781,"Cash And Cash Equivalents, Including Restricted Cash Of 0 And 1,907, Respectively"
6,19469,"Cash And Cash Equivalents, Including Restricted Cash Of 1,500 And 3,635, Respectively"
7,22150,"Cash And Cash Equivalents, Including Restricted Cash Of 3,497 And 1,500, Respectively"
8,23433,"Cash And Cash Equivalents Including Restricted Cash Of 73,200 In 2020 And 0 In 2019"
9,31050,"Cash And Cash Equivalents, Including Restricted Cash Of 1,907 And 3,497, Respectively"

### Short Term Investments

In [63]:
mask = df['line_item'].str.contains(r"Invest",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Short.*Term",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Cash|Secur",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree|Amort|^Other",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg|Total",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,3203,Short-Term Investment
1,3415,Short-Term Investments
2,3626,Sigma Fund And Short-Term Investments
3,4100,Short-Term Investments Net Of Allowance For Credit Losses: 2021-0; 2020
4,4939,Short-Term Investments Available-For-Sale
5,5092,"Short-Term Investments, Net"
6,6002,Short-Term Investments:
7,6121,"Short-Term Investments, At Quoted Market Value Cost Of 4.6 And 4.8"
8,6276,Short-Term And Other Investments
9,6720,"Short-Term Investments Cost: 2020, 1,135,088; 2019, 414,639"
10,6755,"Short-Term Investments Cost: 2018, 241,010; 2017, 509,682"
11,7148,"Short-Term Investments, At Quoted Market Value Cost Of 4.8 And 9.6"
12,7487,Short-Term Available-For-Sale Investments
13,9177,"Short-Term Investments Cost: 2019, 414,639 ; 2018, 241,010"
14,9311,"Short-Term Investments Portion Measured At Fair Value: 2016 3,341; 2015 2,591"
15,9845,"Short-Term Investments Portion Measured At Fair Value: 2012 8,056; 2011 5,913"
16,10668,"Short-Term Investments Cost: 2021, 1,178,386; 2020, 1,135,088"
17,11124,"Short-Term Investments, At Fair Value"
18,11977,"Short-Term Investments, Available-For-Sale Estimated Fair Value Approximates Cost"
19,13807,Investments In Short-Term Commercial Paper
20,14571,Deposits With Banks And Short-Term Investments
21,14696,"Investments, Short-Term"
22,15226,Time Deposits Placed And Other Short-Term Investments
23,16066,Short-Term Investments Net Of Allowance For Credit Losses: 2022-6; 2021
24,16497,"Short-Term Investments, Available-For-Sale"
25,17404,Short-Term Investments At Fair Value Which Approximates Cost
26,17734,"Short-Term Investments Portion Measured At Fair Value: 2014 1,684; 2013 6,313"
27,18842,Investment In Short-Term Commercial Paper
28,19073,"Short-Term Investments, Principally At Estimated Fair Value"
29,20718,"Short-Term Investments Cost: 2022, 1,032; 2021, 1,178"
30,20810,"Short Term Investments, At Fair Value"
31,21295,Short-Term Investments At Cost Which Approximates Fair Value
32,22682,"Short-Term Investments Portion Measured At Fair Value: 2017 2,615; 2016 3,341"
33,23563,Investments Short-Term
34,24384,Short Term Investments
35,25978,Short-Term Investments Note
36,27309,Short-Term Investments 2020-Net Of 1 Allowance For Credit Losses
37,28359,Short-Term Investments Estimated Fair Value Approximates Cost
38,28700,Short-Term Investments See Note
39,28959,"Short-Term Investments, At Cost"
40,29422,"Short-Term Investments Portion Measured At Fair Value: 2013 6,313; 2012 8,056"
41,30088,"Short-Term Investments, At Quoted Market Value Cost Of 4.8 And 4.8"
42,30229,"Short-Term Investments, At Fair Value Note"
43,31283,"Short-Term Investments Portion Measured At Fair Value: 2015 2,591; 2014 1,684"

In [64]:
mask = df['line_item'].str.contains(r"Invest",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Short.*Term",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Amort",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Avail",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree|^Other",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg|Total",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,340,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 1,332,996 And 1,734,738..."
1,2639,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 1,477,584 And 719,848"
2,6186,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 801,758 And 1,477,584"
3,6540,"Short-Term Investments Available-For-Sale, At Fair Value Amortized Cost: 85,246 In 2021 And 0 In..."
4,10856,"Short-Term Investments Available-For-Sale, At Fair Value Amortized Cost: 8,171 In 2018 And 0 In ..."
5,12646,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 909,121 And 913,488"
6,12815,"Short-Term Investments Available-For-Sale Debt Securities: Amortized Cost Of 176 And 25, Respect..."
7,16142,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 611,878 And 591,141"
8,18748,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 1,924,292 And 957,283; ..."
9,19554,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 719,848 And 909,121"
10,20567,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 956,238 And 1,468,955"
11,22618,"Short-Term Investments Available-For-Sale, At Fair Value Amortized Cost: 0 In 2019 And 8,171 In ..."
12,22660,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 1,468,955 And 611,878"
13,24454,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 591,141 And 801,758"
14,25910,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 957,283 And 956,238"
15,26724,"Short-Term Investments Available For Sale, At Fair Value Amortized Cost: 1,734,738 And 1,924,292..."
16,28413,"Short-Term Investments Available-For-Sale, At Fair Value Amortized Cost: 69,393 In 2022 And 85,2..."
17,28590,"Short-Term Investments Available-For-Sale Debt Securities: Amortized Cost Of 500 And 998, Respec..."
18,30430,"Short-Term Investments Available-For-Sale Debt Securities: Amortized Cost Of 25 And 500, Respect..."

In [65]:
mask = df['line_item'].str.contains(r"Invest",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Short.*Term",case=True, regex=True, na=False) & \
         df['line_item'].str.contains(r"Amort",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Avail",case=True, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Vie|Exchange|interest|Held",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Related|Agree|^Other",case=False, regex=True, na=False) & \
        ~df['line_item'].str.contains(r"Disc|Marg|Reg|Total",case=True, regex=True, na=False)

df[mask].reset_index()

,index,line_item
0,3441,"Short-Term Investments Amortized Cost: 1,990.0 And 1,551.8"
1,4808,"Short-Term Investments Amortized Cost: 5,218.5 And 1,798.8"
2,5744,"Short-Term Investments Amortized Cost: 1,551.8 And 1,090.8"
3,8755,"Short-Term Investments Amortized Cost: 2,869.4 And 3,572.9"
4,10648,"Short-Term Investments Amortized Cost: 942.6 And 5,218.5"
5,13400,"Short-Term Investments Amortized Cost: 3,572.9 And 2,172.0"
6,13850,"Short-Term Investments, At Amortized Cost And Fair Value"
7,14552,"Short-Term Investments Amortized Cost: 2,149.0 And 1,272.6"
8,15010,"Short Term Investments, At Fair Value Amortized Cost 4,671,581 At December 31, 2022 2021 5,298..."
9,16188,"Short-Term Investments, At Fair Value Amortized Cost – 3,147 And 4,349"
10,16593,"Short-Term Investments Amortized Cost: 2,172.0 And 2,149.0"
11,17079,"Short-Term Investments, At Fair Value Amortized Cost 4,349 And 4,291"
12,19227,"Short-Term Investments, At Fair Value Amortized Cost – 4,962 And 3,147"
13,19869,"Short-Term Investments Amortized Cost: 1,795.9 And 2,869.4"
14,21340,"Short-Term Investments, At Amortized Cost Which Approximates Fair Value"
15,21838,Short-Term Investments Amortized Cost
16,22930,"Short-Term Investments Amortized Cost: 1,272.6 And 1,990.0"
17,25113,"Short-Term Investments, At Fair Value And Amortized Cost"
18,27107,"Short-Term Investments Amortized Cost: 2,861.7 And 942.6"
19,27953,"Short-Term Investments Amortized Cost: 1,798.8 And 1,795.9"
20,31310,"Short-Term Investments, At Amortized Cost"